### ISSUE TITLE
Multiple issues while using latest SDK 2.3.0

### ISSUE THREAD

**Issue by drbcode** [dart-lang/build#2268] opened 2019-05-12 00:16 UTC
Experiencing multiple issues:
- Some messages are getting lost, as you can see in the preview while starting a build.
- When files are saved without making any changes, sometimes build fails sometimes it succeeds.
- Line of dashes is no longer present while starting a build making different build tasks indistinguishable: see https://github.com/dart-lang/build/pull/1276 and https://github.com/dart-lang/build/issues/1269

![build_issue](https://user-images.githubusercontent.com/41248528/57576238-5e63b100-7478-11e9-949d-22c36e739e2a.gif)

Dart VM version: 2.3.0 (Fri May 3 10:32:31 2019 +0200) on "linux_x64"
build: version: "1.1.4"
build_config: version: "0.3.2"
build_daemon: version: "0.5.0"
build_modules: version: "2.1.2"
build_resolvers: version: "1.0.4"
build_runner: version: "1.3.3"
build_runner_core: version: "3.0.3"
build_web_compilers: version: "2.0.0"
built_collection: version: "4.2.1"
built_value: version: "6.5.0"

**Comment by natebosch** [comment] 2019-05-22 23:52
> - Some messages are getting lost, as you can see in the preview while starting a build.

@jakemac53 @grouma - is this related to the logging stuff you have been looking at?

> - Line of dashes is no longer present while starting a build making different build tasks indistinguishable

@jakemac53 @grouma - this would be good to restore in webdev. Can we look at adding this along with the logging changes?

> - When files are saved without making any changes, sometimes build fails sometimes it succeeds.

@drbcode - can you repro this? I don't think we've gotten other recent reports of non-hermetic failures and this would be surprising.

The recording seems to be highlighting a difference between compilation errors and analyzer output which is a different problem that isn't mentioned. It's hard to tell for sure but I _think_ it's because your errors are in a dependency and the empty analyzer diagnostics are probably just for your root package. Have you run analyzer on the dependencies?

**Comment by grouma** [comment] 2019-05-23 00:30
> > * Some messages are getting lost, as you can see in the preview while starting a build.
> 
> @jakemac53 @grouma - is this related to the logging stuff you have been looking at?
> 

I believe this will be addressed with version `1.5.0` of `build_runner` which will depend on the latest `build_daemon` version.

> > * Line of dashes is no longer present while starting a build making different build tasks indistinguishable
> 
> @jakemac53 @grouma - this would be good to restore in webdev. Can we look at adding this along with the logging changes?
> 

This is not something that will be addressed with the latest changes. I agree we should restore this. Should this line be pushed from `build_runner` or should we add it on the `webdev` side? I don't have a strong preference.

**Comment by drbcode** [comment] 2019-05-23 05:54
> When files are saved without making any changes, sometimes build fails sometimes it succeeds.

This issue is reproducible only while migrating from an older version to a newer version, after calling 
`pub cache repair` and using the new SDK with updated dependencies and deleting `pubspec.lock` and `.dart_tool` the issue is gone.

**Comment by jakemac53** [comment] 2019-06-03 18:12
I believe we have now landed fixes for all the issues except for the one about touching files without making changes, which doesn't sound like it is worth taking action on. On the latest sdk/packages I can't reproduce it at least.

**Closed by jakemac53** 2019-06-03 18:12 UTC
