### ISSUE TITLE
Support for transient assets in build_runner

### ISSUE THREAD

**Issue by natebosch** [dart-lang/build#281] opened 2017-04-26 00:15 UTC
Transformers can 'consume' assets, and bazel let's us write arbitrary files that effectively disappear if we don't declare them as outputs.

We should support something like this in build_runner. Potentially this could be something like assets which live only in memory during a build. Invalidation might get a little tricky, and the configuration will be tough to get right.

**Comment by jakemac53** [comment] 2017-04-26 17:40
duplicate of https://github.com/dart-lang/build/issues/189 :)

**Closed by jakemac53** 2017-04-26 17:40 UTC
