### ISSUE TITLE
Cannot open file, path = '.dart_tool/build/entrypoint/build.dart.dill.cached'

### ISSUE THREAD

**Issue by urmatt** [dart-lang/build#3664] opened 2024-04-01 02:04 UTC
I'm getting error when I running `dart run build_runner build` command also with `--delete-conflicting-outputs`.

I can't remember which actions I doing before that error. But I don't added new packages and before it works fine.

The error if following:

```
PathNotFoundException: Cannot open file, path = 
'.dart_tool/build/entrypoint/build.dart.dill.cached' (OS Error: No such file or directory, errno = 2)
#0      _checkForErrorResponse (dart:io/common.dart:55)
#1      _File.open.<anonymous closure> (dart:io/file_impl.dart:381)
<asynchronous suspension>
#2      _FileStreamConsumer.addStream.<anonymous closure> (dart:io/file_impl.dart:205)
<asynchronous suspension>
```

Flutter version 3.19.5

_No issues found!_ by flutter doctor

**Comment by jakemac53** [comment] 2024-04-01 14:32
Interesting, do you see any other error prior to this? You should see a log about compiling your build script, did that say it completed successfully, or did it have an error?

**Comment by urmatt** [comment] 2024-04-05 05:44
With this error message it brokens. I cleaned pub cache, flutter clean, removed all generated folders and files nothing helped. **At the end** I copied project from git again in new folder **and then error disappeared**.

**Comment by jakemac53** [comment] 2024-04-05 16:06
Ok, I am going to close this because I can't reproduce it, and you seem unblocked. If we get further reports with a reproduction case we can look into it.

**Closed by jakemac53** 2024-04-05 16:06 UTC
