### ISSUE TITLE
CTRL-C during `Delete these files?` prompt should work (cancel)

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/build#1472] opened 2018-05-18 23:16 UTC
```
Delete these files?
1 - Delete
2 - Cancel build
3 - List conflicts
```

Right now it does nothing...

**Comment by natebosch** [comment] 2018-05-19 00:43
Duplicate of #322 

This is hard to fix.

**Closed by natebosch** 2018-05-19 00:43 UTC
Labels: package: build_runner
