### ISSUE TITLE
InvalidOutputException when using `watch` but not when using `build`

### ISSUE THREAD

**Issue by Andersmholmgren** [dart-lang/build#118] opened 2016-07-09 05:50 UTC
If I use the `build` function I can run the build as many times as I like and all is well, but when I change it to use `watch` then it runs once but then on changes blows up with

```
InvalidOutputException: Asset: jason_schemer|lib/src/m2m/schema_to_vcore.g.forwards.dart
Cannot overwrite inputs.
```

`jason_schemer|lib/src/m2m/schema_to_vcore.g.forwards.dart` is an output but this seems to suggest `watch` is thinking it is an input too

**Comment by jakemac53** [comment] 2016-07-11 14:57
Can you provide repro instructions? In the general case this works, so there is probably something specific going on in your case.

**Comment by jakemac53** [comment] 2017-01-29 01:17
closing as a duplicate of https://github.com/dart-lang/build/issues/175 which has good repro instructions.

**Closed by jakemac53** 2017-01-29 01:17 UTC
