### ISSUE TITLE
You have hit a bug in build_runner

### ISSUE THREAD

**Issue by 926** [dart-lang/build#2541] opened 2019-11-13 18:29 UTC
(obeying the terminal)
Please file an issue with reproduction steps at https://github.com/dart-lang/build/issues

type 'DynamicTypeImpl' is not a subtype of type 'InterfaceType'
package:analyzer/src/summary/link.dart 5535:5                     TypeProviderForLink._buildInterfaceType
package:analyzer/src/summary/link.dart 5503:23                    TypeProviderForLink.objectType
package:analyzer/src/summary/link.dart 925:67                     ClassElementForLink_Class._computeInterfaceType
package:analyzer/src/summary/link.dart 823:27                     ClassElementForLink_Class.supertype
package:analyzer/src/task/strong_mode.dart 303:33                 InstanceMemberInferrer._inferClass
package:analyzer/src/task/strong_mode.dart 335:9                  InstanceMemberInferrer._inferClasses
package:analyzer/src/task/strong_mode.dart 56:5                   InstanceMemberInferrer.inferCompilationUnit
package:analyzer/src/summary/link.dart 1627:7                     CompilationUnitElementInBuildUnit.link
package:analyzer/src/summary/link.dart 3840:12                    LibraryElementInBuildUnit.link
package:analyzer/src/summary/link.dart 3540:15                    LibraryCycleNode.link
package:analyzer/src/summary/link.dart 3480:7                     LibraryCycleDependencyWalker.evaluate
package:analyzer/src/summary/link.dart 2213:13                    DependencyWalker.walk.strongConnect
package:analyzer/src/summary/link.dart 2179:24                    DependencyWalker.walk.strongConnect
package:analyzer/src/summary/link.dart 2179:24                    DependencyWalker.walk.strongConnect
package:analyzer/src/summary/link.dart 2232:18                    DependencyWalker.walk
package:analyzer/src/summary/link.dart 3513:42                    LibraryCycleForLink.ensureLinked
package:analyzer/src/summary/link.dart 4045:35                    Linker.link
package:analyzer/src/summary/link.dart 311:74                     _relink
package:analyzer/src/summary/link.dart 125:3                      link
package:analyzer/src/dart/analysis/library_context.dart 220:25    LibraryContext.load.<fn>
package:analyzer/src/dart/analysis/performance_logger.dart 34:15  PerformanceLog.run
package:analyzer/src/dart/analysis/library_context.dart 219:12    LibraryContext.load
package:analyzer/src/dart/analysis/library_context.dart 98:7      new LibraryContext
package:analyzer/src/dart/analysis/driver.dart 1626:29            AnalysisDriver._createLibraryContext
package:analyzer/src/dart/analysis/driver.dart 1570:26            AnalysisDriver._computeUnitElement
package:analyzer/src/dart/analysis/driver.dart 1170:34            AnalysisDriver.performWork
package:analyzer/src/dart/analysis/driver.dart 2188:24            AnalysisDriverScheduler._run
package:analyzer/src/dart/analysis/driver.dart 2118:5             AnalysisDriverScheduler.start
package:build_resolvers/src/analysis_driver.dart 54:13            analysisDriver
package:build_resolvers/src/resolver.dart 138:18                  new AnalyzerResolvers
package:build_runner_core/src/generate/options.dart 132:19        BuildOptions.create
package:build_runner/src/generate/build.dart 84:36                build
package:build_runner/src/entrypoint/build.dart 28:24              BuildCommand.run
package:args/command_runner.dart 197:27                           CommandRunner.runCommand
package:args/command_runner.dart 112:25                           CommandRunner.run.<fn>
dart:async                                                        new Future.sync
package:args/command_runner.dart 112:14                           CommandRunner.run
package:build_runner/src/entrypoint/run.dart 24:31                run
.dart_tool/build/entrypoint/build.dart 26:22                      main

**Comment by jakemac53** [comment] 2019-11-13 18:41
Duplicate of https://github.com/dart-lang/build/issues/2502 - tldr; you need to upgrade your dependencies using `pub upgrade` or `flutter pub upgrade`.

**Closed by jakemac53** 2019-11-13 18:41 UTC
