### ISSUE TITLE
You have hit a bug in build_runner while running angular dart application

### ISSUE THREAD

**Issue by tejaswi-gayathri** [dart-lang/build#2535] opened 2019-11-06 15:53 UTC
Hello,

I'm using dart sdk version 2.6.0, build_runner version is 1.2.3 and Windows machine. 
All the dependencies are obtained fine using pub get command. 
While executing the command **pub run build_runner serve** , it's giving the following error:

`[INFO] Generating build script completed, took 750ms
[INFO] Creating build script snapshot... completed, took 29.5s

You have hit a bug in build_runner
Please file an issue with reproduction steps at https://github.com/dart-lang/build/issues

NoSuchMethodError: The getter 'futureDynamicType' was called on null.
Receiver: null
Tried calling: futureDynamicType
dart:core                                                       Object.noSuchMethod
package:analyzer/src/dart/element/element.dart 5853:40          LibraryElementImpl.createLoadLibraryFunctionForLibrary
package:analyzer/src/dart/element/element.dart 5703:9           LibraryElementImpl.createLoadLibraryFunction
package:analyzer/src/summary/resynthesize.dart 339:24           SummaryResynthesizer.getLibraryElement.<fn>
dart:collection                                                 _LinkedHashMapMixin.putIfAbsent
package:analyzer/src/summary/resynthesize.dart 327:36           SummaryResynthesizer.getLibraryElement
package:analyzer/src/summary/resynthesize.dart 390:20           SummaryResynthesizer._buildTypeProvider
package:analyzer/src/summary/resynthesize.dart 178:5            new SummaryResynthesizer
package:analyzer/src/summary/package_bundle_reader.dart 346:9   new StoreBasedSummaryResynthesizer
package:analyzer/src/summary/package_bundle_reader.dart 322:26  ResynthesizerResultProvider.createResynthesizer
package:analyzer/src/summary/package_bundle_reader.dart 80:5    new InputPackagesResultProvider
package:analyzer/src/dart/sdk/sdk.dart 96:19                    AbstractDartSdk.context
package:analyzer/src/context/context.dart 1884:46               PartitionManager.forSdk
package:analyzer/src/context/context.dart 681:50                AnalysisContextImpl.createCacheFromSourceFactory.createCache
package:analyzer/src/context/context.dart 686:38                AnalysisContextImpl.createCacheFromSourceFactory
package:analyzer/src/context/context.dart 413:14                AnalysisContextImpl.sourceFactory=
package:build_resolvers/src/resolver.dart 95:14                 new AnalyzerResolver
package:build_resolvers/src/resolver.dart 449:32                new AnalyzerResolvers
package:build_runner_core/src/generate/options.dart 132:19      BuildOptions.create
package:build_runner/src/generate/watch_impl.dart 71:36         watch
package:build_runner/src/generate/build.dart 167:5              watch
package:build_runner/src/entrypoint/serve.dart 82:25            ServeCommand._runServe
package:build_runner/src/entrypoint/serve.dart 60:12            ServeCommand.run
package:args/command_runner.dart 197:27                         CommandRunner.runCommand
package:args/command_runner.dart 112:25                         CommandRunner.run.<fn>
dart:async                                                      new Future.sync
package:args/command_runner.dart 112:14                         CommandRunner.run
package:build_runner/src/entrypoint/run.dart 23:31              run
.dart_tool\build\entrypoint\build.dart 154:22                   main`

**Comment by jakemac53** [comment] 2019-11-06 15:58
Duplicate of https://github.com/dart-lang/build/issues/2502 - tldr; you need to upgrade your dependencies using `pub upgrade` or `flutter pub upgrade`.

**Closed by jakemac53** 2019-11-06 15:58 UTC
