### ISSUE TITLE
NullSafety "flutter pub run build_runner build" problem

### ISSUE THREAD

**Issue by yfer** [dart-lang/build#3046] opened 2021-03-13 11:49 UTC
I'm using new null-safety feature with dart and had a problem with build_runner.

```
 Error: Operator '[]' cannot be called on 'ArgResults?' because it is potentially null.
 - 'ArgResults' is from 'package:args/src/arg_results.dart' ('/C:/flutter/.pub-cache/hosted/pub.dartlang.org/args-2.0.0/lib/src/arg_results.dart').
    var verbose = parsedArgs.command['verbose'] as bool ?? false;
```
and
```
Failed to precompile build_runner:build_runner:
/c:/flutter/.pub-cache/hosted/pub.dartlang.org/build_runner-1.12.1/bin/build_runner.dart:101:9: Warning: Operand of null-aware operation '?.' has type 'StreamSubscription<dynamic>' which excludes null.
 - 'StreamSubscription' is from 'dart:async'.
  await logListener?.cancel();
```

**Fixed both of them, hence PR.** But of course I still got 

```
Error: Cannot run with sound null safety, because the following dependencies
don't support null safety:

 - package:build_runner_core
 - package:io
 - package:build_runner
 - package:build_config
 - package:build_daemon
 - package:timing
 - package:code_builder
 - package:dart_style
 - package:http_multi_server
 - package:shelf_web_socket
 - package:web_socket_channel
```
Tried to run `flutter pub run build_runner build --no-sound-null-safety`, it had no effect.

**Solution!!!**
The only thing that helped is manually insert `// @dart=2.9` at the beginning of bin/build_runner.dart, after that builder is working.

**Should we just include `// @dart=2.9` at the beginning of bin/build_runner.dart, so you at least don't see this problem untill null-safety is fully supported?**

```
- Flutter version 2.0.2 at C:\flutter
- Framework revision 8962f6dc68 (2 days ago), 2021-03-11 13:22:20 -0800
- Engine revision 5d8bf811b3
- Dart version 2.12.1
- What package(s) from this repo you are using: **build_runner 1.11.5**, **build_runner 1.12.1** and master
- What builder(s) you are using: **freezed 0.14.0+1**, but without any builders it fails the same
- Whether you are using? Windows
```

**Comment by simolus3** [comment] 2021-03-13 15:51
@yfer, how do you run `build_runner`? The package itself doesn't opt-in to null safety, so running `dart run build_runner build_runner build` should work (replace `dart` with `flutter pub` if you're using Flutter).

If you're using null-safety, make sure you're on `build_runner` version `1.10.4` or later. That adds the necessary `//@dart=2.9` comment to the generate build script, which might be what you're seeing here.

**Comment by natebosch** [comment] 2021-03-14 04:35
It looks like something it going wrong with the tooling here.

> ```
> Failed to precompile build_runner:build_runner:
> /c:/flutter/.pub-cache/hosted/pub.dartlang.org/build_runner-1.12.1/bin/build_runner.dart:101:9: Warning: Operand of null-aware operation '?.' has type 'StreamSubscription<dynamic>' which excludes null.
>  - 'StreamSubscription' is from 'dart:async'.
>   await logListener?.cancel();
> ```

`bin/build_runner.dart` should not be considered opted in to null safety at that version. The language version should be `2.11`

https://github.com/dart-lang/build/blob/build_runner-v1.12.1/build_runner/pubspec.yaml#L7

@yfer - what specific command did you run? Also, can you upload the content of your `.dart_too/package_config.json` file?

I suspect there is a bug in either the flutter or pub tooling. cc @jonahwilliams @jonasfj @jakemac53

**Comment by yfer** [comment] 2021-03-14 14:29
@natebosch 
I am running `C:\flutter\bin\flutter.bat pub run build_runner build`

>dart --version
Dart SDK version: 2.12.1 (stable) (Wed Mar 10 10:18:47 2021 +0100) on "windows_x64"

flutter doctor
    • Flutter version 2.0.2 at C:\flutter
    • Framework revision 8962f6dc68 (3 days ago), 2021-03-11 13:22:20 -0800
    • Engine revision 5d8bf811b3
    • Dart version 2.12.1

[.dart_tool/package_config.json](https://github.com/dart-lang/build/files/6136824/package_config.txt)

@simolus3 

build_runner version: "1.12.1", and also i've tried versions from 1.10.4 to 1.12.1

[pubspec.txt](https://github.com/dart-lang/build/files/6136827/pubspec.txt)

**Comment by jonahwilliams** [comment] 2021-03-14 16:39
For the most part `flutter pub run` is treated as a pass through: https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/commands/packages.dart#L238

**Comment by jakemac53** [comment] 2021-03-15 16:11
@yfer are you passing `--enable-experiment=non-nullable` possibly? That should be dropped now - I believe it would break any package with a min sdk constraint between 2.10 and 2.12 (exclusive) because it would opt them in to null safety (the "experiment release version" is 2.10, which is confusing).

Or @jonahwilliams is it possible flutter_tool is passing this?

**Comment by jonahwilliams** [comment] 2021-03-15 16:12
No, the tool doesn't pass any experiment flags through unless they are passed by the user

**Comment by jonahwilliams** [comment] 2021-03-15 16:14
(I mean, probably 🙃  )

**Comment by jonasfj** [comment] 2021-03-16 15:02
@yfer  can you do a minimal example reproducing the issue?

Does it also happen if you don't have a flutter dependency and just do `dart run build_runner build`?

**Comment by yfer** [comment] 2021-03-16 18:11
@jonasfj Yes. I'm working on it. For now i can tell that can't see the bug on linux/unix. But I see it on windows, trying to make minimal example.

**Comment by MatrixDev** [comment] 2021-03-19 11:26
@yfer I have same problem on MacOS

**Comment by PiN73** [comment] 2021-03-22 06:27
Here are reproduction steps:

- Create new folder named hello

- Create pubspec.yaml with contents:
```yaml
name: hello

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  json_annotation: ^4.0.0

dev_dependencies:
  build_runner: ^1.0.0
  json_serializable: ^4.0.0
```
- Create lib/example.dart with contents:
```dart
import 'package:json_annotation/json_annotation.dart';

part 'example.g.dart';

@JsonSerializable()
class Person {
  final String name;

  Person(this.name);

  factory Person.fromJson(Map<String, dynamic> json) => _$PersonFromJson(json);

  Map<String, dynamic> toJson() => _$PersonToJson(this);
}
```

- Open this folder with Android Studio

- Open pubspec.yaml file

- Click "Enable Dart support"

- Click "Pub get"

- Open terminal and type
```
flutter packages pub run build_runner build
```

Result:
```
hello % flutter packages pub run build_runner build
Failed to precompile build_runner:build_runner:
/Applications/flutter/.pub-cache/hosted/pub.dartlang.org/build_runner-1.12.2/bin/build_runner.dart:91:49: Warning: Operand of null-aware operation '??' has type 'bool' which excludes null.
    var verbose = parsedArgs.command['verbose'] as bool ?? false;
                                                ^
/Applications/flutter/.pub-cache/hosted/pub.dartlang.org/build_runner-1.12.2/bin/build_runner.dart:101:9: Warning: Operand of null-aware operation '?.' has type 'StreamSubscription<dynamic>' which excludes null.
 - 'StreamSubscription' is from 'dart:async'.
  await logListener?.cancel();
        ^
Error: Cannot run with sound null safety, because the following dependencies
don't support null safety:

 - package:build_runner_core
 - package:build_runner
 - package:build_config
 - package:build_daemon
 - package:code_builder

For solutions, see https://dart.dev/go/unsound-null-safety
/Applications/flutter/.pub-cache/hosted/pub.dartlang.org/build_runner-1.12.2/bin/build_runner.dart:91:37: Error: Operator '[]' cannot be called on 'ArgResults?' because it is potentially null.
 - 'ArgResults' is from 'package:args/src/arg_results.dart' ('../../.pub-cache/hosted/pub.dartlang.org/args-2.0.0/lib/src/arg_results.dart').
    var verbose = parsedArgs.command['verbose'] as bool ?? false;
                                    ^
pub finished with exit code 1
hello %
```

Not sure if the problem is in my setup, json_serializable or build_runner

**Comment by PiN73** [comment] 2021-03-22 06:38
Though `build_runner: '>=1.10.0 <1.11.0'` AND `flutter packages pub run --no-sound-null-safety build_runner build` seems to work, but this also downgrades json_serializable from 4.1.0 to 4.0.2

**Comment by jakemac53** [comment] 2021-03-22 15:48
> /Applications/flutter/.pub-cache/hosted/pub.dartlang.org/build_runner-1.12.2/bin/build_runner.dart

It looks like you have one of these funky pub caches that ships (or used to ship?) with flutter - can you try deleting that entire `.pub_cache` directory? Then do another pub get (or ideally upgrade) again and then a run.

**Comment by jakemac53** [comment] 2021-03-31 14:20
@yfer can you also try deleting your flutter specific pub cache? It is at `c:/flutter/.pub-cache`

**Comment by iksent** [comment] 2021-04-08 12:37
And what about this?

Running the next check following the [official guide](https://dart.dev/null-safety/migration-guide#check-dependency-status):
`dart pub outdated --mode=null-safety`

Says it's not compatible with `nullsafety` yet:
`build_runner                   ✗1.11.1    ✗1.11.5     ✗1.12.2                ✗1.12.2`

**Comment by simolus3** [comment] 2021-04-08 13:07
IMO the guide is confusing here.

You can start migrating your app once all the dependencies that you import have migrated. If you don't import `package:build_runner` somewhere (you probably don't), that package is not blocking you.

**Comment by vborbely** [comment] 2021-04-12 21:33
> @yfer can you do a minimal example reproducing the issue?
> 
> Does it also happen if you don't have a flutter dependency and just do `dart run build_runner build`?

Indeed, first I used `flutter pub run build_runner build`, instead of `dart run build_runner build`. It solved for me.

**Comment by CoderJava** [comment] 2021-04-24 05:33
I have the same issue on mac.

<details>
  <summary>flutter doctor -v</summary>
  
```
[✓] Flutter (Channel unknown, 2.0.1, on macOS 11.2.1 20D74 darwin-x64, locale en-ID)
    • Flutter version 2.0.1 at /Users/nusanet/Downloads/flutter
    • Framework revision c5a4b4029c (7 weeks ago), 2021-03-04 09:47:48 -0800
    • Engine revision 40441def69
    • Dart version 2.12.0

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/nusanet/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.53.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (2 available)
    • Redmi Note 4 (mobile) • faa168ce9804 • android-arm64  • Android 7.0 (API 24)
    • Chrome (web)          • chrome       • web-javascript • Google Chrome 90.0.4430.85

• No issues found!
```
</details>

<details>
  <summary>flutter pub run build_runner build</summary>

```
Failed to precompile build_runner:build_runner:
../../Downloads/flutter/.pub-cache/hosted/pub.dartlang.org/build_daemon-3.0.0/lib/data/build_target.g.dart:66:56: Warning: Operand of null-aware operation '!' has type 'Object' which excludes null.
 - 'Object' is from 'dart:core'.
          result.blackListPatterns.replace(serializers.deserialize(value,
                                                       ^
../../Downloads/flutter/.pub-cache/hosted/pub.dartlang.org/build_daemon-3.0.0/lib/data/build_target.g.dart:72:53: Warning: Operand of null-aware operation '!' has type 'Object' which excludes null.
 - 'Object' is from 'dart:core'.
          result.outputLocation.replace(serializers.deserialize(value,
                                                    ^
../../Downloads/flutter/.pub-cache/hosted/pub.dartlang.org/build_daemon-3.0.0/lib/data/build_target.g.dart:77:51: Warning: Operand of null-aware operation '!' has type 'Object' which excludes null.
 - 'Object' is from 'dart:core'.
          result.buildFilters.replace(serializers.deserialize(value,
                                                  ^
../../Downloads/flutter/.pub-cache/hosted/pub.dartlang.org/build_daemon-3.0.0/lib/data/build_status.g.dart:171:46: Warning: Operand of null-aware operation '!' has type 'Object' which excludes null.
 - 'Object' is from 'dart:core'.
          result.results.replace(serializers.deserialize(value,
                                             ^
../../Downloads/flutter/.pub-cache/hosted/pub.dartlang.org/build_daemon-3.0.0/lib/data/build_target.g.dart:22:21: Error: The return type of the method '_$DefaultBuildTargetSerializer.serialize' is 'Iterable<Object?>', which does not match the return type, 'Iterable<Object>', of the overridden method, 'StructuredSerializer.serialize'.
 - 'Iterable' is from 'dart:core'.
 - 'Object' is from 'dart:core'.
Change to a subtype of 'Iterable<Object>'.
  Iterable<Object?> serialize(
                    ^
../../Downloads/flutter/.pub-cache/hosted/pub.dartlang.org/built_value-8.0.0/lib/serializer.dart:346:20: Context: This is the overridden method ('serialize').
  Iterable<Object> serialize(Serializers serializers, T object,
                   ^
../../Downloads/flutter/.pub-cache/hosted/pub.dartlang.org/build_daemon-3.0.0/lib/data/build_target.g.dart:101:21: Error: The return type of the method '_$OutputLocationSerializer.serialize' is 'Iterable<Object?>', which does not match the return type, 'Iterable<Object>', of the overridden method, 'StructuredSerializer.serialize'.
 - 'Iterable' is from 'dart:core'.
 - 'Object' is from 'dart:core'.
Change to a subtype of 'Iterable<Object>'.
  Iterable<Object?> serialize(Serializers serializers, OutputLocation object,
                    ^
../../Downloads/flutter/.pub-cache/hosted/pub.dartlang.org/built_value-8.0.0/lib/serializer.dart:346:20: Context: This is the overridden method ('serialize').
  Iterable<Object> serialize(Serializers serializers, T object,
                   ^
../../Downloads/flutter/.pub-cache/hosted/pub.dartlang.org/build_daemon-3.0.0/lib/data/build_request.g.dart:19:21: Error: The return type of the method '_$BuildRequestSerializer.serialize' is 'Iterable<Object?>', which does not match the return type, 'Iterable<Object>', of the overridden method, 'StructuredSerializer.serialize'.
 - 'Iterable' is from 'dart:core'.
 - 'Object' is from 'dart:core'.
Change to a subtype of 'Iterable<Object>'.
  Iterable<Object?> serialize(Serializers serializers, BuildRequest object,
                    ^
../../Downloads/flutter/.pub-cache/hosted/pub.dartlang.org/built_value-8.0.0/lib/serializer.dart:346:20: Context: This is the overridden method ('serialize').
  Iterable<Object> serialize(Serializers serializers, T object,
                   ^
../../Downloads/flutter/.pub-cache/hosted/pub.dartlang.org/build_daemon-3.0.0/lib/data/build_status.g.dart:64:21: Error: The return type of the method '_$DefaultBuildResultSerializer.serialize' is 'Iterable<Object?>', which does not match the return type, 'Iterable<Object>', of the overridden method, 'StructuredSerializer.serialize'.
 - 'Iterable' is from 'dart:core'.
 - 'Object' is from 'dart:core'.
Change to a subtype of 'Iterable<Object>'.
  Iterable<Object?> serialize(
                    ^
../../Downloads/flutter/.pub-cache/hosted/pub.dartlang.org/built_value-8.0.0/lib/serializer.dart:346:20: Context: This is the overridden method ('serialize').
  Iterable<Object> serialize(Serializers serializers, T object,
                   ^
../../Downloads/flutter/.pub-cache/hosted/pub.dartlang.org/build_daemon-3.0.0/lib/data/build_status.g.dart:146:21: Error: The return type of the method '_$BuildResultsSerializer.serialize' is 'Iterable<Object?>', which does not match the return type, 'Iterable<Object>', of the overridden method, 'StructuredSerializer.serialize'.
 - 'Iterable' is from 'dart:core'.
 - 'Object' is from 'dart:core'.
Change to a subtype of 'Iterable<Object>'.
  Iterable<Object?> serialize(Serializers serializers, BuildResults object,
                    ^
../../Downloads/flutter/.pub-cache/hosted/pub.dartlang.org/built_value-8.0.0/lib/serializer.dart:346:20: Context: This is the overridden method ('serialize').
  Iterable<Object> serialize(Serializers serializers, T object,
                   ^
pub finished with exit code 1
```
</details>

**Comment by nank1ro** [comment] 2021-04-25 12:32
Same here:
build_runner version: `^2.0.1`
```
$ flutter pub run build_runner build
Failed to precompile build_runner:build_runner:
../../.pub-cache/hosted/pub.dartlang.org/build_daemon-3.0.0/lib/data/build_target.g.dart:66:56: Warning: Operand of null-aware operation '!' has type 'Object' which excludes null.
 - 'Object' is from 'dart:core'.
          result.blackListPatterns.replace(serializers.deserialize(value,
                                                       ^
../../.pub-cache/hosted/pub.dartlang.org/build_daemon-3.0.0/lib/data/build_target.g.dart:72:53: Warning: Operand of null-aware operation '!' has type 'Object' which excludes null.
 - 'Object' is from 'dart:core'.
          result.outputLocation.replace(serializers.deserialize(value,
                                                    ^
../../.pub-cache/hosted/pub.dartlang.org/build_daemon-3.0.0/lib/data/build_target.g.dart:77:51: Warning: Operand of null-aware operation '!' has type 'Object' which excludes null.
 - 'Object' is from 'dart:core'.
          result.buildFilters.replace(serializers.deserialize(value,
                                                  ^
../../.pub-cache/hosted/pub.dartlang.org/build_daemon-3.0.0/lib/data/build_status.g.dart:171:46: Warning: Operand of null-aware operation '!' has type 'Object' which excludes null.
 - 'Object' is from 'dart:core'.
          result.results.replace(serializers.deserialize(value,
                                             ^
../../.pub-cache/hosted/pub.dartlang.org/build_daemon-3.0.0/lib/data/build_target.g.dart:22:21: Error: The return type of the method '_$DefaultBuildTargetSerializer.serialize' is 'Iterable<Object?>', which does not match the return type, 'Iterable<Object>', of the overridden method, 'StructuredSerializer.serialize'.
 - 'Iterable' is from 'dart:core'.
 - 'Object' is from 'dart:core'.
Change to a subtype of 'Iterable<Object>'.
  Iterable<Object?> serialize(
                    ^
../../.pub-cache/hosted/pub.dartlang.org/built_value-8.0.0/lib/serializer.dart:346:20: Context: This is the overridden method ('serialize').
  Iterable<Object> serialize(Serializers serializers, T object,
                   ^
../../.pub-cache/hosted/pub.dartlang.org/build_daemon-3.0.0/lib/data/build_target.g.dart:101:21: Error: The return type of the method '_$OutputLocationSerializer.serialize' is 'Iterable<Object?>', which does not match the return type, 'Iterable<Object>', of the overridden method, 'StructuredSerializer.serialize'.
 - 'Iterable' is from 'dart:core'.
 - 'Object' is from 'dart:core'.
Change to a subtype of 'Iterable<Object>'.
  Iterable<Object?> serialize(Serializers serializers, OutputLocation object,
                    ^
../../.pub-cache/hosted/pub.dartlang.org/built_value-8.0.0/lib/serializer.dart:346:20: Context: This is the overridden method ('serialize').
  Iterable<Object> serialize(Serializers serializers, T object,
                   ^
../../.pub-cache/hosted/pub.dartlang.org/build_daemon-3.0.0/lib/data/build_request.g.dart:19:21: Error: The return type of the method '_$BuildRequestSerializer.serialize' is 'Iterable<Object?>', which does not match the return type, 'Iterable<Object>', of the overridden method, 'StructuredSerializer.serialize'.
 - 'Iterable' is from 'dart:core'.
 - 'Object' is from 'dart:core'.
Change to a subtype of 'Iterable<Object>'.
  Iterable<Object?> serialize(Serializers serializers, BuildRequest object,
                    ^
../../.pub-cache/hosted/pub.dartlang.org/built_value-8.0.0/lib/serializer.dart:346:20: Context: This is the overridden method ('serialize').
  Iterable<Object> serialize(Serializers serializers, T object,
                   ^
../../.pub-cache/hosted/pub.dartlang.org/build_daemon-3.0.0/lib/data/build_status.g.dart:64:21: Error: The return type of the method '_$DefaultBuildResultSerializer.serialize' is 'Iterable<Object?>', which does not match the return type, 'Iterable<Object>', of the overridden method, 'StructuredSerializer.serialize'.
 - 'Iterable' is from 'dart:core'.
 - 'Object' is from 'dart:core'.
Change to a subtype of 'Iterable<Object>'.
  Iterable<Object?> serialize(
                    ^
../../.pub-cache/hosted/pub.dartlang.org/built_value-8.0.0/lib/serializer.dart:346:20: Context: This is the overridden method ('serialize').
  Iterable<Object> serialize(Serializers serializers, T object,
                   ^
../../.pub-cache/hosted/pub.dartlang.org/build_daemon-3.0.0/lib/data/build_status.g.dart:146:21: Error: The return type of the method '_$BuildResultsSerializer.serialize' is 'Iterable<Object?>', which does not match the return type, 'Iterable<Object>', of the overridden method, 'StructuredSerializer.serialize'.
 - 'Iterable' is from 'dart:core'.
 - 'Object' is from 'dart:core'.
Change to a subtype of 'Iterable<Object>'.
  Iterable<Object?> serialize(Serializers serializers, BuildResults object,
                    ^
../../.pub-cache/hosted/pub.dartlang.org/built_value-8.0.0/lib/serializer.dart:346:20: Context: This is the overridden method ('serialize').
  Iterable<Object> serialize(Serializers serializers, T object,
                   ^
pub finished with exit code 1
```

**Comment by chinitadelrey** [comment] 2021-04-25 16:45
> For now I fixed downgrading `build_runner` to `^1.12.2`

I can confirm this fix works on MacOS for some of the following dependencies: 

  json_annotation: ^4.0.1 
  chopper: ^4.0.0-nullsafety.1

dev_dependencies:
  chopper_generator: <4.0.0-nullsafety.1
  json_serializable: ^4.1.1
  flutter_launcher_icons: ^0.9.0
  logging: ^1.0.1 

environment:
  sdk: ">=2.9.0 <3.0.0"

The current Dart SDK version is 2.13.0-211.6.beta.

Had a lot of issues with version solving so I hope this helps someone.

**Comment by jakemac53** [comment] 2021-04-26 15:33
@CoderJava @nank1ro do you have dependency overrides in your pubspec?

**Comment by nank1ro** [comment] 2021-04-26 15:35
> @CoderJava @nank1ro do you have dependency overrides in your pubspec?

No I don't

**Comment by CoderJava** [comment] 2021-04-26 16:41
> @CoderJava @nank1ro do you have dependency overrides in your pubspec?

No.

**Comment by jakemac53** [comment] 2021-04-26 18:28
It looks like the method signature for `StructuredSerializer.serialize` changed between version [8.0.0](https://github.com/google/built_value.dart/blob/v8.0.0/built_value/lib/serializer.dart#L346) and [8.0.1](https://github.com/google/built_value.dart/blob/v8.0.1/built_value/lib/serializer.dart#L346).

This makes the latest `built_value_generator` not compatible with `built_value` 8.0.0 [as it claims](https://github.com/google/built_value.dart/blob/v8.0.0/built_value_generator/pubspec.yaml#L16) it is. Cc @davidmorgan.

@CoderJava @nank1ro can you update to built_value 8.0.1 or greater?

**Comment by CoderJava** [comment] 2021-04-28 01:29
> It looks like the method signature for `StructuredSerializer.serialize` changed between version [8.0.0](https://github.com/google/built_value.dart/blob/v8.0.0/built_value/lib/serializer.dart#L346) and [8.0.1](https://github.com/google/built_value.dart/blob/v8.0.1/built_value/lib/serializer.dart#L346).
> 
> This makes the latest `built_value_generator` not compatible with `built_value` 8.0.0 [as it claims](https://github.com/google/built_value.dart/blob/v8.0.0/built_value_generator/pubspec.yaml#L16) it is. Cc @davidmorgan.
> 
> @CoderJava @nank1ro can you update to built_value 8.0.1 or greater?

It's working. Thanks.

**Comment by jakemac53** [comment] 2021-04-29 19:15
I got a bit confused but i realize the original issue here is not necessarily resolved, @yfer are you still experiencing this problem?

**Comment by davidmorgan** [comment] 2021-05-01 20:22
Yes, sorry about that; some of the null safety changes in `8.0.0` turned out to not be workable, `8.0.1` was an incompatible fix. I thought `8.0.0` was effectively hidden to Flutter due to the analyzer dependency being incompatible, that's why I didn't do another major release.

**Comment by natebosch** [comment] 2021-05-06 20:28
Another report of this happening: https://github.com/dart-lang/mockito/issues/402#issuecomment-832742028

**Comment by natebosch** [comment] 2021-05-06 20:31
@jonasfj - I'm assigning to you for now since I think the bulk of the investigation required is in pub or the dart integration with pub.

For anyone experiencing this issue, you may be able to work around it by upgrading to `build_runner` version 2 which is migrated to null safety.

**Comment by yfer** [comment] 2021-05-08 10:28
Well, i've finally solved my initial issue.

you can easily reproduce it with running on windows:

1. (Take a project with freezed dependency any @freezed class (maybe this is unnecessary, not checked)
2. make sure .dart-tool is deleted
2. run c:\flutter\bin\flutter.bat pub get
3. run C:\flutter\bin\flutter.bat pub run build_runner build --delete-conflicting-outputs

**Letter-case of 'C' disk is different!** Issue will reproduce when the cases are different. _I personally had lower-case in my windows PATH, and Android Studio had it running upper-case._

After (2) you will have .dart_tool\package_config_subset containing something like that
```
2.12
yourprojectname
file:///C:/projects/yourprojectname/           //if you lowercase this disk names everything run fine
file:///C:/projects/yourprojectname/lib/       //if you lowercase this disk names everything run fine
_fe_analyzer_shared
2.12
file:///c:/flutter/.pub-cache/hosted/pub.dartlang.org/_fe_analyzer_shared-17.0.0/
file:///c:/flutter/.pub-cache/hosted/pub.dartlang.org/_fe_analyzer_shared-17.0.0/lib/

```
After (3) you will have the exception. 

if you flip letter cases on (2), then behavior on step 2 is different, but the exception on 3 is the same.

it seems that inconsistencies of disk names letter-cases causes the observed exception. For windows it is no different. But somewhere internally in build tool it causes problems. 

It can be fixed with changing /flutter/bin/flutter.bat to make letter-case of disk the same every time tool called. But I think it is breaking-change. I know it is possible on windows to have folder and filenames case-sensitive, but can't find info on if it possible with the disk name itself, so not sure if it safe to do.


@sibylantoninobajeli this can help you, as I see you are on windows. As for other guys - not sure why you see this. Maybe this is some general problem that somehow narrows down to this.

**Comment by marianhlavac** [comment] 2021-05-15 14:06
This issue still persists, cannot build the project with latest flutter version, now the only solution seems to downgrade the flutter to <2.0... 🙄 

<details>
<summary><code>flutter doctor -v</code></summary>

```
❯ flutter doctor -v
[✓] Flutter (Channel stable, 2.0.6, on Mac OS X 10.15.7 19H114 darwin-x64, locale en-GB)
    • Flutter version 2.0.6 at /usr/local/Caskroom/flutter/1.22.5/flutter
    • Framework revision 1d9032c7e1 (2 weeks ago), 2021-04-29 17:37:58 -0700
    • Engine revision 05e680e202
    • Dart version 2.12.3

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at ###
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    • CocoaPods version 1.10.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.56.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.22.0

[✓] Connected device (2 available)
    • ###
    • Chrome (web)     • chrome   • web-javascript • Google Chrome 90.0.4430.212
    ! ###

• No issues found!
```
</details>

<details>
<summary><code>flutter pub run --no-sound-null-safety build_runner build</code></summary>

```
❯ flutter pub run --no-sound-null-safety build_runner build
[INFO] Generating build script...
[INFO] Generating build script completed, took 671ms

[INFO] Creating build script snapshot......
[INFO] Creating build script snapshot... completed, took 25.0s

[SEVERE] Failed to snapshot build script .dart_tool/build/entrypoint/build.dart.
This is likely caused by a misconfigured builder definition.
[SEVERE] .dart_tool/build/entrypoint/build.dart:27:3: Warning: Operand of null-aware operation '?.' has type 'SendPort' which excludes null. - 'SendPort' is from 'dart:isolate'.  sendPort?.send(result);  ^Error: Cannot run with sound null safety, because the following dependenciesdon't support null safety: - package:build_runner_core - package:json_serializable - package:mockito - package:source_gen - package:build_config - package:build_runner - package:build - package:json_annotation - package:analyzer - package:code_builder - package:dart_style - package:glob - package:crypto - package:logging - package:watcher - package:build_resolvers - package:timing - package:graphs - package:package_config - package:yaml - package:pub_semver - package:checked_yaml - package:pubspec_parse - package:build_daemon - package:args - package:io - package:convert - package:_fe_analyzer_shared - package:built_value - package:built_collection - package:http_multi_server - package:shelf - package:quiver - package:stream_transform - package:http_parser - package:mime - package:shelf_web_socket - package:web_socket_channel - package:cli_util - package:fixnumFor solutions, see https://dart.dev/go/unsound-null-safety.dart_tool/build/entrypoint/build.dart:25:44: Error: The parameter 'sendPort' can't have a value of 'null' because of its type 'SendPort', but the implicit default value is 'null'. - 'SendPort' is from 'dart:isolate'.Try adding either an explicit non-'null' default value or the 'required' modifier.void main(List<String> args, [_i6.SendPort sendPort]) async {                                           ^^^^^^^^
pub finished with exit code 78
```
</details>

**Comment by simolus3** [comment] 2021-05-15 14:37
@marianhlavac Is there any reason for not using the latest `build_runner`? The current version is 2.0.3. If you can't use that, can you try at least using `^1.10.4` as a lower bound?

**Comment by marianhlavac** [comment] 2021-05-15 15:56
@simolus3 Because then it gives different error saying `Generator cannot target libraries that have not been migrated to null-safety.`. My sdk constraints are set to `sdk: '>=2.11.0 <3.0.0'`, and I'm running build_runner with `--no-sound-null-safety` option.

**Comment by simolus3** [comment] 2021-05-15 16:22
> `Generator cannot target libraries that have not been migrated to null-safety.`

Ah I see, in that case it looks like you'll have to use `build_runner` 1.x for now. But I still think that you're seeing a different error than OP here. `build_runner` starts running, but then fails to snapshot the build script.

If you take a look at the `.dart_tool/build/entrypoint/build.dart` file in your project, do you see a `// @dart=2.9` comment somewhere? If not, the problem is likely that you're using a version earlier than `^1.14.4`, I would try upgrading to the latest `1.x` version just in case.

**Comment by marianhlavac** [comment] 2021-05-15 16:24
After long and painful troubleshooting I figured out it was caused by incompatible version of `json_annotation`. Setting the conflicting versions to `any`, in pubspec.yaml, and then locking then to resolved versions from lockfile did the trick and it builds now.

@simolus3 Thanks for your help.

**Comment by jakemac53** [comment] 2021-05-17 14:30
@marianhlavac

Note that the `Generator cannot target libraries that have not been migrated to null-safety` should be coming from a specific builder and not build_runner. The log line should indicate which builder is logging that message. You can likely downgrade that builder to the previous version if you need it to run on opted out code.

**Comment by jakemac53** [comment] 2021-05-17 14:31
I am going to close this issue as it looks like the original problem is resolved now (or a workaround was found).

**Closed by jakemac53** 2021-05-17 14:31 UTC

**Comment by craiglabenz** [comment] 2021-05-28 17:49
I continued to have this issue until I specified `built_value: ^8.0.6` in my pubspec.yaml file. Transitive dependencies had left it at 8.0.0 in my lock file.

**Comment by searchy2** [comment] 2021-06-04 19:39
@craiglabenz your solution worked for me, thank you! 
Unfortunately, when I try to regenerate the json_serializable files, it now throws this error:
`Generator cannot target libraries that have not been migrated to null-safety.`

This is really bad and not a good dev experience.

**Comment by Amr1440** [comment] 2021-06-23 13:35
Same issue as @searchy2 :((

**Comment by simolus3** [comment] 2021-06-23 14:06
@searchy2 and @Amr1440, that message is coming from the `json_serializable` package and is not directly related to  `build_runner`.
Try using version 3.x of `json_serializable` or migrating your project to null-safety.
