### ISSUE TITLE
No published analyzer available for language version 2.12.0 AND "requires the 'non-nullable' language feature"

### ISSUE THREAD

**Issue by emme1444** [dart-lang/build#3049] opened 2021-03-14 22:53 UTC
Every now and then I get this message upon executing `flutter packages pub run build_runner build --delete-conflicting-outputs --verbose`.

```
Your current `analyzer` version may not fully support your current SDK version.

Please try upgrading to the latest `analyzer` by running `flutter packages upgrade`.

Analyzer language version: 2.10.0
SDK language version: 2.12.0

If you are getting this message and have the latest analyzer please file
an issue at https://github.com/dart-lang/sdk/issues/new with the title
"No published analyzer available for language version 2.12.0".
Please search the issue tracker first and thumbs up and/or subscribe to
existing issues if present to avoid duplicates.
```

As the message indicates; it thinks I might not have the latest `analyzer` version installed. According to `flutter packages pub deps` I have `0.39.17`, so not the latest. 

Upon running the suggested command (`flutter packages upgrade`), the version of `analyzer` does not change (still `0.39.17`) but the message, however, disappears sometimes and sometimes not. What is happening? What is the message trying to say? What would normally cause this message to be displayed? 

The message comes along with one or more messages that go something like this:

```
[INFO] build_resolvers:Generating SDK summary...
[SEVERE] mypackage_generator:some_builder on lib/main.dart:

Bad state: Unexpected diagnostics:
C:\Users\user\flutter\bin\cache\pkg\sky_engine\lib\ui\channel_buffers.dart:166:25 - This requires the 'non-nullable' language feature to be enabled.
C:\Users\user\flutter\bin\cache\pkg\sky_engine\lib\ui\channel_buffers.dart:539:15 - This requires the 'non-nullable' language feature to be enabled.
C:\Users\user\flutter\bin\cache\pkg\sky_engine\lib\ui\channel_buffers.dart:390:19 - This requires the 'non-nullable' language feature to be enabled.
C:\Users\user\flutter\bin\cache\pkg\sky_engine\lib\ui\channel_buffers.dart:30:49 - This requires the 'non-nullable' language feature to be enabled.
C:\Users\user\flutter\bin\cache\pkg\sky_engine\lib\ui\channel_buffers.dart:18:62 - This requires the 'non-nullable' language feature to be enabled.
C:\Users\user\flutter\bin\cache\pkg\sky_engine\lib\ui\channel_buffers.dart:42:22 - This requires the 'non-nullable' language feature to be enabled.
C:\Users\user\flutter\bin\cache\pkg\sky_engine\lib\ui\channel_buffers.dart:327:34 - This requires the 'non-nullable' language feature to be enabled.
C:\Users\user\flutter\bin\cache\pkg\sky_engine\lib\ui\channel_buffers.dart:376:19 - This requires the 'non-nullable' language feature to be enabled.
C:\Users\user\flutter\bin\cache\pkg\sky_engine\lib\ui\channel_buffers.dart:516:13 - This requires the 'non-nullable' language feature to be enabled.
C:\Users\user\flutter\bin\cache\pkg\sky_engine\lib\ui\channel_buffers.dart:224:29 - This requires the 'non-nullable' language feature to be enabled.
C:\Users\user\flutter\bin\cache\pkg\sky_engine\lib\ui\channel_buffers.dart:65:23 - This requires the 'non-nullable' language feature to be enabled.
C:\Users\user\flutter\bin\cache\pkg\sky_engine\lib\ui\channel_buffers.dart:58:17 - This requires the 'non-nullable' language feature to be enabled.
C:\Users\user\flutter\bin\cache\pkg\sky_engine\lib\ui\channel_buffers.dart:41:23 - This requires the 'non-nullable' language feature to be enabled.
C:\Users\user\flutter\bin\cache\pkg\sky_engine\lib\ui\channel_buffers.dart:132:29 - This requires the 'non-nullable' language feature to be enabled.
package:analyzer/dart/sdk/build_sdk_summary.dart 179:7   _Builder._parse
package:analyzer/dart/sdk/build_sdk_summary.dart 142:36  _Builder._addLibrary
dart:core                                                List.forEach
package:analyzer/dart/sdk/build_sdk_summary.dart 96:20   _Builder.build
package:analyzer/dart/sdk/build_sdk_summary.dart 70:5    buildSdkSummary
package:build_resolvers/src/resolver.dart 290:36         _defaultSdkSummaryGenerator
package:build_resolvers/src/resolver.dart 225:11         AnalyzerResolvers._ensureInitialized.<fn>
package:build_resolvers/src/resolver.dart 232:5          AnalyzerResolvers.get
package:build                                            _DelayedResolver.isLibrary
package:source_gen/src/builder.dart 69:10                _Builder.build
```

I didn't previously have any problems, but I think adding a package might have started it. The package is `merging_builder`. Anybody willing to help me figure out why?

I replaced the code using `merging_builder` for this output. As you can see the errors above seem to originate from `source_gen`, which is what is used for the above output. Before the replace the same thing was output except a somewhat longer stacktrace and obviously the lower lines mentioning `package:merging_builder`.

Help in resolving this issue would be greatly appreciated. I'm posting this here because of the message at the top suggesting it.

Thanks!

---

* Dart SDK Version (`dart --version`): 
  `Dart SDK version: 2.12.0-133.2.beta (beta) (Tue Dec 15 09:55:09 2020 +0100) on "windows_x64"`
* What package(s) from this repo you are using, and the version (i.e. `build_runner 0.7.12`): 
  `build_runner 1.10.2`
* What builder(s) you are using (or writing yourself). Try to give a short summary of what they do: 
  `merging_builder`'s `MergingBuilder`, according to the documentation, enables builder aggregation of multiple files to one single file. I don't know if it's of any help here but; my builder just builds on the `MergingBuilder`. If you wanna know more feel free to ask.
* Whether you are using Windows, MacOSX, or Linux (if applicable): 
  `Windows 10`
* Any other packages or constraints we should know about: 
  `merging_builder`

**Comment by jakemac53** [comment] 2021-03-15 16:17
Most likely the `merging_builder` package is restricting your analyzer version so you can't get the latest.

Since you are on an old analyzer, it doesn't understand that null safety no longer requires an experiment, and you get those errors.

You can use the [pubviz](https://pub.dev/packages/pubviz) tool to try and see if there are additional things blocking you from getting the latest analyzer as well.

**Comment by jakemac53** [comment] 2021-03-15 16:18
I am going to close this as the issue is definitely just an old analyzer, but we can still help you resolve the issue if you are having troubles.

**Closed by jakemac53** 2021-03-15 16:18 UTC

**Comment by emme1444** [comment] 2021-03-16 10:18
Thanks, @jakemac53 for the quick response!

Yeah okay, sounds like something I was suspecting anyway.



I removed the `merging_builder` package as a dependency for the generator I'm building. However, the `analyzer` version does not change. So, I used `pubviz` like you suggested. I ran `dart pub global run pubviz open -p` and I got this:

![screenshot](https://user-images.githubusercontent.com/23585909/111291874-ea802a00-8647-11eb-9d9a-3c84127888b4.png)

To me, it looks like `build` is the one constraining the version to below `0.40.0`. That would explain a version of `0.39.17`, but see I don't understand why it would constrain it. My `pubspec.yaml` looks like this:

```
...
environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  build:
  source_gen:

  # merging_builder:
  directed_graph:
  exception_templates:

  themeable:
    path: ../themeable

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4

  build_test:
  build_runner:
...
```

Wouldn't that get all the latest versions. Or is it because of my Dart SDK constraints? 

I'm kind of stuck here! Thanks for your help!

_PS: I'm aware that the `pubspec.yaml` above is not really ideal for a production release, but I'm just in a test phase so far._

**Comment by jakemac53** [comment] 2021-03-16 14:49
Just to double check @emme1444, you have been running `pub upgrade` to upgrade your deps? I don't see anything there restricting the `build` version directly, but you are definitely getting a very old version (almost a year old).

It might be that `pub` is not dealing well with all of the `any` constraints you have and is selecting a very old version of packages? I would try forcing `build: ^1.6.3` and see what happens.

**Comment by emme1444** [comment] 2021-03-16 21:22
Hey @jakemac53!

> Just to double check @emme1444, you have been running pub upgrade to upgrade your deps?

Well, kind of I guess. I ran it on the `example` flutter side, but for some reason never thought to run it in my `generator` package. 

Anyway, playing around with the things you've suggested, this is what I've found out. Although I am still stuck. I think.

Without merging builder (same `pubspec.yaml` as before), followed by a `pub get` and then a `pub upgrade`, I get this:

![screenshot1](https://user-images.githubusercontent.com/23585909/111379210-25637b80-86a3-11eb-9b08-4da8be854d9b.png)

Which looks exactly like I want it to (kind of). So `source_gen` and `build` both restrict `analyzer` correctly here. However, if I add `merging_builder` back in, followed by a `pub get` and then a `pub upgrade`, I get this:

![screenshot2](https://user-images.githubusercontent.com/23585909/111379692-b4709380-86a3-11eb-9931-838835eb0cbc.png)

Which does not look good. Looking at the `merging_builder`'s `pubspec.yaml` I'm guessing that this is what constrains `analyzer`'s version: 

[`merging_builder/pubspec.yaml`](https://github.com/simphotonics/merging_builder/blob/main/pubspec.yaml)
```yaml
name: merging_builder
...
environment:
  sdk: '>=2.8.1 <3.0.0'

dependencies:
  analyzer: ^0.39.15
  build: ^1.3.0
  dart_style: ^1.3.6
  directed_graph: ^0.1.7
  exception_templates: ^0.0.6
  glob: ^1.2.0
  meta: ^1.2.2
  path: ^1.7.0
  source_gen: ^0.9.6
  lazy_evaluation: ^0.0.6+3
...
```

However, it's still not clear to me at all why `build` wouldn't get the latest version. Unless the very thing above is the reason causing `build` not to _fully_ satisfy its constraints (in this case `^1.3.0` in `merging_builder`). That's about the only logical explanation I can find for this. 

Do you think I'm on the right track? Or do you have any other thoughts that could help me? And also, how would you suggest going forward? I might just make a clone of `merging_builder` and play arround with its dependencies. Then override it in my project. I'll get back to you on that as soon as possible!

Thanks! And sorry for maybe wasting your time.

**Comment by jakemac53** [comment] 2021-03-17 15:42
@emme1444 yes so `merging_builder` requires analyzer ` ^0.39.15` which doesn't allow any of the newer versions (anything above `0.39.x`). I would start by filing an issue on that builder, asking them to update. If they don't respond, then you probably want to re-evaluate using that builder is the sort of harsh reality.  You could either fork your own version or find something else that does what you want.

**Comment by emme1444** [comment] 2021-03-19 10:59
@jakemac53 yes as I suspected. I did open an issue at `merging_builder` they're soon in the process of migrating to support null-safety which should resolve the dependency mismatched I've experienced. 

Thanks for all the help and time anyway. Have a nice weekend!
