### ISSUE TITLE
Failed to precompile build_runner:graph_inspector and  build_runner:build_runner

### ISSUE THREAD

**Issue by StrawberryChocolateFudge** [dart-lang/build#2567] opened 2019-12-08 12:00 UTC
Dart VM version: 2.6.1 (Mon Nov 11 13:12:24 2019 +0100) on "linux_x64"

 dev_dependencies:
  build_runner: ^1.7.2

I just created a brand new project with stagehand. Removed all the other dependencies so build_runner is the only dependency  
here is the output:

Precompiling executables...
Failed to precompile build_runner:graph_inspector:
Error: Could not resolve the package 'kernel' in 'package:kernel/util/graph.dart'.
../../../.pub-cache/hosted/pub.dartlang.org/analyzer-0.39.2/lib/src/summary2/default_types_builder.dart:15:8: Error: Not found: 'package:kernel/util/graph.dart'
import 'package:kernel/util/graph.dart' show Graph, computeStrongComponents;
       ^
../../../.pub-cache/hosted/pub.dartlang.org/analyzer-0.39.2/lib/src/summary2/default_types_builder.dart:256:39: Error: Type 'Graph' not found.
class _TypeParametersGraph implements Graph<int> {
                                      ^^^^^
../../../.pub-cache/hosted/pub.dartlang.org/analyzer-0.39.2/lib/src/summary2/default_types_builder.dart:256:39: Error: Expected 0 type arguments.
class _TypeParametersGraph implements Graph<int> {
                                      ^
../../../.pub-cache/hosted/pub.dartlang.org/analyzer-0.39.2/lib/src/summary2/default_types_builder.dart:125:29: Error: The method 'computeStrongComponents' isn't defined for the class 'DefaultTypesBuilder'.
 - 'DefaultTypesBuilder' is from 'package:analyzer/src/summary2/default_types_builder.dart' ('../../../.pub-cache/hosted/pub.dartlang.org/analyzer-0.39.2/lib/src/summary2/default_types_builder.dart').
Try correcting the name to the name of an existing method, or defining a method named 'computeStrongComponents'.
    var stronglyConnected = computeStrongComponents(graph);
                            ^^^^^^^^^^^^^^^^^^^^^^^
Failed to precompile build_runner:build_runner:
Error: Could not resolve the package 'kernel' in 'package:kernel/util/graph.dart'.
../../../.pub-cache/hosted/pub.dartlang.org/analyzer-0.39.2/lib/src/summary2/default_types_builder.dart:15:8: Error: Not found: 'package:kernel/util/graph.dart'
import 'package:kernel/util/graph.dart' show Graph, computeStrongComponents;
       ^
../../../.pub-cache/hosted/pub.dartlang.org/analyzer-0.39.2/lib/src/summary2/default_types_builder.dart:256:39: Error: Type 'Graph' not found.
class _TypeParametersGraph implements Graph<int> {
                                      ^^^^^
../../../.pub-cache/hosted/pub.dartlang.org/analyzer-0.39.2/lib/src/summary2/default_types_builder.dart:256:39: Error: Expected 0 type arguments.
class _TypeParametersGraph implements Graph<int> {
                                      ^
../../../.pub-cache/hosted/pub.dartlang.org/analyzer-0.39.2/lib/src/summary2/default_types_builder.dart:125:29: Error: The method 'computeStrongComponents' isn't defined for the class 'DefaultTypesBuilder'.
 - 'DefaultTypesBuilder' is from 'package:analyzer/src/summary2/default_types_builder.dart' ('../../../.pub-cache/hosted/pub.dartlang.org/analyzer-0.39.2/lib/src/summary2/default_types_builder.dart').
Try correcting the name to the name of an existing method, or defining a method named 'computeStrongComponents'.
    var stronglyConnected = computeStrongComponents(graph);
                            ^^^^^^^^^^^^^^^^^^^^^^^
exit code 0

**Comment by StrawberryChocolateFudge** [comment] 2019-12-08 12:18
I can reproduce this error every time I create a new stagehand project. BUT it goes away if I use an older version of build_runner and upgrade the older version to a newer. After further testing I can say the error is not present when using   build_runner: 1.7.0  and after successfully precompiling 1.7.0 I can also precompile 1.7.1 and 1.7.2.

**Comment by jakemac53** [comment] 2019-12-08 19:04
Duplicate of https://github.com/dart-lang/build/issues/2565

**Closed by jakemac53** 2019-12-08 19:04 UTC
