### ISSUE TITLE
Daemon doesn't terminate after last client is killed

### ISSUE THREAD

**Issue by DanTup** [dart-lang/build#2368] opened 2019-07-22 17:10 UTC
There was some discussion about this at https://github.com/flutter/devtools/pull/802#issuecomment-513707181. In DevTools tests on Windows the devtools daemon seems to hang around after we kill the `serve` process. It can be reproduced by running:

```
$ENV:WEBDEV_RELEASE="true"
pub run --enable-asserts test -j1 --reporter expanded --exclude-tags useFlutterSdk .\test\integration_tests\integration_test.dart --plain-name="lists scripts"
```

From the `packages/devtools` folder.

It might be related to use calling`.kill()` which sends SIGTERM, but the code might only handle SIGINT:

see https://github.com/dart-lang/build/blob/9c37817df024e86052d78e3c886c1d12ed5b9e63/build_daemon/lib/daemon.dart#L114-L122

I'm not sure though - I can't repro it on macOS.

@grouma

**Comment by grouma** [comment] 2019-07-22 17:41
I thought you were sending a `SIGTERM` to `webdev` not the underlying `build_daemon` process? That should cause the `build_daemon` to lose a connection to the client and therefore exit:
https://github.com/dart-lang/build/blob/9c37817df024e86052d78e3c886c1d12ed5b9e63/build_daemon/lib/src/server.dart#L155

Regardless, I don't believe you need to explicitly handle `ProcessSignal.sigterm`. My understanding (which could be wrong and I should verify) is that if you don't add a listener for a given process signal the default behavior will apply.

**Comment by DanTup** [comment] 2019-07-22 17:59
> I thought you were sending a `SIGTERM` to `webdev` not the underlying `build_daemon` process?

You are correct. I wasn't sure how this stuff all hung together, so that might've been a red herring 😄

**Comment by DanTup** [comment] 2019-07-23 08:16
@grouma I can repro with this script. Doesn't matter if I just call `kill()` or `kill(sigint)`, there are always two Dart processes left after the script terminates.

```dart
import 'dart:async';
import 'dart:convert';
import 'dart:io';

Future<void> main() async {
  final proc = await Process.start(
      'pub.bat', ['global', 'run', 'webdev', 'serve', 'web', '--release']);

  await proc.stdout.map(utf8.decode).map((s) {
    print(s.trim());
    return s;
  }).firstWhere((s) => s.contains('Succeeded after'));
  await Future.delayed(const Duration(seconds: 5));

  // Both of these result in the daemon process leaking
  proc.kill();
  //proc.kill(ProcessSignal.sigint);
}
```

**Comment by grouma** [comment] 2019-07-23 17:12
I investigated this today. The issue you are seeing is that you are killing just the underlying `pub` process, not the `webdev` process. As soon as you kill the `webdev` process the build_daemon process immediately exits. You can see this by running `webdev serve` directly in `cmd` and hitting `ctrl + c`.

I'm going to close this as a duplicate of https://github.com/dart-lang/pub/issues/2042

**Closed by grouma** 2019-07-23 17:12 UTC

**Comment by DanTup** [comment] 2019-07-23 17:17
Ah yes, of course. Dart-Code has been bitten by this before... we now collect PIDs of processes we spawn (Flutter, VM service, pkg:test, etc. all advertise their PID in the startup events) and when we terminate, we kill those PIDs as well as the shell process we have a reference to.

It's not so simple here though, since our tests are just calling `webdev serve` and there isn't really a machine protocol we could use for it to tell us the PID 😞

**Comment by grouma** [comment] 2019-07-23 17:20
I was curious why we don't have this issue in `package:webdev`. Looks like we call the binary directly: https://github.com/dart-lang/webdev/blob/master/webdev/test/test_utils.dart#L15

**Comment by DanTup** [comment] 2019-07-23 17:34
Yeah, that would prevent it. It's easier there because it's a local script, but for devtools we'd need to reach into the pubcache directly.

I fixed DevTools by making the options line up properly (my original issue was not passing `--no-release` to disable release mode for `build` because it was release by default) so it's not an issue there now.
