### ISSUE TITLE
build_web_compilers not within constraints

### ISSUE THREAD

**Issue by johnniwinther** [dart-lang/build#2808] opened 2020-09-09 21:17 UTC
Trying to run my `web/index.html` from within IntelliJ I get the following error:
```
dart-sdk\bin\pub.bat global run webdev daemon web:53322 --launch-app=web/index.html
webdev could not run for this project.
The `build_web_compilers` version – 2.11.0 – is not within the allowed constraint – >=2.12.0-dev.1 <3.0.0.
```
It worked yesterday and I have no clue where the `>=2.12.0-dev.1 <3.0.0` constraint comes from, it doesn't match the any constraints in my pubspec.yaml.

@jakemac53 Do you have any idea what has happened ? `2.12.0-dev.1` is still in the future, right?

**Comment by stephan-gruen** [comment] 2020-09-10 08:55
The problem is webdev 2.6.0, released on Sep 8, 2020. 

You have to manually downgrad webdev to 2.5.9 till the error is fixed.

`pub global activate webdev 2.5.9`
or 
`"D:\dart-sdk\dart-sdk 2.10.0-99.0.dev\bin\pub.bat" global activate webdev 2.5.9`

worked for me.

**Comment by jakemac53** [comment] 2020-09-10 14:06
cc @grouma @annagrin not sure what we want to do here - this version of webdev should have probably been released as a pre-release itself to avoid this type of issue :/

**Comment by jakemac53** [comment] 2020-09-10 14:07
Probably the easiest fix would be to release a stable version of build_web_compilers?

**Comment by jakemac53** [comment] 2020-09-10 14:11
Going to close this as a dupe of https://github.com/dart-lang/webdev/issues/1099

**Closed by jakemac53** 2020-09-10 14:11 UTC

**Comment by vakenbolt** [comment] 2021-11-02 04:13
Hello all 👋 

Run the following command to activate `webdev`
```bash
pub global activate webdev
```

If you are still seeing the error then the pub cache is more than likely interfering with you updating to the latest `webdev`. To fix, simply remove your pub cache, like so:

```bash
rm -rf ~/.pub-cache/
```

and re-run `pub upgrade` and `pub global activate webdev`

Cheers!
