### ISSUE TITLE
[build_runner] throws InvalidType is not a class element after update

### ISSUE THREAD

**Issue by migalv** [dart-lang/build#3564] opened 2023-08-23 10:59 UTC
After updating Flutter to v3.13.0 & Dart v3.1.0 (stable channel as of 23 Aug 2023)

My code generation has broken.

It was working perfectly fine for versions v3.10.6 & Dart v3.0.7.

----
* Dart SDK Version 3.1.0
* `build_runner` Version 2.4.5
* I'm using `auto_route` for route generation, `injectable` for dependency registration & `freezed` data class generation
* MacOS
----

<details>
    <summary>`dart info` output:</summary>
    <br>

#### General info

- Dart 3.1.0 (stable) (Tue Aug 15 21:33:36 2023 +0000) on "macos_arm64"
- on macos / Version 13.4.1 (Build 22F82)
- locale is en-ES

#### Project info

- sdk constraint: '>=3.0.0 <4.0.0'
- dependencies: auto_route, auto_size_text, bloc, cached_network_image, carousel_slider, connectivity_plus, cookie_jar, dio, dio_cookie_manager, dotted_border, equatable, expandable, flutter, flutter_bloc, flutter_markdown, flutter_native_splash, freezed_annotation, gap, get_it, injectable, intl, json_annotation, json_serializable, logger, markdown, non_uniform_border, shared_preferences, shimmer, signalr_netcore, timeago, webview_flutter, youtube_player_flutter
- dev_dependencies: auto_route_generator, build_runner, flutter_test, freezed, injectable_generator, lint, mockito
   <br>
</details>

I'm using Injectable to generate my factory registration.

But I'm getting InvalidType is not a class element error

It seems this is thrown when trying to register the External Module AppRouter from the auto_route package.

Here is the code for the External module. Fairly straightforward

```
@module
abstract class AppRouterModule {
  @singleton
  AppRouter get appRouter => AppRouter();
}
```

I've tried switching between different build_runner versions but nothing has worked

**Comment by jakemac53** [comment] 2023-08-23 14:18
Almost certainly you just need to update some transitive package dependency - possibly `watcher`? There were a few minor breaking changes recently that broke some of our transitive dependencies.

A `flutter pub upgrade` should resolve the issue though.

If that doesn't fix things, can you give a stack trace so we can see exactly which package is having an issue?

**Comment by migalv** [comment] 2023-08-23 15:46
@jakemac53  This is all the [SEVERE] error types I'm getting from the stack trace: 

```
[SEVERE] injectable_generator:injectable_builder on lib/infrastructure/core/injectable_modules.dart:

InvalidType is not a class element
package:injectable_generator/utils.dart 38:5                             throwIf
package:injectable_generator/resolvers/dependency_resolver.dart 63:5     DependencyResolver.resolveModuleMember
package:injectable_generator/generators/injectable_generator.dart 51:15  InjectableGenerator.generate
package:source_gen/src/builder.dart 355:23                               _generate
```

**Comment by jakemac53** [comment] 2023-08-23 15:53
It looks like this is coming from here https://github.com/Milad-Akarie/injectable/blob/master/injectable_generator/lib/resolvers/dependency_resolver.dart#L66 .

The issue is almost certainly related to a change in `package:graphs`, basically the order in which some builders get applied changed in a newer version, so the `AppRouter` class isn't generated yet when your `injectable_generator` builder is running.

See https://github.com/dart-lang/build/issues/3509 for the original issue and [this comment](https://github.com/dart-lang/build/issues/3509#issuecomment-1549730451) for a fix using global configuration to specify the ordering manually so that injectable will run _after_ app_router.

**Comment by jakemac53** [comment] 2023-08-23 15:54
I am going to close this as it is a known issue but feel free to respond if you need additional help with setting up the proper configuration.

**Closed by jakemac53** 2023-08-23 15:54 UTC
Labels: needs-info

**Comment by migalv** [comment] 2023-08-23 16:13
Thank you @jakemac53. I'll take a look at your proposal and I'll let you know if this works :)

**Comment by migalv** [comment] 2023-08-24 09:36
Hey @jakemac53. I tried what you mentioned in [this comment](https://github.com/dart-lang/build/issues/3509#issuecomment-1549730451) for my case.

But I'm getting this error: `Invalid argument(s): line 3, column 5 of build.yaml: Unrecognized keys: [injectable];`

This is my build.yaml:
```
builders:
  global_options:
    injectable:
      runs_after:
        - auto_route
```

I'm really not familiar at all with the build.yaml format, so I'm probably doing something wrong

**Comment by jakemac53** [comment] 2023-08-24 14:20
> builders:
>   global_options:
>     injectable:
>       runs_after:
>         - auto_route

The builder "key" (`injectable`) is wrong here - you have to look at the original injectable_builder generator to find their builder key if they don't document it elsewhere, which is [here](https://github.com/Milad-Akarie/injectable/blob/master/injectable_generator/build.yaml#L9C3-L9C28). Specifically note that there are actually two builders, but the one called `injectable_config_builder` is the one that actually produces dart files, and that is the one you need to configure.

You need to do the same for the auto_route_generator package, their `build.yaml` is [here](https://github.com/Milad-Akarie/auto_route_library/blob/master/auto_route_generator/build.yaml#L2) but I think their build config is messed up because they don't list any `.dart` outputs for any of their builders. You can try just listing them all though:

So you will end up with something like this:

 > builders:
>   global_options:
>     injectable_generator:injectable_config_builder:
>       runs_after:
>         - auto_route_generator:auto_route_generator
>         - auto_route_generator:auto_router_module_generator
>         - auto_route_generator:auto_router_generator

**Comment by haarnorb** [comment] 2023-09-07 11:43
I just run into the same problem. Extending the build.yaml fixed it
`global_options:
  auto_route_generator:autoRouteGenerator:
    runs_before:
      - injectable_generator:injectable_builder
`
