### ISSUE TITLE
FileSystemException: Directory watcher closed unexpectedly

### ISSUE THREAD

**Issue by insinfo** [dart-lang/build#3150] opened 2021-07-21 21:08 UTC
FileSystemException: Directory watcher closed unexpectedly

* Dart SDK Version 2.12.4
* Whether you are using Windows / Linux
* Whether you are using Chrome

##### pubspec.yaml
```yaml
name: cmpop_browser
description: A web app that uses AngularDart Components

environment:
  sdk: ">=2.7.1 <3.0.0"

dependencies:
  angular: ^6.0.0
  angular_components: ^1.0.2
  angular_router: ^2.0.0
  angular_forms: ^3.0.0
  sembast_web: ^1.2.0
  angular_recaptcha: ^0.1.5
  stream_transform: #^0.0.19
  sass_builder: ^2.1.3
  intl: ^0.16.1
  uuid: ^2.2.2
  crossplat_objectid: ^2.1.4  
  http: ^0.12.2
  quiver: ^2.1.5

dev_dependencies: 
  angular_test: ^3.0.0                                                                                                 
  build_runner: ^1.10.4                                                                                                   
  build_test: ^1.3.0                                                                                              
  build_web_compilers: ^2.12.0                                                                                
  pedantic: ^1.9.2                                                                                               
  test: ^1.15.4

```

```console
webdev build
[INFO] Reading cached asset graph completed, took 722ms
[INFO] Checking for updates since last build completed, took 1.1s
[INFO] Running build completed, took 437ms
[INFO] Caching finalized dependency graph completed, took 581ms
[SEVERE]
[SEVERE]
[SEVERE] You have hit a bug in build_runner
[SEVERE] Please file an issue with reproduction steps at https://github.com/dart-lang/build/issues
[SEVERE]
[SEVERE]
[SEVERE] FileSystemException: Directory watcher closed unexpectedly, path = 'd:\mydartprojects\cmpop\cmpop_browser'
[SEVERE] dart:isolate  _RawReceivePortImpl._handleMessage
[SEVERE]
```

**Comment by jakemac53** [comment] 2021-07-22 14:17
We can't unfortunately do much about this error - if you are seeing it regularly you can try using the `--use-polling-watcher` flag, but that may consume more resources than normal watch mode.

**Comment by insinfo** [comment] 2021-07-22 15:05
@jakemac53
yes i am seeing this regurlamnete after updating webdev and running pub update
What is causing this, as this problem did not occur before

**Comment by jakemac53** [comment] 2021-07-22 15:30
We are just handling an exception from your file system so it is a bit hard to say exactly what the issue is, but you may have ran out of file handles or something like that. It is possible that rebooting your computer could fix it also... maybe some rogue process somewhere is hogging a lot of file handles.

**Comment by insinfo** [comment] 2021-07-22 15:39
Thank you very much for the feedback, I will check your suggestions

**Comment by jakemac53** [comment] 2021-07-22 15:41
Actually thinking more on this... @annagrin did we just release a webdev version that allows for higher parallelism when serving files? Maybe that is what is causing you to run out of file handles.

**Comment by jakemac53** [comment] 2021-07-22 15:42
@insinfo I think that change was specific to the mode that webdev uses for build_runner, could you try running normal standalone build_runner: `pub run build_runner serve web` and see if you still experience the issue? That might help narrow things down.

**Comment by insinfo** [comment] 2021-07-22 19:56
I tested it with "pub run build_runner serve web" and "pub run build_runner build web" and it worked perfectly.

I took the test several times.
I found that the problem is only in the "webdev build" when run at odd time, at even time the error doesn't occur.

As can be seen in the log, the error only occurs the second time.


```console
PS D:\MyDartProjects\cmpop\cmpop_browser> webdev build
[INFO] Reading cached asset graph completed, took 856ms
[INFO] Checking for updates since last build completed, took 1.2s
[INFO] Running build completed, took 457ms
[INFO] Caching finalized dependency graph completed, took 553ms
[INFO] Reading manifest at build\.build.manifest completed, took 0ms
[INFO] Deleting previous outputs in `build` completed, took 22ms
[INFO] Creating merged output dir `build` completed, took 781ms
[INFO] Succeeded after 4.3s with 0 outputs (0 actions)
PS D:\MyDartProjects\cmpop\cmpop_browser> webdev build
[INFO] Reading cached asset graph completed, took 932ms
[INFO] Checking for updates since last build completed, took 1.2s
[INFO] Running build completed, took 438ms
[INFO] Caching finalized dependency graph completed, took 533ms
[INFO] Reading manifest at build\.build.manifest completed, took 0ms
[INFO] Deleting previous outputs in `build` completed, took 205ms
[SEVERE]
[SEVERE] You have hit a bug in build_runner
[SEVERE] Please file an issue with reproduction steps at https://github.com/dart-lang/build/issues
[SEVERE]
[SEVERE]
[SEVERE] FileSystemException: Directory watcher closed unexpectedly, path = 'd:\mydartprojects\cmpop\cmpop_browser'
[SEVERE] dart:isolate  _RawReceivePortImpl._handleMessage
[SEVERE]
PS D:\MyDartProjects\cmpop\cmpop_browser> webdev build
[INFO] Reading cached asset graph completed, took 753ms
[INFO] Checking for updates since last build completed, took 1.2s
[INFO] Running build completed, took 424ms
[INFO] Caching finalized dependency graph completed, took 543ms
[INFO] Reading manifest at build\.build.manifest completed, took 0ms
[INFO] Deleting previous outputs in `build` completed, took 21ms
[INFO] Creating merged output dir `build` completed, took 725ms
[INFO] Writing asset manifest completed, took 6ms
[INFO] Succeeded after 4.2s with 0 outputs (0 actions)
PS D:\MyDartProjects\cmpop\cmpop_browser> webdev build
[INFO] Reading cached asset graph completed, took 738ms
[INFO] Checking for updates since last build completed, took 1.2s
[INFO] Running build completed, took 436ms
[INFO] Caching finalized dependency graph completed, took 555ms
[INFO] Reading manifest at build\.build.manifest completed, took 0ms
[SEVERE]
[SEVERE]
[SEVERE] You have hit a bug in build_runner
[SEVERE] Please file an issue with reproduction steps at https://github.com/dart-lang/build/issues
[SEVERE]
[SEVERE]
[SEVERE] FileSystemException: Directory watcher closed unexpectedly, path = 'd:\mydartprojects\cmpop\cmpop_browser'
[SEVERE] dart:isolate  _RawReceivePortImpl._handleMessage
[SEVERE]
```

**Comment by jakemac53** [comment] 2021-07-22 20:16
That is very odd indeed that it is happening with `webdev build`. We should not even be setting up file watchers in that case?

**Comment by jakemac53** [comment] 2021-07-22 20:18
Re-opening as that seems like a different issue, maybe `daemon` mode always sets up watchers but I wonder if we can somehow avoid this.

**Comment by insinfo** [comment] 2021-07-22 21:50
I downgraded dart 2.12 to 2.10 and ran some more tests and saw that with dart 2.10 the problem does not occur

**Comment by insinfo** [comment] 2021-07-22 22:02
in Dart 2.13.4 the problem persists

**Comment by jakemac53** [comment] 2021-07-23 14:50
> I downgraded dart 2.12 to 2.10 and ran some more tests and saw that with dart 2.10 the problem does not occur

I think that probably this is related to your version solve (you likely got a _very_ different set of packages in 2.10).

**Comment by jakemac53** [comment] 2021-07-23 14:50
@annagrin I do think this is most likely related to the recent asset server change, given the timing and description.

**Comment by annagrin** [comment] 2021-07-26 20:10
Looking!

**Comment by annagrin** [comment] 2021-07-26 21:30
> Actually thinking more on this... @annagrin did we just release a webdev version that allows for higher parallelism when serving files? Maybe that is what is causing you to run out of file handles.

We released dwds 11.1.2, but webdev from `pub global activate` and SDK 2.13.4 brings dwds version dwds 11.0.2 for me, so it does not contain my latest changes to the http clients. 

@insinfo I tried to repro the failure in `example` directory (on mac and windows) with the same dependencies listed above, with SDK 2.12 and 2.13.4, no luck. Is it possible to share your repro with us?

@jakemac53 On windows, `webdev.bat build` gives this output:
```
Can't load Kernel binary: Invalid binary format version.
[INFO] Reading cashed asset graph completed, took 318 ms
... 
[INFO Succeded after 883ms with 0 outputs (0 actions)
```

And finishes successfully. Looks like the build tries to run something built with another SDK version in a isolate - do you know what it might be?

**Comment by jakemac53** [comment] 2021-07-26 21:34
> And finishes successfully. Looks like the build tries to run something built with another SDK version in a isolate - do you know what it might be?

That is normal output from pub after updating your sdk (its a bit weird but... 🤷‍♂️ )

**Comment by jakemac53** [comment] 2021-07-26 21:35
If we aren't pulling down the latest asset server changes @annagrin then you probably don't need to investigate much further yourself (its also fairly unlikely you will be able to actually reproduce the issue).

**Comment by annagrin** [comment] 2021-07-26 23:18
@jakemac53 I don't know if it helps but I thought the watcher should restart on this failure, according to the fix for https://github.com/dart-lang/sdk/issues/38853. Not sure if something changed there...

**Comment by insinfo** [comment] 2021-07-27 15:55
@annagrin 
I put a copy without sensitive data of the project on github, to demonstrate the problem
https://github.com/insinfo/cmpop/tree/main/cmpop_browser

**Comment by annagrin** [comment] 2021-07-27 22:07
> Apparently this problem had been resolved, but it seems to have returned from dart 2.12.

it was resolved in the dart-lang/watcher, which just restarted the watcher recursively as infinitum. But I does not seem to restart here, I am not sure why. 

> the strangest thing is that on the first run it goes well, but on the second time I run "webdev build" the problem occurs

Yeah I have seen something like that in situations when the daemon from the first run was still running and the second one would connect to it, not sure if this is possible here as I am not very familiar with the implementation details. In my case the problem would disappear if I killed all suspicious dart processes in between builds.

**Comment by annagrin** [comment] 2021-07-27 22:13
Update: brushed up on `webdev build` implementation details:) I does indeed use the daemon, so I wonder if the problem is that the daemon does not exit after the build is done. @insinfo let me know if killing dart processes in between build  helps in your case.

**Comment by annagrin** [comment] 2021-07-27 22:15
forgot to anser this:

> Did you run on a clean windows virtual machine? Or on a working machine?

I run it on my windows laptop. I will try to repro now that I have your code.

**Comment by annagrin** [comment] 2021-07-28 00:30
@insinfo I can very predictably repro the issue on my windows laptop using your code. There are no dart processes left in between runs, so it looks like the issue is not due to webdev setup.

@jakemac53 I think the issue might be in the build_runner after all.

**Comment by insinfo** [comment] 2021-07-28 17:16
yes, deleting the directory every time it compiles, the error doesn't occur

```console
PS D:\MyDartProjects\cmpop\cmpop_browser> rm -r .\build\
PS D:\MyDartProjects\cmpop\cmpop_browser> webdev build
[INFO] Reading cached asset graph completed, took 728ms
[INFO] Checking for updates since last build completed, took 1.1s
[INFO] Running build completed, took 406ms
[INFO] Caching finalized dependency graph completed, took 509ms
[INFO] Creating merged output dir `build` completed, took 1.0s
[INFO] Writing asset manifest completed, took 4ms
[INFO] Succeeded after 4.3s with 0 outputs (0 actions)
PS D:\MyDartProjects\cmpop\cmpop_browser> rm -r .\build\
PS D:\MyDartProjects\cmpop\cmpop_browser> webdev build
[INFO] Reading cached asset graph completed, took 735ms
[INFO] Checking for updates since last build completed, took 1.1s
[INFO] Running build completed, took 414ms
[INFO] Caching finalized dependency graph completed, took 507ms
[INFO] Creating merged output dir `build` completed, took 621ms
[INFO] Writing asset manifest completed, took 3ms
[INFO] Succeeded after 3.9s with 0 outputs (0 actions)
PS D:\MyDartProjects\cmpop\cmpop_browser> rm -r .\build\
PS D:\MyDartProjects\cmpop\cmpop_browser> webdev build
[INFO] Reading cached asset graph completed, took 729ms
[INFO] Checking for updates since last build completed, took 1.1s
[INFO] Running build completed, took 420ms
[INFO] Caching finalized dependency graph completed, took 513ms
[INFO] Creating merged output dir `build` completed, took 1.1s
[INFO] Writing asset manifest completed, took 5ms
[INFO] Succeeded after 4.4s with 0 outputs (0 actions)

```

**Comment by jakemac53** [comment] 2021-07-28 21:14
Ok, so it seems like the problem is to do with that `build/` directory. Note that you can use I think `--output=NONE` to disable this. 

I don't know what would cause this to not occur on older sdks though.

**Comment by annagrin** [comment] 2021-07-29 01:38
The fix that was done in watcher just restarted it forever, but it seems like it does not anymore in this example. I wonder if something changed in the watcher or the use of it...

**Comment by annagrin** [comment] 2021-07-29 01:45
@jakemac53 Is it possible to configure the watcher in build_daemon not to monitor that directory?

**Comment by jakemac53** [comment] 2021-07-29 01:55
It isn't practical to unfortunately, no. We can't  exclude certain dirs from the watcher. And we have to watch the root dir of the package to detect file/directory changes at that level.

**Comment by annagrin** [comment] 2021-07-29 02:11
@jakemac53 I've got a theory - could it be this change: https://github.com/dart-lang/build/pull/2505
Looks like we exit immediately after watcher reports its error, so it it does not help that it is restarting...

https://github.com/dart-lang/build/blob/372dce1d7d04deb254d1db5ad433bbcaf3a7c471/build_runner/lib/src/watcher/graph_watcher.dart#L64

**Comment by jakemac53** [comment] 2021-07-29 17:26
Should we just be ignoring these errors? If we did, would the watcher would just restart?

**Comment by annagrin** [comment] 2021-07-29 22:19
I think so... but it would be nice to test:)

**Closed** 2021-08-05 14:34 UTC

**Comment by insinfo** [comment] 2021-08-05 20:27
https://github.com/dart-lang/build/pull/3167
It was not possible to use this solution as it is incompatible with angular



https://github.com/insinfo/app


```
Resolving dependencies...
Because no versions of sass_builder match >2.1.3 <2.1.4 and sass_builder >=2.1.4 depends on build_config ^1.0.0, sass_builder >2.1.3 requires build_config ^1.0.0.
And because sass_builder 2.1.3 depends on build >=0.12.5 <2.0.0, sass_builder >=2.1.3 requires build >=0.12.5 <2.0.0 or build_config ^1.0.0.
And because every version of build_runner from git depends on both build >=2.0.0 <2.1.0 and build_config >=0.4.7 <0.4.8, build_runner from git is incompatible with sass_builder >=2.1.3.
So, because turismo_browser depends on both sass_builder ^2.1.3 and build_runner from git, version solving failed.
exit code 1
--
[turismo_browser] dart pub get
Resolving dependencies...
Because every version of build_runner from git depends on build >=2.0.0 <2.1.0 and angular_components >=1.0.0 depends on build ^1.0.0, build_runner from git is incompatible with angular_components >=1.0.0.
So, because turismo_browser depends on both angular_components ^1.0.2 and build_runner from git, version solving failed.
exit code 1
```

```pubspec.yaml
name: turismo_browser
description: A web app that uses AngularDart Components
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  angular: ^6.0.0
  angular_components: ^1.0.2
  angular_router: ^2.0.0
  angular_forms: ^3.0.0
  sembast_web: ^1.2.0
  angular_recaptcha: ^0.1.5
  stream_transform: #^0.0.19

  sass_builder: any
  intl: '>=0.16.1 < 0.17.9'
  uuid: '>=2.2.2 < 3.0.9'
  crossplat_objectid: ^2.1.4  
  #dio: ^3.0.10
  http: '>=0.12.2 < 0.13.5'
  quiver: ^2.1.5

  turismo_core:
    path: ../turismo_core

dependency_overrides:
  build_runner:
    git:
      url: https://github.com/dart-lang/build.git
      ref: backport-watcher-fix
      path: build_runner

dev_dependencies: 
  angular_test: ^3.0.0                                                                                                 
  build_runner: ^1.10.4                                                                                                   
  build_test: ^1.3.0                                                                                              
  build_web_compilers: ^2.12.0                                                                                
  pedantic: ^1.9.2                                                                                               
  test: ^1.15.4

```


 build_runner: ^1.10.4

**Comment by annagrin** [comment] 2021-08-13 21:53
@jake @insinfo is this really solved? Do we need to make an update in an earlier version of build_runner?

**Comment by annagrin** [comment] 2021-08-13 21:54
Related: https://github.com/dart-lang/webdev/issues/1362

**Comment by jakemac53** [comment] 2021-08-16 16:19
I did backport this to an earlier version of build_runner yes (version `1.11.1+1` which we confirmed you can get with angular).

**Comment by insinfo** [comment] 2021-08-19 13:52
Has this version 1.11.1+1 been published?

**Comment by jakemac53** [comment] 2021-08-19 14:32
Yes
