### ISSUE TITLE
Incorrect error message when inotify filewatcher limit is reached

### ISSUE THREAD

**Issue by drbcode** [dart-lang/build#1714] opened 2018-08-05 16:33 UTC
```
FileSystemException: Failed to watch path, path = '/home/coder/new_home/projects/ng/ng_billing/ng_billing_admin/.dart_tool/build/generated/analyzer/lib/src/fasta' 
(OS Error: No space left on device, errno = 28)
dart:isolate  _RawReceivePortImpl._handleMessage

  error: exit status 1
```
There's plenty of storage space on device.
This error is resolved after increasing the amount of inotify watchers.
The error message should be `file watcher limit is reached` and not `No space left on device`.

```
OS:
ArchLinux

Dart SDK:
2.0.0-dev.69.3 

  build:
    version: "0.12.7+3"
  build_config:
    version: "0.3.1+2"
  build_modules:
    version: "0.3.1+1"
  build_resolvers:
    version: "0.2.1+1"
  build_runner:
    version: "0.10.0"
  build_runner_core:
    version: "0.3.0"
  build_web_compilers:
    version: "0.4.1"
  built_collection:
    version: "3.1.3"
```

**Comment by natebosch** [comment] 2018-08-05 17:54
We're somewhat limited in what we can do here, this is the error the os reports. We can probably catch this and make an assumption about the root cause and change the message...

**Comment by matanlurey** [comment] 2018-08-05 18:02
Duplicate of https://github.com/dart-lang/build/issues/1711 anyway.

**Closed by matanlurey** 2018-08-05 18:02 UTC
