### ISSUE TITLE
Snapshot is generated twice when upgrading core packages and language versions

### ISSUE THREAD

**Issue by simolus3** [dart-lang/build#3029] opened 2021-03-07 13:06 UTC
After upgrading `build_runner` and some dependencies, running the build causes two snapshots:

```
[INFO] Generating build script completed, took 279ms
[WARNING] Deleted previous snapshot due to core package update
[INFO] Creating build script snapshot... completed, took 11.8s
[INFO] There was output on stdout while compiling the build script snapshot, run with `--verbose` to see it (you will need to run a `clean` first to re-snapshot).
[WARNING] Throwing away cached asset graph because the language version of some package(s) changed. This would most commonly happen when updating dependencies or changing your min sdk constraint.
[INFO] Cleaning up outputs from previous builds. completed, took 5ms
[INFO] Generating build script completed, took 65ms
[INFO] Creating build script snapshot... completed, took 11.1s
[INFO] There was output on stdout while compiling the build script snapshot, run with `--verbose` to see it (you will need to run a `clean` first to re-snapshot).
```

I assume this wouldn't happen too often, but it's annoying since that build takes ~10s longer than it needs to.

**Comment by jakemac53** [comment] 2021-03-08 16:20
Ya there are actually a fair number of situations that can cause this - the solution isn't super obvious though unfortunately so we haven't yet addressed it.

If I recall the issue is that we generally try to keep the old asset graph around if we can, just because a package updated does not mean it actually affected the build (although it usually does). So we don't eagerly throw away the asset graph. Then after re-snapshotting we realize it did in fact change the build, and the behavior there is to do a full purge (including the just snapshotted script), so we re-snapshot. We would need to understand we had just snapshotted and not to throw away that snapshot or something but the code is very disconnected.

**Comment by simolus3** [comment] 2021-04-29 15:49
This is not really a clean solution, but do you think it could be possible to use a frontend server with incremental compilation to snapshot the build script? If we end up building multiple snapshots, the rebuilds should at least be cheap right? Could this also improve snapshot performance when only some builders change?

**Comment by jakemac53** [comment] 2021-04-29 15:55
Yes I was literally just thinking the same thing this morning - it would make it so that at least subsequent compiles were faster.

**Comment by jakemac53** [comment] 2021-05-03 14:33
I am going to go ahead and close this given we have incremental snapshot generation now, and fixing the actual problem is I think not worth the effort.

**Closed by jakemac53** 2021-05-03 14:33 UTC
