### ISSUE TITLE
[build_runner] More comprehensive measuring_performance.md

### ISSUE THREAD

**Issue by FufferKS** [dart-lang/build#3648] opened 2024-02-11 17:02 UTC
Hi, I've embarked on a journey to decrease the time taken by the build_runner in my project.

It would be extremely helpful if we got a bit more info on the performance measuring.
https://github.com/dart-lang/build/blob/master/docs/measuring_performance.md

The docs are quite short, but I would like to learn more about how to interpret the results, different view options, what is the difference between real time and user time, how to interpret the async slices, how to read actions that take longer, what steps are optimisable and which are not, etc etc.

If there are any learning materials you recommend or would be able to add to the official docs, it would be greatly appreciated!

**Comment by Serena867** [comment] 2024-02-11 20:05
Without touching on the part about measuring performance, I had some success speeding up my build time by making my `generate_for` targets fairly specific by using `includes` and `excludes`.

``` 
generate_for:
          include:
            - lib/ ...Add specific targets here
          exclude:
            - lib/ ...Exclude anything you don't need targeted here
```
 
 Thanks again to Jake and the rest of the Dart team on that one.

**Comment by FufferKS** [comment] 2024-02-12 09:43
True! It does help a lot, I browsed through the issues and am mostly basing my optimisations on this post:
https://github.com/dart-lang/build/issues/3491#issuecomment-1529868494

I am hoping that being able to more deeply understand the performance report could help me identify more pain points in my app and optimise even further.

**Comment by jakemac53** [comment] 2024-02-12 19:01
Note that I don't have any time available to improve the tooling here at this time, as I am 100% focused on macros currently. I can help explain the existing tooling a bit, but I can't prioritize any real work here at this time.

**Comment by FufferKS** [comment] 2024-02-13 11:08
> Note that I don't have any time available to improve the tooling here at this time, as I am 100% focused on macros currently. I can help explain the existing tooling a bit, but I can't prioritize any real work here at this time.

Sure, I appreciate your knowledge sharing and am so looking forward to macros 🤞 

> > To add to the questions - learning where things like this come from and how to get rid of them would be awesome.
> 
> What do you mean by this exactly?

On some of my runs I'm getting warnings `waiting on `build_resolvers:transitive_digests`` for deep transitive dependencies. 
Ideally I'd like to learn what `build_resolvers:transitive_digests` are, what causes them to sometimes delay for 15s and what could be done to improve it. The fact that it waits for external dependencies is a bit scary.

In the PR I mentioned I'd add some more questions:

- Color coding - a legend would be helpful to work out what means what. 

- astNodeFor - I can see a bunch of mentions of it, but not sure what they are?

<img width="753" alt="image" src="https://github.com/dart-lang/build/assets/23334356/0116f619-01fb-46f0-8fbb-d05cadf19e22">

- Single vs multiple files - What is more optimal for the sake of build_runner, having a single file with 10 freezed/jsonSerializable/etc classes or 10 files with 10 classes? I could run some benchmarks, but is there an argument for one or the other? 

- Is there a way to dig deeper into a single build step to figure out why it takes as long as it does? This file is one of chunkiest we have, but 10 seconds seems excessive (It has 17 freezed classes, one of which is a union with 13 subtypes + it imports around 12 standalone small freezed classes).

<img width="1073" alt="image" src="https://github.com/dart-lang/build/assets/23334356/5652c2a8-4994-4b6b-a053-190a2dad9bb7">

- I managed to improve the time taken by the builds following your comment from https://github.com/dart-lang/build/issues/3491#issuecomment-1529868494, I think it might be beneficial for others to drop that information into the docs too.

Thank you again for your time, really appreciate it!

**Comment by jakemac53** [comment] 2024-02-13 15:30
> On some of my runs I'm getting warnings waiting on build_resolvers:transitive_digests`` for deep transitive dependencies.

Most likely, it isn't truly waiting on this builder, but some input this builder is reading. This builder is actually an optimization, details [here](https://github.com/dart-lang/build/pull/3556). A resolver would have also been doing this work, but N different times. This builder caches that work so it only happens once.

> * Color coding - a legend would be helpful to work out what means what.

The colors have no meaning - they are just showing the different stages (setup, build, finalize).

> * astNodeFor - I can see a bunch of mentions of it, but not sure what they are?

Seems like maybe a bug in the output? I am not sure what is going on with that.

> * Single vs multiple files - What is more optimal for the sake of build_runner, having a single file with 10 freezed/jsonSerializable/etc classes or 10 files with 10 classes? I could run some benchmarks, but is there an argument for one or the other?

One file with 10 classes will be faster, I can say with very high confidence. Smaller build graph, less overhead. Most of the cost is actually overhead generally (getting a resolver).

> * Is there a way to dig deeper into a single build step to figure out why it takes as long as it does? This file is one of chunkiest we have, but 10 seconds seems excessive (It has 17 freezed classes, one of which is a union with 13 subtypes + it imports around 12 standalone small freezed classes).

You have to go into the builder implementation, but the [trackStage](https://pub.dev/documentation/build/latest/build/BuildStep/trackStage.html) API can be used to add custom tracking of individual pieces, to see what is taking so long.

**Comment by jakemac53** [comment] 2024-02-13 15:33
Feel free to keep asking questions here, even though the issue is closed since I merged the docs update

**Closed** 2024-02-13 15:33 UTC

**Comment by FufferKS** [comment] 2024-02-14 12:57
Thanks again!
