### ISSUE TITLE
build_runner serve failing with "FileSystemException: Directory listing failed"

### ISSUE THREAD

**Issue by jumperchen** [dart-lang/build#1963] opened 2019-01-10 07:46 UTC
Dart version: 2.1.0
We run with this command `pub run build_runner serve web:5678 --output=web:build/web --no-release --define 'build_web_compilers|entrypoint=compiler=dart2js'`

And the error displays as below:

```
FileSystemException: Directory listing failed, path = '/dart_project/node_modules/testcafe-hammerhead.MODULES/...' (OS Error: No such file or directory, errno = 2)
dart:isolate  _RawReceivePortImpl._handleMessage
```

Why does the build_runner watch the node_modules folder?
How to ignore that folder for watch?

**Comment by jakemac53** [comment] 2019-01-10 14:37
The build_runner package watches the root directory of the package - which unfortunately includes the node_modules directory if you have one.

Closing as a duplicate of https://github.com/dart-lang/build/issues/1579

**Closed by jakemac53** 2019-01-10 14:37 UTC
