### ISSUE TITLE
Delete builder outputs if it didn't run

### ISSUE THREAD

**Issue by nickclmb** [dart-lang/build#1695] opened 2018-07-31 14:21 UTC
Hey,

Here is situation: Lets say i have 3 builders: 
A   .dart => .a1   (may produce output or not)
B   .a1 => .b1    (doesn't read .dart file)
C   .b1 => .c1    (reads .b1 and .a1 files)

Now if i run build on file  example.dart, i will got files  example.a1, example.b1 and example.c1
After that, i do some changes in example.dart, and builder A doesn't produce output.

build_runner runs builder A - deletes .a1 output, but no new output produced.
build_runner doesn't run builder B, but doesn't remove .b1 from generated folder
build_runner see .b1 file and runs builder C, and it fails because there is no .a1 anymore

So I think the correct behavior is that build_runner should also delete .b1 and .c1 files if .a1 was not produced.

Here is repo with reproduce: https://github.com/nickclmb/build_runner_issue_with_deletes/

run `pub run build_runner build`
go to lib/example.dart, and delete all content
run `pub run build_runner build` again

If example.dart is empty - then BuilderA  has no output, but output of BuilderB stays in .dart_tool folder

**Comment by jakemac53** [comment] 2018-07-31 14:29
The build cache is not generally intended to be in a "pristine" state always - there are a few other reasons you might get stale assets under there.

Given that it isn't considered harmful to have those files exist (as long as the asset graph knows they are stale) this probably isn't going to be prioritized, but it would be reasonable to clean up eventually.

**Comment by nickclmb** [comment] 2018-07-31 14:35
We actually has this issue with build_modules. 
There is some complex logic when dart files may be generated or not by other $lib$ builder.  And if they were not generated by some reason, the .module file stays in .dart_tool folder, and linked and ddc builders fail with error.

**Comment by jakemac53** [comment] 2018-07-31 15:36
DDC actually runs in a separate temp directory - but it does have similar semantics to the .dart_tool generated directory in that it can have stale files. However, ddc shouldn't be reading any arbitrary files outside of the ones we explicitly tell it to, and those will always be up to date.

It seems more likely that the error you are seeing is caused by an ordering issue, where the module builders are being ran before all the dart files are available or something?

**Comment by natebosch** [comment] 2018-08-30 03:07
I'm going to close this since we don't have plans for trying to keep the generated directory as a perfect reflection of output files and since all file reads are going through a reader and not directly on this directory it should be safe.

If we can find a repro for one of the symptoms you believe is caused by this choice please file a new issue and we'll investigate - so far it seems like the possible issues are cause by builder and package/node ordering.

**Closed by natebosch** 2018-08-30 03:07 UTC
Labels: state: needs info
