### ISSUE TITLE
NoSuchMethodError: The getter 'futureDynamicType' was called on null.

### ISSUE THREAD

**Issue by DroidSU** [dart-lang/build#2762] opened 2020-07-25 08:16 UTC
Dart VM version: 2.8.2 (stable) (Mon May 11 15:06:42 2020 +0200) on "windows_x64"

dependencies -  
        analyzer: 0.34.3,  
        json_annotation: 2.3.0,  
        http: 0.12.2, 
        email_validator: 1.0.5,
        shared_preferences: 0.5.8,
                   
dev_dependencies - 
        build_runner: 1.1.3,
        json_serializable : 2.3.0,

Using Windows 10. 

I have uploaded the stacktrace. Running "flutter packages pub run build_runner build" causes this problem.

[issue.txt](https://github.com/dart-lang/build/files/4975076/issue.txt)

**Comment by tremp-m** [comment] 2020-07-26 18:35
i have same problem

**Comment by jakemac53** [comment] 2020-07-27 17:08
Duplicate of https://github.com/dart-lang/build/issues/2502

You need to `pub upgrade` or `flutter packages pub upgrade` to get the latest build_resolvers (this is a transitive dependency).

**Closed by jakemac53** 2020-07-27 17:08 UTC
