### ISSUE TITLE
Both "declaring" a builder and using another builder/generator for the source code of the "declared" builder.

### ISSUE THREAD

**Issue by emme1444** [dart-lang/build#3057] opened 2021-03-20 17:20 UTC
I'm currently writing a builder/generator package. Which has been going pretty well so far. Unfortunately I've now hit a roadblock. A minor problem if you will. 

I came across the idea of using `json_serializable` to decode my builder options' config. The problem occurs in trying to figure out how to both, so to say, "declare" a builder (from within the builder/generator package's `build.yaml` file) and configure and use `json_serializable`. 

So, basically, whenever I run `dart run build_runner build --delete-conflicting-outputs --verbose`; I get the following output.

```
[INFO] Entrypoint:Generating build script...
[INFO] Entrypoint:Generating build script completed, took 394ms

[INFO] Bootstrap:Creating build script snapshot......
[WARNING] Bootstrap:
stderr: lib/src/models/builder_config.dart:4:6: Error: Error when reading 'lib/src/models/builder_config.g.dart': The system cannot find the file specified.
[WARNING] Bootstrap:
stderr: 
[WARNING] Bootstrap:
stderr: part 'builder_config.g.dart';
[WARNING] Bootstrap:
stderr:      ^
[WARNING] Bootstrap:
stderr: lib/src/models/builder_config.dart:4:6: Error: Can't use 'lib/src/models/builder_config.g.dart' as a part, because it has no 'part of' declaration.
[WARNING] Bootstrap:
stderr: part 'builder_config.g.dart';
[WARNING] Bootstrap:
stderr:      ^
[WARNING] Bootstrap:
stderr: lib/src/models/builder_config.dart:26:7: Error: Method not found: '_$BuilderConfigFromJson'.
[WARNING] Bootstrap:
stderr:       _$BuilderConfigFromJson(json);
[WARNING] Bootstrap:
stderr:       ^^^^^^^^^^^^^^^^^^^^^^^
[WARNING] Bootstrap:
stderr: lib/src/models/builder_config.dart:28:36: Error: The method '_$BuilderConfigToJson' isn't defined for the class 'BuilderConfig'.
[WARNING] Bootstrap:
stderr:  - 'BuilderConfig' is from 'package:press_generator/src/models/builder_config.dart' ('lib/src/models/builder_config.dart').
[WARNING] Bootstrap:
stderr: Try correcting the name to the name of an existing method, or defining a method named '_$BuilderConfigToJson'.
[WARNING] Bootstrap:
stderr:   Map<String, dynamic> toJson() => _$BuilderConfigToJson(this);
[WARNING] Bootstrap:
stderr:                                    ^^^^^^^^^^^^^^^^^^^^^
[INFO] Bootstrap:Creating build script snapshot... completed, took 8.1s

[SEVERE] Bootstrap:
Failed to snapshot build script .dart_tool/build/entrypoint/build.dart.
This is likely caused by a misconfigured builder definition.
```

And at last, there is no output from the builder.

Here is my `build.yaml`:

```yaml
targets:
  $default:
    builders:
      json_serializable:
        enabled: true
        options:
          disallow_unrecognized_keys: true
# press_generator:press:
#   enabled: false

builders:
  press:
    import: "package:press_generator/builder.dart"
    # builder_factories: ["pressBuilder"]
    builder_factories:
      - pressBuilder
    # build_extensions: { "$package$": ["lib/src/cli.dart"] }
    build_extensions:
      $package$:
        - lib/src/cli.dart
    auto_apply: root_package
    # auto_apply: dependents
    build_to: source
    # applies_builders:
    #   - json_serializable
    # runs_before:
    #   - json_serializable
    # required_inputs: [".g.dart"]

```

My workaround for running the `json_serializable` builder at the moment is to comment out the whole `builder` map including the key. 

At first, I thought it might have to do with the fact that _my_ builder might be run before or something like that. The output mentions that it cannot find the file `.../builder_config.g.dart` ... because it just removed it to re-create it. But what? Anyway, if so; how would I consider changing the order of the two (_my_ builder and `json_serializable` that is). 

As you can see, there's a bunch of commented lines for what I've tried but failed. Maybe I was on the right track or missed something, maybe this actually is some bug, I don't know. One of the things I tried was "disabling" my own builder for the $default target. But haven't quite fully grasped that so far.

If not that above, what could be a probable cause for these warnings and the build "not snapshotting"/exiting abruptly? I have observed the output mentioning that it likely has to do with a misconfigured builder definition. So my builder in the `builders` map, but why? 

I can't seem to figure out what this might have to do with. Any help would be greatly appreciated. 

Thanks!

---

* **Dart SDK Version (`dart --version`):**
  `Dart SDK version: 2.12.1 (stable) (Wed Mar 10 10:18:47 2021 +0100) on "windows_x64"`
* **What package(s) from this repo you are using, and the version (i.e. `build_runner 0.7.12`):** 
  * `build`: `2.0.0`
  * `build_runner`: `1.12.2`
    * `build_config`: `0.4.7` (implicit)
      * `build_daemon`: `2.1.10` (implicit)
      * `build_resolvers`: `2.0.0` (implicit)
      * `build_runner_core`: `6.1.12` (implicit)

* **Whether you are using Windows, MacOSX, or Linux (if applicable):** 
  Windows
* **Any other packages or constraints we should know about:** 
  * `json_annotation`: `4.0.1`
  * `json_serializable`: `4.1.0`
  * `source_gen`: `1.0.0`

**Comment by jakemac53** [comment] 2021-03-22 16:02
The problem is that when you try to do this the build script itself is invalid, it can't even start. This is because it has missing generated files that are a part of the build.

There isn't any explicitly supported solution here. You can move these files to a separate package, which doesn't depend on your actual builder, and then depend on that. It is a bit cumbersome but works.

Or if you can get a single successful build in your package you can leave those files checked in and it will kind of work, but when you do a `clean` it will break and you would have to restore the files manually etc, it is a pain.

**Closed by jakemac53** 2021-03-22 16:02 UTC

**Comment by emme1444** [comment] 2021-03-25 21:40
Thanks @jakemac53 for the response!

First of all, I totally thought this was a misconfiguration or something of the like. I definitely did not think this wouldn't be possible? Anyway, here's me just trying to understand the tools I'm working with.

> The problem is that when you try to do this the build script itself is invalid, it can't even start. This is because it has missing generated files that are a part of the build.

Could you elaborate _more precisely_ on why it can't start?

> This is because it has missing generated files that are a part of the build.

_What generated files_ are part of _what build_. Or what?

> There isn't any explicitly supported solution here.

Might there be a solution in the future? Or is this somehow blocked by the way it is handled behind the scenes, something that prevents this from being possible at all? Just wondering.

**Comment by jakemac53** [comment] 2021-03-25 21:49
> Could you elaborate _more precisely_ on why it can't start?

The way the build system works, we generate a build script which imports all the builders that you use. The build itself runs by just running this script (`pub run build_runner` is really just a wrapper that generates a real build script and then runs it).

This script imports your builder, which has references to generated files that won't exist until the build actually runs, so the build script itself is thus not valid.
 
> _What generated files_ are part of _what build_. Or what?

Hopefully the above makes this more clear?

> Might there be a solution in the future? Or is this somehow blocked by the way it is handled behind the scenes, something that prevents this from being possible at all? Just wondering.

There is no plan to fix this. The best recommendation is to not make your builder code use any builders itself - it can depend on other _packages_ that have generated code though so you can move that code to another package. Those packages would then be built via their own, separate build script, which doesn't use your builder, and thus doesn't have a problem.

**Comment by emme1444** [comment] 2021-03-26 19:39
I see! Oh well...

One last question: When you say to seperate the part that uses `json_serializable` out to a seperate package, do you mean something in the style of _path dependencies_? Or where you thinking something else? Can't seem to figure it out, since packages that depend on _path dependencies_ can't be published. Or would you publish it to pub.dev along-side the builder/generator package?

Thank you so much for your time.

**Comment by jakemac53** [comment] 2021-03-29 14:42
> Or would you publish it to pub.dev along-side the builder/generator package?

Right you would likely use a path dependency for development (using dependency_overrides) and then publish them both to pub (without the overrides).
