### ISSUE TITLE
Got a bug message

### ISSUE THREAD

**Issue by feinstein** [dart-lang/build#2850] opened 2020-10-02 06:13 UTC
I got a bug message asking to open an issue about it:

```
AssetNotFoundException: myapp|.dart_tool/package_config.json
package:build_runner_core/src/asset/file_based.dart 134:18  _fileForOrThrow.<fn>
dart:async                                                  _completeOnAsyncReturn
package:pool/pool.dart                                      Pool.withResource
package:build_runner_core/src/asset/file_based.dart 133:26  _fileForOrThrow
package:build_runner_core/src/asset/file_based.dart 33:48   FileBasedAssetReader.readAsBytes
package:build_runner/src/generate/watch_impl.dart 272:46    WatchImpl._run.<fn>
```

**Comment by jakemac53** [comment] 2020-10-02 15:53
Is this consistently happening or did it just happen one time and then go away?

I think this was most likely a race condition where the file was being re-written by pub (or some other tool) exactly when this code was ran

**Comment by feinstein** [comment] 2020-10-02 15:55
Just one time.

**Comment by jakemac53** [comment] 2020-10-02 15:58
Ok - I am going to close this as a duplicate of https://github.com/dart-lang/build/issues/2790 which I think is the same issue.

It is a real problem, although we haven't yet come up with a creative solution for it.

**Closed by jakemac53** 2020-10-02 15:58 UTC

**Comment by feinstein** [comment] 2020-10-02 16:00
Ok no problem :)
