### ISSUE TITLE
Null-safety

### ISSUE THREAD

**Issue by ammaratef45** [dart-lang/build#3037] opened 2021-03-11 18:25 UTC
What is the plan for upgrading to support null-safety?

**Comment by jakemac53** [comment] 2021-03-11 18:41
See https://github.com/dart-lang/build/issues/2920 - this is nearly ready to be published we are just validating things internally right now.

**Comment by jakemac53** [comment] 2021-03-11 18:41
(the issue is closed because we have actually landed all the code necessary to write and test a null safe builder in sound mode, we just need to publish)

**Closed by jakemac53** 2021-03-11 18:41 UTC

**Comment by BartusZak** [comment] 2021-03-24 08:06
Hej @jakemac53 

I am just checking availability to update my project to flutter 2.0 and dart with null safety support.

Run:
```
dart pub outdated --mode=null-safety
```

Result:

```
Resolving...
Showing dependencies that are currently not opted in to null-safety.
[✗] indicates versions without null safety support.
[✓] indicates versions opting in to null safety.  

Package Name                          Current        Upgradable      Resolvable  Latest
...
dev_dependencies:
build_runner                          ✗1.11.1        ✗1.11.5         -           ✗1.12.2
flutter_launcher_icons                ✗0.8.1         ✗0.8.1          -           ✓0.9.0
...
```

**Comment by jakemac53** [comment] 2021-03-24 14:30
You can freely update to null safety - note that `build_runner` itself is not migrated but that only means the build itself will not run with sound null safety. Your project should not be directly importing `build_runner` and so it can run with sound null safety without issue.

**Comment by petoknm** [comment] 2021-03-25 16:37
@jakemac53 can you please elaborate on how to upgrade a project that uses build_runner to null safety? I've been trying to follow the official migration guide with no luck for a few hours now...

**Comment by jakemac53** [comment] 2021-03-25 17:03
@petoknm where are you running into issues?

**Comment by petoknm** [comment] 2021-03-25 17:18
```shell
$ dart pub outdated --mode=null-safety
...
No resolution was found. Try running `dart pub upgrade --null-safety --dry-run` to explore why.
$ dart pub upgrade --null-safety --dry-run
null-safety compatible versions do not exist for:
 - build_runner
 - hive_generator
...
```
And from then on I cannot follow the guide, because technically not all my deps are null safe. So I'm unsure what to do.

**Comment by jakemac53** [comment] 2021-03-25 17:59
You can ignore these, and continue to follow the guide. As long as they are not imported directly it won't impact the migration.

**Comment by felixwortmann** [comment] 2021-03-28 18:31
> You can ignore these, and continue to follow the guide. As long as they are not imported directly it won't impact the migration.

@jakemac53  Where can I find that guide?

**Comment by petoknm** [comment] 2021-03-28 19:47
@felixwortmann https://dart.dev/null-safety/migration-guide
