### ISSUE TITLE
Cannot run angulardart's webdev serve command. Crash directed me here.

### ISSUE THREAD

**Issue by advonesix** [dart-lang/build#2542] opened 2019-11-13 18:43 UTC
Thank you for taking the time to file an issue!

In order to route, prioritize, and act on this as soon as possible please include:

* Dart SDK Version (`dart --version`)
Dart VM version: 2.6.0 (Thu Oct 24 17:52:22 2019 +0200) on "windows_x64"

* What package(s) from this repo you are using, and the version (i.e. `build_runner 0.7.12`)
[pubspec.lock](https://github.com/dart-lang/build/files/3842807/pubspec.lock.txt)

* What builder(s) you are using (or writing yourself). Try to give a short summary of what they do.
Just trying to use the `webdev serve` command from angular dart

* Whether you are using Windows, MacOSX, or Linux (if applicable)
Win 10 Enterprise version 1903

* Whether you are using Chrome, Safari, Firefox, Edge (if applicable)
n/a 

* Any other packages or constraints we should know about
n/a

A couple days ago I upgraded my Dart SDK to the latest stable release. I do not know the previous version I was upgrading from, but I have not used dart in a while. I previously updated maybe ~6 - 12 months ago.

Today I returned to an angulardart project that I have not worked on in some time. (maybe 2 or 3 months)

I simply opened the project and tried to run 'webdev serve' which caused a crash and directed me here:
```

Microsoft Windows [Version 10.0.18362.418]
(c) 2019 Microsoft Corporation. All rights reserved.

C:\programming\projects\web\api.example.com-dashboard>webdev serve
webdev could not run for this project.
Dart 2.6.0 is incompatible with your dependencies' SDK constraints. Please run "pub get" again.

C:\programming\projects\web\api.example.com-dashboard>pub get
Resolving dependencies...
> dart_internal 0.1.7 (was 0.1.5)
Downloading dart_internal 0.1.7...
Changed 1 dependency!
Precompiling executables...
Precompiled build_runner:graph_inspector.
Precompiled test:test.
Precompiled build_runner:build_runner.

C:\programming\projects\web\api.example.com-dashboard>webdev serve
[WARNING] Throwing away cached asset graph due to Dart SDK update.
[INFO] Cleaning up outputs from previous builds. completed, took 810ms
[INFO] Building new asset graph completed, took 2.4s
[INFO] Checking for unexpected pre-existing outputs. completed, took 1ms
[INFO] Serving `web` on http://127.0.0.1:8080
[SEVERE]
[SEVERE]
[SEVERE] You have hit a bug in build_runner
[SEVERE] Please file an issue with reproduction steps at https://github.com/dart-lang/build/issues
[SEVERE]
[SEVERE]
[SEVERE] type 'DynamicTypeImpl' is not a subtype of type 'InterfaceType'
ERROR - 2019-11-13 11:22:22.113783
GET /
Error thrown by handler.
Connection closed before full header was received
dart:isolate  _RawReceivePortImpl._handleMessage

[SEVERE] package:analyzer/src/summary/link.dart 5473:5                     TypeProviderForLink._buildInterfaceType
[SEVERE] package:analyzer/src/summary/link.dart 5438:23                    TypeProviderForLink.objectType
[SEVERE] package:analyzer/src/summary/link.dart 918:67                     ClassElementForLink_Class._computeInterfaceType
[SEVERE] package:analyzer/src/summary/link.dart 816:27                     ClassElementForLink_Class.supertype
[SEVERE] package:analyzer/src/task/strong_mode.dart 294:33                 InstanceMemberInferrer._inferClass
[SEVERE] package:analyzer/src/task/strong_mode.dart 326:9                  InstanceMemberInferrer._inferClasses
[SEVERE] package:analyzer/src/task/strong_mode.dart 55:5                   InstanceMemberInferrer.inferCompilationUnit
[SEVERE] package:analyzer/src/summary/link.dart 1618:7                     CompilationUnitElementInBuildUnit.link
[SEVERE] package:analyzer/src/summary/link.dart 3814:12                    LibraryElementInBuildUnit.link
[SEVERE] package:analyzer/src/summary/link.dart 3517:15                    LibraryCycleNode.link
[SEVERE] package:analyzer/src/summary/link.dart 3457:7                     LibraryCycleDependencyWalker.evaluate
[SEVERE] package:analyzer/src/summary/link.dart 2199:13                    DependencyWalker.walk.strongConnect
[SEVERE] package:analyzer/src/summary/link.dart 2165:24                    DependencyWalker.walk.strongConnect
[SEVERE] package:analyzer/src/summary/link.dart 2165:24                    DependencyWalker.walk.strongConnect
[SEVERE] package:analyzer/src/summary/link.dart 2165:24                    DependencyWalker.walk.strongConnect
[SEVERE] package:analyzer/src/summary/link.dart 2218:18                    DependencyWalker.walk
[SEVERE] package:analyzer/src/summary/link.dart 3490:42                    LibraryCycleForLink.ensureLinked
[SEVERE] package:analyzer/src/summary/link.dart 4019:35                    Linker.link
[SEVERE] package:analyzer/src/summary/link.dart 306:74                     _relink
[SEVERE] package:analyzer/src/summary/link.dart 123:3                      link
[SEVERE] package:analyzer/src/dart/analysis/library_context.dart 170:25    LibraryContext.load.<fn>
[SEVERE] package:analyzer/src/dart/analysis/performance_logger.dart 34:15  PerformanceLog.run
[SEVERE] package:analyzer/src/dart/analysis/library_context.dart 169:12    LibraryContext.load
[SEVERE] package:analyzer/src/dart/analysis/library_context.dart 73:5      new LibraryContext
[SEVERE] package:analyzer/src/dart/analysis/driver.dart 1612:29            AnalysisDriver._createLibraryContext
[SEVERE] package:analyzer/src/dart/analysis/driver.dart 1556:26            AnalysisDriver._computeUnitElement
[SEVERE] package:analyzer/src/dart/analysis/driver.dart 1158:34            AnalysisDriver.performWork
[SEVERE] package:analyzer/src/dart/analysis/driver.dart 2145:24            AnalysisDriverScheduler._run
[SEVERE] package:analyzer/src/dart/analysis/driver.dart 2075:5             AnalysisDriverScheduler.start
[SEVERE] package:build_resolvers/src/analysis_driver.dart 54:13            analysisDriver
[SEVERE] package:build_resolvers/src/resolver.dart 138:18                  new AnalyzerResolvers
[SEVERE] package:build_runner_core/src/generate/options.dart 132:19        BuildOptions.create
[SEVERE] package:build_runner/src/daemon/daemon_builder.dart 180:43        BuildRunnerDaemonBuilder.create
[SEVERE] package:build_runner/src/entrypoint/daemon.dart 83:48             DaemonCommand.run
[SEVERE] package:args/command_runner.dart 197:27                           CommandRunner.runCommand
[SEVERE] package:args/command_runner.dart 112:25                           CommandRunner.run.<fn>
[SEVERE] dart:async                                                        new Future.sync
[SEVERE] package:args/command_runner.dart 112:14                           CommandRunner.run
[SEVERE] package:build_runner/src/entrypoint/run.dart 24:31                run
[SEVERE] .dart_tool\build\entrypoint\build.dart 130:22                     main
[SEVERE]
ERROR - 2019-11-13 11:22:24.346632
GET /favicon.ico
Error thrown by handler.
SocketException: OS Error: The remote computer refused the network connection.
, errno = 1225, address = localhost, port = 55161
dart:isolate  _RawReceivePortImpl._handleMessage
```

There have been no changes in my network setup, and previously webdev serve worked just fine. I am just trying to serve on localhost. Really not sure why "The remote computer refused the network connection."

Any idea on how I can get this to build?

**Comment by jakemac53** [comment] 2019-11-13 18:44
Duplicate of https://github.com/dart-lang/build/issues/2502 - tldr; you need to upgrade your dependencies using `pub upgrade` or `flutter pub upgrade`.

**Closed by jakemac53** 2019-11-13 18:44 UTC
