### ISSUE TITLE
[build_runner] DefaultBuildTargetSerializer.serialize type mismatch

### ISSUE THREAD

**Issue by creativecreatorormaybenot** [dart-lang/build#3131] opened 2021-06-18 13:16 UTC
## Problem

In one of our packages, `flutter pub run build_runner build ` fails instantly, it seems like it is failing to compile:

```
Failed to build build_runner:build_runner:
../.pub-cache/hosted/pub.dartlang.org/build_daemon-3.0.0/lib/data/build_target.g.dart:22:21: Error: The return type of the method '_$DefaultBuildTargetSerializer.serialize' is 'Iterable<Object?>', which does not match the return type, 'Iterable<Object>', of the overridden method, 'StructuredSerializer.serialize'.
 - 'Iterable' is from 'dart:core'.
 - 'Object' is from 'dart:core'.
Change to a subtype of 'Iterable<Object>'.
  Iterable<Object?> serialize(
```

This type mismatch is logged many times, here is the full log:

<details><summary>Click to expand logs</summary>

```
Failed to build build_runner:build_runner:
../.pub-cache/hosted/pub.dartlang.org/build_daemon-3.0.0/lib/data/build_target.g.dart:22:21: Error: The return type of the method '_$DefaultBuildTargetSerializer.serialize' is 'Iterable<Object?>', which does not match the return type, 'Iterable<Object>', of the overridden method, 'StructuredSerializer.serialize'.
 - 'Iterable' is from 'dart:core'.
 - 'Object' is from 'dart:core'.
Change to a subtype of 'Iterable<Object>'.
  Iterable<Object?> serialize(
                    ^
../.pub-cache/hosted/pub.dartlang.org/built_value-8.0.0/lib/serializer.dart:346:20: Context: This is the overridden method ('serialize').
  Iterable<Object> serialize(Serializers serializers, T object,
                   ^
../.pub-cache/hosted/pub.dartlang.org/build_daemon-3.0.0/lib/data/build_target.g.dart:101:21: Error: The return type of the method '_$OutputLocationSerializer.serialize' is 'Iterable<Object?>', which does not match the return type, 'Iterable<Object>', of the overridden method, 'StructuredSerializer.serialize'.
 - 'Iterable' is from 'dart:core'.
 - 'Object' is from 'dart:core'.
Change to a subtype of 'Iterable<Object>'.
  Iterable<Object?> serialize(Serializers serializers, OutputLocation object,
                    ^
../.pub-cache/hosted/pub.dartlang.org/built_value-8.0.0/lib/serializer.dart:346:20: Context: This is the overridden method ('serialize').
  Iterable<Object> serialize(Serializers serializers, T object,
                   ^
../.pub-cache/hosted/pub.dartlang.org/build_daemon-3.0.0/lib/data/build_request.g.dart:19:21: Error: The return type of the method '_$BuildRequestSerializer.serialize' is 'Iterable<Object?>', which does not match the return type, 'Iterable<Object>', of the overridden method, 'StructuredSerializer.serialize'.
 - 'Iterable' is from 'dart:core'.
 - 'Object' is from 'dart:core'.
Change to a subtype of 'Iterable<Object>'.
  Iterable<Object?> serialize(Serializers serializers, BuildRequest object,
                    ^
../.pub-cache/hosted/pub.dartlang.org/built_value-8.0.0/lib/serializer.dart:346:20: Context: This is the overridden method ('serialize').
  Iterable<Object> serialize(Serializers serializers, T object,
                   ^
../.pub-cache/hosted/pub.dartlang.org/build_daemon-3.0.0/lib/data/build_status.g.dart:64:21: Error: The return type of the method '_$DefaultBuildResultSerializer.serialize' is 'Iterable<Object?>', which does not match the return type, 'Iterable<Object>', of the overridden method, 'StructuredSerializer.serialize'.
 - 'Iterable' is from 'dart:core'.
 - 'Object' is from 'dart:core'.
Change to a subtype of 'Iterable<Object>'.
  Iterable<Object?> serialize(
                    ^
../.pub-cache/hosted/pub.dartlang.org/built_value-8.0.0/lib/serializer.dart:346:20: Context: This is the overridden method ('serialize').
  Iterable<Object> serialize(Serializers serializers, T object,
                   ^
../.pub-cache/hosted/pub.dartlang.org/build_daemon-3.0.0/lib/data/build_status.g.dart:146:21: Error: The return type of the method '_$BuildResultsSerializer.serialize' is 'Iterable<Object?>', which does not match the return type, 'Iterable<Object>', of the overridden method, 'StructuredSerializer.serialize'.
 - 'Iterable' is from 'dart:core'.
 - 'Object' is from 'dart:core'.
Change to a subtype of 'Iterable<Object>'.
  Iterable<Object?> serialize(Serializers serializers, BuildResults object,
                    ^
../.pub-cache/hosted/pub.dartlang.org/built_value-8.0.0/lib/serializer.dart:346:20: Context: This is the overridden method ('serialize').
  Iterable<Object> serialize(Serializers serializers, T object,
                   ^
../.pub-cache/hosted/pub.dartlang.org/build_daemon-3.0.0/lib/data/build_target_request.g.dart:20:21: Error: The return type of the method '_$BuildTargetRequestSerializer.serialize' is 'Iterable<Object?>', which does not match the return type, 'Iterable<Object>', of the overridden method, 'StructuredSerializer.serialize'.
 - 'Iterable' is from 'dart:core'.
 - 'Object' is from 'dart:core'.
Change to a subtype of 'Iterable<Object>'.
  Iterable<Object?> serialize(
                    ^
../.pub-cache/hosted/pub.dartlang.org/built_value-8.0.0/lib/serializer.dart:346:20: Context: This is the overridden method ('serialize').
  Iterable<Object> serialize(Serializers serializers, T object,
                   ^
../.pub-cache/hosted/pub.dartlang.org/build_daemon-3.0.0/lib/data/shutdown_notification.g.dart:23:21: Error: The return type of the method '_$ShutdownNotificationSerializer.serialize' is 'Iterable<Object?>', which does not match the return type, 'Iterable<Object>', of the overridden method, 'StructuredSerializer.serialize'.
 - 'Iterable' is from 'dart:core'.
 - 'Object' is from 'dart:core'.
Change to a subtype of 'Iterable<Object>'.
  Iterable<Object?> serialize(
                    ^
../.pub-cache/hosted/pub.dartlang.org/built_value-8.0.0/lib/serializer.dart:346:20: Context: This is the overridden method ('serialize').
  Iterable<Object> serialize(Serializers serializers, T object,
                   ^
../.pub-cache/hosted/pub.dartlang.org/build_daemon-3.0.0/lib/data/server_log.g.dart:79:21: Error: The return type of the method '_$ServerLogSerializer.serialize' is 'Iterable<Object?>', which does not match the return type, 'Iterable<Object>', of the overridden method, 'StructuredSerializer.serialize'.
 - 'Iterable' is from 'dart:core'.
 - 'Object' is from 'dart:core'.
Change to a subtype of 'Iterable<Object>'.
  Iterable<Object?> serialize(Serializers serializers, ServerLog object,
                    ^
../.pub-cache/hosted/pub.dartlang.org/built_value-8.0.0/lib/serializer.dart:346:20: Context: This is the overridden method ('serialize').
  Iterable<Object> serialize(Serializers serializers, T object,
                   ^
../.pub-cache/hosted/pub.dartlang.org/build_daemon-3.0.0/lib/data/server_log.g.dart:125:50: Error: The argument type 'Object?' can't be assigned to the parameter type 'Object' because 'Object?' is nullable and 'Object' isn't.
 - 'Object' is from 'dart:core'.
          result.level = serializers.deserialize(value,
                                                 ^
../.pub-cache/hosted/pub.dartlang.org/build_daemon-3.0.0/lib/data/server_log.g.dart:129:52: Error: The argument type 'Object?' can't be assigned to the parameter type 'Object' because 'Object?' is nullable and 'Object' isn't.
 - 'Object' is from 'dart:core'.
          result.message = serializers.deserialize(value,
                                                   ^
../.pub-cache/hosted/pub.dartlang.org/build_daemon-3.0.0/lib/data/server_log.g.dart:133:55: Error: The argument type 'Object?' can't be assigned to the parameter type 'Object' because 'Object?' is nullable and 'Object' isn't.
 - 'Object' is from 'dart:core'.
          result.loggerName = serializers.deserialize(value,
                                                      ^
../.pub-cache/hosted/pub.dartlang.org/build_daemon-3.0.0/lib/data/server_log.g.dart:137:50: Error: The argument type 'Object?' can't be assigned to the parameter type 'Object' because 'Object?' is nullable and 'Object' isn't.
 - 'Object' is from 'dart:core'.
          result.error = serializers.deserialize(value,
                                                 ^
../.pub-cache/hosted/pub.dartlang.org/build_daemon-3.0.0/lib/data/server_log.g.dart:141:55: Error: The argument type 'Object?' can't be assigned to the parameter type 'Object' because 'Object?' is nullable and 'Object' isn't.
 - 'Object' is from 'dart:core'.
          result.stackTrace = serializers.deserialize(value,
                                                      ^
../.pub-cache/hosted/pub.dartlang.org/build_daemon-3.0.0/lib/data/build_target.g.dart:66:68: Error: The argument type 'Object?' can't be assigned to the parameter type 'Object' because 'Object?' is nullable and 'Object' isn't.
 - 'Object' is from 'dart:core'.
          result.blackListPatterns.replace(serializers.deserialize(value,
                                                                   ^
../.pub-cache/hosted/pub.dartlang.org/build_daemon-3.0.0/lib/data/build_target.g.dart:66:56: Warning: Operand of null-aware operation '!' has type 'Object' which excludes null.
 - 'Object' is from 'dart:core'.
          result.blackListPatterns.replace(serializers.deserialize(value,
                                                       ^
../.pub-cache/hosted/pub.dartlang.org/build_daemon-3.0.0/lib/data/build_target.g.dart:72:65: Error: The argument type 'Object?' can't be assigned to the parameter type 'Object' because 'Object?' is nullable and 'Object' isn't.
 - 'Object' is from 'dart:core'.
          result.outputLocation.replace(serializers.deserialize(value,
                                                                ^
../.pub-cache/hosted/pub.dartlang.org/build_daemon-3.0.0/lib/data/build_target.g.dart:72:53: Warning: Operand of null-aware operation '!' has type 'Object' which excludes null.
 - 'Object' is from 'dart:core'.
          result.outputLocation.replace(serializers.deserialize(value,
                                                    ^
../.pub-cache/hosted/pub.dartlang.org/build_daemon-3.0.0/lib/data/build_target.g.dart:77:63: Error: The argument type 'Object?' can't be assigned to the parameter type 'Object' because 'Object?' is nullable and 'Object' isn't.
 - 'Object' is from 'dart:core'.
          result.buildFilters.replace(serializers.deserialize(value,
                                                              ^
../.pub-cache/hosted/pub.dartlang.org/build_daemon-3.0.0/lib/data/build_target.g.dart:77:51: Warning: Operand of null-aware operation '!' has type 'Object' which excludes null.
 - 'Object' is from 'dart:core'.
          result.buildFilters.replace(serializers.deserialize(value,
                                                  ^
../.pub-cache/hosted/pub.dartlang.org/build_daemon-3.0.0/lib/data/build_target.g.dart:83:51: Error: The argument type 'Object?' can't be assigned to the parameter type 'Object' because 'Object?' is nullable and 'Object' isn't.
 - 'Object' is from 'dart:core'.
          result.target = serializers.deserialize(value,
                                                  ^
../.pub-cache/hosted/pub.dartlang.org/build_daemon-3.0.0/lib/data/build_target.g.dart:130:51: Error: The argument type 'Object?' can't be assigned to the parameter type 'Object' because 'Object?' is nullable and 'Object' isn't.
 - 'Object' is from 'dart:core'.
          result.output = serializers.deserialize(value,
                                                  ^
../.pub-cache/hosted/pub.dartlang.org/build_daemon-3.0.0/lib/data/build_target.g.dart:134:56: Error: The argument type 'Object?' can't be assigned to the parameter type 'Object' because 'Object?' is nullable and 'Object' isn't.
 - 'Object' is from 'dart:core'.
          result.useSymlinks = serializers.deserialize(value,
                                                       ^
../.pub-cache/hosted/pub.dartlang.org/build_daemon-3.0.0/lib/data/build_target.g.dart:138:50: Error: The argument type 'Object?' can't be assigned to the parameter type 'Object' because 'Object?' is nullable and 'Object' isn't.
 - 'Object' is from 'dart:core'.
          result.hoist = serializers.deserialize(value,
                                                 ^
../.pub-cache/hosted/pub.dartlang.org/build_daemon-3.0.0/lib/data/build_status.g.dart:113:51: Error: The argument type 'Object?' can't be assigned to the parameter type 'Object' because 'Object?' is nullable and 'Object' isn't.
 - 'Object' is from 'dart:core'.
          result.status = serializers.deserialize(value,
                                                  ^
../.pub-cache/hosted/pub.dartlang.org/build_daemon-3.0.0/lib/data/build_status.g.dart:117:51: Error: The argument type 'Object?' can't be assigned to the parameter type 'Object' because 'Object?' is nullable and 'Object' isn't.
 - 'Object' is from 'dart:core'.
          result.target = serializers.deserialize(value,
                                                  ^
../.pub-cache/hosted/pub.dartlang.org/build_daemon-3.0.0/lib/data/build_status.g.dart:121:52: Error: The argument type 'Object?' can't be assigned to the parameter type 'Object' because 'Object?' is nullable and 'Object' isn't.
 - 'Object' is from 'dart:core'.
          result.buildId = serializers.deserialize(value,
                                                   ^
../.pub-cache/hosted/pub.dartlang.org/build_daemon-3.0.0/lib/data/build_status.g.dart:125:50: Error: The argument type 'Object?' can't be assigned to the parameter type 'Object' because 'Object?' is nullable and 'Object' isn't.
 - 'Object' is from 'dart:core'.
          result.error = serializers.deserialize(value,
                                                 ^
../.pub-cache/hosted/pub.dartlang.org/build_daemon-3.0.0/lib/data/build_status.g.dart:129:53: Error: The argument type 'Object?' can't be assigned to the parameter type 'Object' because 'Object?' is nullable and 'Object' isn't.
 - 'Object' is from 'dart:core'.
          result.isCached = serializers.deserialize(value,
                                                    ^
../.pub-cache/hosted/pub.dartlang.org/build_daemon-3.0.0/lib/data/build_status.g.dart:171:58: Error: The argument type 'Object?' can't be assigned to the parameter type 'Object' because 'Object?' is nullable and 'Object' isn't.
 - 'Object' is from 'dart:core'.
          result.results.replace(serializers.deserialize(value,
                                                         ^
../.pub-cache/hosted/pub.dartlang.org/build_daemon-3.0.0/lib/data/build_status.g.dart:171:46: Warning: Operand of null-aware operation '!' has type 'Object' which excludes null.
 - 'Object' is from 'dart:core'.
          result.results.replace(serializers.deserialize(value,
                                             ^
../.pub-cache/hosted/pub.dartlang.org/build_daemon-3.0.0/lib/data/build_target_request.g.dart:45:51: Error: The argument type 'Object?' can't be assigned to the parameter type 'Object' because 'Object?' is nullable and 'Object' isn't.
 - 'Object' is from 'dart:core'.
          result.target = serializers.deserialize(value,
                                                  ^
../.pub-cache/hosted/pub.dartlang.org/build_daemon-3.0.0/lib/data/shutdown_notification.g.dart:51:52: Error: The argument type 'Object?' can't be assigned to the parameter type 'Object' because 'Object?' is nullable and 'Object' isn't.
 - 'Object' is from 'dart:core'.
          result.message = serializers.deserialize(value,
                                                   ^
../.pub-cache/hosted/pub.dartlang.org/build_daemon-3.0.0/lib/data/shutdown_notification.g.dart:55:56: Error: The argument type 'Object?' can't be assigned to the parameter type 'Object' because 'Object?' is nullable and 'Object' isn't.
 - 'Object' is from 'dart:core'.
          result.failureType = serializers.deserialize(value,
                                                       ^
../.pub-cache/hosted/pub.dartlang.org/analyzer-1.5.0/lib/src/error/best_practices_verifier.dart:1978:14: Error: A non-null value must be returned since the return type 'String' doesn't allow null.
  String get displayString {
             ^
pub finished with exit code 1
```

</details>

I have the feeling this might be a version issue - I have tried to change `build_runner` versions and similar, but I have not had any success yet.  

## Debugging

I am having a really hard time debugging this since all of our code is perfectly fine but the `build_runner` crashes right away, so I am not sure where to start.

I am also not sure what exactly caused the regression. Some notable changes since the last working build:

```
dart: "2.14.0-136.0.dev"  ->   dart: "2.14.0-188.0.dev"
build_runner: 1.12.2  ->   build_runner: 2.0.4
```

But from what I can tell, there is nothing in the project that would make it incompatible with the latest version of build runner.

### Dart SDK

```
Tools • Dart 2.14.0 (build 2.14.0-188.0.dev)
Flutter 2.3.0-24.0.pre • channel dev • https://github.com/flutter/flutter.git
Framework • revision 2b9537c783 (6 days ago) • 2021-06-11 22:11:53 -0700
Engine • revision ddbac024d1
```

### Packages

These are the revelant package versions taken from the Pubspec lock file:

```
build_runner: 1.12.2
freezed: 0.14.1+2
json_serializable: 4.1.1
mockito: 5.0.5
```

We are not using any other _direct_ dependencies, all other dependencies are transitive. There is at least one `@freezed` annotated class that also uses `json_serializable` and at least one `GenerateMocks`. However, I think the actual classes are not relevant as the code generation fails instantly.

### OS

This happens on both Windows and macOS.

**Comment by jakemac53** [comment] 2021-06-18 16:14
Duplicate of https://github.com/dart-lang/build/issues/3104, you will need to update to `built_value` version 8.0.1 or higher

**Closed by jakemac53** 2021-06-18 16:14 UTC
