### ISSUE TITLE
build_runner fails on Windows with dependencies using git and path

### ISSUE THREAD

**Issue by technolion** [dart-lang/build#3137] opened 2021-06-28 17:33 UTC
When using a dependency like this:

```
  menubar:
    git:
      url: https://github.com/google/flutter-desktop-embedding.git
      path: plugins/menubar
```

build_runner fails parsing the path correctly **on Windows**:

```
dart run build_runner build
Could not find a file named "pubspec.yaml" in "C:\Users\tom\AppData\Local\Pub\Cache\git\flutter-desktop-embedding-e48abe7c3e9ebfe0b81622167c5201d4e783bb81\plugins%5Cmenubar".
```

As one can see from the error, it looks like the `path` parameter of the `git` dependency leads to an encoded backslash (%5C) which somehow messes up build_runner.

The above way to add a dependency via git is an officially supported syntax:
https://dart.dev/tools/pub/dependencies

* Dart SDK version: 2.14.0-188.5.beta (beta) (Thu Jun 24 15:29:20 2021 +0200) on "windows_x64"
* build_runner version 2.0.5
* Windows 10 operating system

**Comment by technolion** [comment] 2021-06-30 07:33
Sure:

```
{
  "configVersion": 2,
  "packages": [
    {
      "name": "async",
      "rootUri": "file:///C:/Users/tom/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/async-2.7.0",
      "packageUri": "lib/",
      "languageVersion": "2.12"
    },
    {
      "name": "boolean_selector",
      "rootUri": "file:///C:/Users/tom/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/boolean_selector-2.1.0",
      "packageUri": "lib/",
      "languageVersion": "2.12"
    },
    {
      "name": "characters",
      "rootUri": "file:///C:/Users/tom/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/characters-1.1.0",
      "packageUri": "lib/",
      "languageVersion": "2.12"
    },
    {
      "name": "charcode",
      "rootUri": "file:///C:/Users/tom/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/charcode-1.2.0",
      "packageUri": "lib/",
      "languageVersion": "2.12"
    },
    {
      "name": "clock",
      "rootUri": "file:///C:/Users/tom/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/clock-1.1.0",
      "packageUri": "lib/",
      "languageVersion": "2.12"
    },
    {
      "name": "collection",
      "rootUri": "file:///C:/Users/tom/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/collection-1.15.0",
      "packageUri": "lib/",
      "languageVersion": "2.12"
    },
    {
      "name": "cupertino_icons",
      "rootUri": "file:///C:/Users/tom/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/cupertino_icons-1.0.3",
      "packageUri": "lib/",
      "languageVersion": "2.12"
    },
    {
      "name": "fake_async",
      "rootUri": "file:///C:/Users/tom/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/fake_async-1.2.0",
      "packageUri": "lib/",
      "languageVersion": "2.12"
    },
    {
      "name": "flutter",
      "rootUri": "file:///C:/Users/tom/Development/flutter/packages/flutter",
      "packageUri": "lib/",
      "languageVersion": "2.12"
    },
    {
      "name": "flutter_lints",
      "rootUri": "file:///C:/Users/tom/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/flutter_lints-1.0.3",
      "packageUri": "lib/",
      "languageVersion": "2.12"
    },
    {
      "name": "flutter_test",
      "rootUri": "file:///C:/Users/tom/Development/flutter/packages/flutter_test",
      "packageUri": "lib/",
      "languageVersion": "2.12"
    },
    {
      "name": "lints",
      "rootUri": "file:///C:/Users/tom/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/lints-1.0.1",
      "packageUri": "lib/",
      "languageVersion": "2.12"
    },
    {
      "name": "matcher",
      "rootUri": "file:///C:/Users/tom/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/matcher-0.12.10",
      "packageUri": "lib/",
      "languageVersion": "2.12"
    },
    {
      "name": "menubar",
      "rootUri": "file:///C:/Users/tom/AppData/Local/Pub/Cache/git/flutter-desktop-embedding-e48abe7c3e9ebfe0b81622167c5201d4e783bb81/plugins/menubar",
      "packageUri": "lib/",
      "languageVersion": "2.12"
    },
    {
      "name": "meta",
      "rootUri": "file:///C:/Users/tom/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/meta-1.4.0",
      "packageUri": "lib/",
      "languageVersion": "2.12"
    },
    {
      "name": "path",
      "rootUri": "file:///C:/Users/tom/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/path-1.8.0",
      "packageUri": "lib/",
      "languageVersion": "2.12"
    },
    {
      "name": "sky_engine",
      "rootUri": "file:///C:/Users/tom/Development/flutter/bin/cache/pkg/sky_engine",
      "packageUri": "lib/",
      "languageVersion": "2.12"
    },
    {
      "name": "source_span",
      "rootUri": "file:///C:/Users/tom/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/source_span-1.8.1",
      "packageUri": "lib/",
      "languageVersion": "2.12"
    },
    {
      "name": "stack_trace",
      "rootUri": "file:///C:/Users/tom/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/stack_trace-1.10.0",
      "packageUri": "lib/",
      "languageVersion": "2.12"
    },
    {
      "name": "stream_channel",
      "rootUri": "file:///C:/Users/tom/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/stream_channel-2.1.0",
      "packageUri": "lib/",
      "languageVersion": "2.12"
    },
    {
      "name": "string_scanner",
      "rootUri": "file:///C:/Users/tom/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/string_scanner-1.1.0",
      "packageUri": "lib/",
      "languageVersion": "2.12"
    },
    {
      "name": "term_glyph",
      "rootUri": "file:///C:/Users/tom/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/term_glyph-1.2.0",
      "packageUri": "lib/",
      "languageVersion": "2.12"
    },
    {
      "name": "test_api",
      "rootUri": "file:///C:/Users/tom/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/test_api-0.4.0",
      "packageUri": "lib/",
      "languageVersion": "2.12"
    },
    {
      "name": "typed_data",
      "rootUri": "file:///C:/Users/tom/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/typed_data-1.3.0",
      "packageUri": "lib/",
      "languageVersion": "2.12"
    },
    {
      "name": "vector_math",
      "rootUri": "file:///C:/Users/tom/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/vector_math-2.1.0",
      "packageUri": "lib/",
      "languageVersion": "2.12"
    },
    {
      "name": "build_runner_test",
      "rootUri": "../",
      "packageUri": "lib/",
      "languageVersion": "2.12"
    }
  ],
  "generated": "2021-06-28T16:52:30.635680Z",
  "generator": "pub",
  "generatorVersion": "2.14.0-188.5.beta"
}
```

The package is correctly installed in that directory:
![Bildschirmfoto 2021-06-30 um 09 32 10](https://user-images.githubusercontent.com/1611505/123920371-2a181b00-d986-11eb-97f1-8cda8d9227f2.png)

**Comment by jakemac53** [comment] 2021-06-30 14:42
Interesting... the package config looks fine.

**Comment by technolion** [comment] 2021-06-30 14:54
Maybe another relevant piece of information is that I discovered this with a flutter project on Flutter's beta channel.

**Comment by technolion** [comment] 2021-06-30 16:08
I just switched to Flutter's  `stable` branch and can confirm, that the error does **not** appear!
Do you have an idea, what the cause can be?

**Comment by jakemac53** [comment] 2021-06-30 16:10
I do not yet, no. I haven't had a chance to dive into this but I will try and take a look in a bit.

**Comment by jakemac53** [comment] 2021-06-30 16:14
As far as I can tell though this is where we create the path https://github.com/dart-lang/build/blob/d8ffc57f19090e23c4e51ddaf1c9b7429db0aa82/build_runner_core/lib/src/package_graph/package_graph.dart#L92.

If you wanted to you could try some local debugging to see how the path looks at that point (check `package.root` and `package.root.toFilePath()` to see how they look).

You can see some initial help on how to debug the build script here https://github.com/dart-lang/build/blob/master/docs/builder_author_faq.md#how-can-i-debug-my-builder although the actual debugging part is IDE specific. I can give an example vscode config if you would like.

**Comment by technolion** [comment] 2021-06-30 16:27
Thank you. I will try to debug it tomorrow. The vscode example config would definitely be of help, as I use this IDE.

**Comment by jakemac53** [comment] 2021-06-30 16:37
```json
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "build script",
            "program": ".dart_tool/build/entrypoint/build.dart",
            "request": "launch",
            "type": "dart",
            // "cwd": "Set this to your package subdir if not the root",  
            "args": [
                "build",
                "--delete-conflicting-outputs"
            ]
        }
    ]
}
```

**Comment by jakemac53** [comment] 2021-08-03 16:52
It looks like this is now a duplicate of https://github.com/dart-lang/pub/issues/3012 where the underlying issue is being tracked, going to go ahead and close this one.

**Closed by jakemac53** 2021-08-03 16:52 UTC

**Comment by enloc-port** [comment] 2022-06-30 08:44
In my case, the reason for this problem was that I used to pull the packges using `flutter pub get`, but I ran build_runner with `dart run build_runner ...`, which both use different working directories.

So be sure to run build_runner with the same command as the one you pulled the packages with.
