### ISSUE TITLE
The Installing pub page says "dependencies", instead of "dev_dependencies"

### ISSUE THREAD

**Issue by feinstein** [dart-lang/build#2079] opened 2019-03-11 22:04 UTC
The build_runner "installing" [page](https://pub.dartlang.org/packages/build_runner#-installing-tab-) has the following instruction:

>1. Depend on it
>
>Add this to your package's pubspec.yaml file:
>
>dependencies:
>   build_runner: ^1.2.8

While it should be a `dev_dependencies` instead.

**Comment by natebosch** [comment] 2019-03-14 00:29
Good idea!

This isn't something we can control from any of the code in this repo. Closing as a duplicate of https://github.com/dart-lang/pub-dartlang-dart/issues/2125

Once there is some supported way of indicating that a package is generally a dev dependency we'll definitely update this to use it.

**Closed by natebosch** 2019-03-14 00:29 UTC

**Comment by feinstein** [comment] 2019-03-14 00:31
Thanks Nate!
