### ISSUE TITLE
Add a `force rebuild all` flag to build_runner

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/build#314] opened 2017-07-27 05:19 UTC
Shouldn't be needed – but sometimes it is.

Better than deleting the `.dart_tool` directory.

**Comment by natebosch** [comment] 2017-09-13 20:22
Can also `touch tool/build.dart` - is that sufficient for you?

**Comment by zoechi** [comment] 2017-09-14 06:53
Should changing any file imported by `tool/build.dart` (like `tool/my_generator.dart`) also cause generated files to be regenerated. This doesn't seem to work for me.

**Comment by natebosch** [comment] 2017-09-14 07:11
@zoechi do you mean during a `watch`? That was changed in https://github.com/dart-lang/build/pull/422 - but it wouldn't have rebuilt files, just killed the watch.

If you mean during separate runs then yes we expect that to work. It should have a prompt to delete existing outputs and then rebuild everything. Is that not working?

**Comment by zoechi** [comment] 2017-09-14 07:28
@natebosch recently I was working on a generator and had to delete the generated file every time before running `dart tool/build.dart` to get the generated file updated.
I didn't know what the current expected behavior would be. 
I'll check again create a bug report.

**Comment by matanlurey** [comment] 2017-12-24 06:15
Closing because I haven't seen any particular issues that needed this in a while.

If users are needing to delete the `.dart_tool` folder we should get bug reports before deciding on needing to add a "clean" type function, which is ~trivial.

**Closed** 2017-12-24 06:15 UTC
Labels: package:build_runner
