### ISSUE TITLE
Localhost Not Found (404)

### ISSUE THREAD

**Issue by Cododoc** [dart-lang/build#1088] opened 2018-03-05 15:23 UTC
Hello!
I run serve command like this:
`pub run build_runner serve webDev`

Then a have erroe on localhost:8080:
Not Found
```
Request URL:http://localhost:8080/
Request Method:GET
Status Code:404 Not Found
```

If run serve without params all works fine.
`pub run build_runner serve`

OS: Windwos.
Dart: Dart VM version: 2.0.0-dev.30.0 (Thu Feb 22 14:08:47 2018 +0100) on "windows_x64"
angular-5.0.0-alpha+6

**Comment by jakemac53** [comment] 2018-03-05 16:09
`pub run build_runner serve webDev` would serve the `webDev` directory on port 8080 - just to confirm do you have a webDev dir?

**Comment by Cododoc** [comment] 2018-03-05 18:38
Yes, of course. I have 2 web folders. For production and development.

**Comment by jakemac53** [comment] 2018-03-05 19:00
Oh, the issue here is going to be that you are using a non-standard directory (which is fine, but will require some config on your part). Basically, we have a whitelist of directories that we include as sources by default so we don't pick up output directories or editor specific directories etc.

You can fix this with a build.yaml, something like this:

```
targets:
  $default:
    sources:
      - lib/**
      - web/**
      - webDev/**
```

**Comment by jakemac53** [comment] 2018-03-05 19:01
closing as I assume this will fix the issue, please re-open if you are still having issues

**Closed by jakemac53** 2018-03-05 19:01 UTC
Labels: Resolution: works as intended

**Comment by natebosch** [comment] 2018-03-05 19:04
I think we can identify situations like this and print something more helpful. Filed #1091 to track.

**Comment by Cododoc** [comment] 2018-03-06 07:31
@jakemac53 I tried run serve with build.yaml file. Something changed but it doesn't work.

Now it can find index.html:
```
Request URL:http://localhost:8080/
Request Method:GET
Status Code:200 OK
```

But it can't find main.dart.js:
```
Request URL:http://localhost:8080/main.dart.js
Request Method:GET
Status Code:404 Not Found
```

**Comment by Cododoc** [comment] 2018-03-06 08:14
It look like we need set entrypoint in build.yaml:
```
targets:
  $default:
    sources:
      - lib/**
      - web/**
      - webDev/**
    builders:
      build_web_compilers|entrypoint:
        generate_for:
        - webDev/**.dart
```

After that changes all work fine.

**Comment by hpoit** [comment] 2019-06-21 13:59
Hi @jakemac53! I have a similar issue I've been trying to solve for the past two days:
![image](https://user-images.githubusercontent.com/3711100/59927639-57cf3e80-9413-11e9-840e-d9234013c603.png)
I've installed Dart's SDK (not from Flutter), and also have added some paths to `.bash_profile`:
![image](https://user-images.githubusercontent.com/3711100/59927757-8d742780-9413-11e9-82de-597440e64e34.png)
Need help please!

**Comment by hpoit** [comment] 2019-06-21 14:03
When I run `flutter pub global activate webdev`, I get:
![image](https://user-images.githubusercontent.com/3711100/59927996-21de8a00-9414-11e9-83a0-9f552e2ac593.png)

**Comment by jakemac53** [comment] 2019-06-21 14:03
@hpoit generally the path you load in the browser should be relative to your `web` directory, but it looks like in your case it is loading two directories above that. You could just have the wrong path in your script tag, or something else could be going on I don't really have enough information here.

If you can please open up a new issue and post a reproduction case.

**Comment by jakemac53** [comment] 2019-06-21 14:04
(this does not look like the same issue as above)
