### ISSUE TITLE
Dart 3.0.2 project build_runner running in Dart 2 mode

### ISSUE THREAD

**Issue by JCKodel** [dart-lang/build#3525] opened 2023-06-02 20:29 UTC
Dart SDK 3.0.2
build_runner 2.4.4
isar_generator 3.1.0+1
Windows 11

1. Create a Flutter 3.10.2 project
2. Use some Dart 3.0 feature (such as `final class`)
3. Add those dependencies: isar 3.1.0+1, isar_flutter_libs 3.1.0+1
4. Add those dev dependencies: build_runner 2.4.4, custom_lint 0.2.12, equatable_lint 0.2.1, isar_generator 3.1.0
5. Create an Isar collection such as this:
```dart
import 'package:isar/isar.dart';

part "test.g.dart";

abstract class BaseEntity {
  BaseEntity({
    this.id,
    required this.creationDate,
    required this.updateDate,
    required this.synced,
    required this.deleted,
  });

  DateTime creationDate;
  @Index()
  bool deleted;

  @Index()
  bool synced;

  @Index()
  DateTime updateDate;

  Id? id;
}

@Collection(accessor: "users")
final class User extends BaseEntity {
  User({
    super.id,
    required super.creationDate,
    required super.updateDate,
    required super.synced,
    required super.deleted,
    required this.userId,
    required this.displayName,
    required this.email,
    required this.photoURL,
  });

  @Index(unique: true)
  String userId;

  String displayName;

  String email;

  String photoURL;
}
```
6. run `dart run build_runner build`

The output is saying some Dart 3 features are not recognized (it seems is somehow running it on Dart 2):

```console
[INFO] Generating build script completed, took 157ms
[INFO] Reading cached asset graph completed, took 39ms
[INFO] Checking for updates since last build completed, took 436ms
[SEVERE] isar_generator on lib/test.dart:

This builder requires Dart inputs without syntax errors.
However, package:XXX/test.dart (or an existing part) contains the following errors.
test.dart:28:1: Can't have modifier 'final' here.

Try fixing the errors and re-running the build.

[INFO] Running build completed, took 138ms
[INFO] Caching finalized dependency graph completed, took 18ms
[SEVERE] isar_generator on lib/main.dart (cached):

This builder requires Dart inputs without syntax errors.
However, package:XXX/main.dart (or an existing part) contains the following errors.
main.dart:7:1: Can't have modifier 'final' here.
main.dart:57:1: Can't have modifier 'final' here.

Try fixing the errors and re-running the build.

[SEVERE] Failed after 167ms
```

7. Now override the dependency of equatable_lint to grab the code from my fork: git@github.com:JCKodel/equatable_lint.git and update the dependency of custom_lint to 0.4.0 (my fork only upgrades the dependency of custom_lint_builder to 0.4.0)
8. Run `dart run build_runner build` again
9. Done! Everything works fine!

(Insert Jackie Chan WHY meme here)
```

**Comment by jakemac53** [comment] 2023-06-05 14:50
@JCKodel this sounds like you are stuck on an older version of `analyzer`. You need to be on a version of analyzer that supports the features you are trying to use. In particular, you need [analyzer 5.8.0](https://pub.dev/packages/analyzer/changelog#580).

I can't help much more beyond that with the information I have, but if you add `analyzer: ^5.8.0` to your dev_dependencies in  your pubspec.yaml, it should fail to solve, and the message should help you figure out why you can't get that version. If you can't understand that message (they can be quite wordy), you can paste it here and I can help you decipher it.

**Comment by JCKodel** [comment] 2023-06-05 16:17
> @JCKodel this sounds like you are stuck on an older version of `analyzer`. You need to be on a version of analyzer that supports the features you are trying to use. In particular, you need [analyzer 5.8.0](https://pub.dev/packages/analyzer/changelog#580).
> 

This fixes nothing!

First, I don't even have analyzer 5.8.0 on my pubspec.yaml. A new project shouldn't require it (especially without any information at all about the issue).

The libs that triggers this issue don't work with analyzer 5.8.0, so I have to update them.

If I update them, I don't need analyzer (any version), so... adding analyzer it is useless.

The problem is: a brand new project using latest SDKs with `Dart 3 Compatible` badges simply doesn't work!

**Comment by jakemac53** [comment] 2023-06-05 16:48
> This fixes nothing!

It isn't intended to - it is just to help diagnose why you _can't_ get that version.

> First, I don't even have analyzer on my pubspec.yaml. A new project shouldn't require it (especially without any information at all about the issue).

Your dependencies do use it, and you do need to be on the latest version in order to use the latest features.

It has long been my opinion that the analyzer package fundamentally uses semver wrong, as it claims support for future SDKs which it knowingly won't be able to support, but this isn't something I have been able to convince them of, hence issues such as this.

> The libs that triggers this issue don't work with analyzer 5.8.0, so I have to update them.

Yes, you should file issues on those libraries in order to get them to update to the latest analyzer. This simply must happen, there is no way around it.

> If I update them, I don't need analyzer (any version), so... adding analyzer is useless.

Again, it's only there to help discover which libs need to be updated to allow it. If you already know which ones those are, then file issues (or send prs) on those packages to get them to update.

> The problem is: a brand new project using latest SDKs with Dart 3 Compatible badges simply doesn't work!

This is an issue with the packages you depend on, and Dart or this package. Older versions of analyzer were written prior to records etc existing. To support them, you must update analyzer, full stop. It is not reasonable to expect anything otherwise.

I am going to close this issue, as the issue is related to your dependencies updating.

**Closed by jakemac53** 2023-06-05 16:48 UTC
Labels: needs-info

**Comment by JCKodel** [comment] 2023-06-05 16:59
@jakemac53 Ok.

A simple fix would then be to remove the `Dart 3 compatible` from pub.dev and replace it with `Dart (latest Dart version supported by analyzer here) compatible`, but, then again, pub.dev said, basically, it is not an issue so, nothing will change =\

**Comment by jakemac53** [comment] 2023-06-05 17:07
Analyzer always has a version that is compatible with the latest SDK. But your deps won't necessarily always allow it.

This package, always supports the latest analyzer as well, because it is well maintained.

We can't promise anything about any other packages you depend on though, you have to go to them to ensure they keep up to date.

**Comment by jakemac53** [comment] 2023-06-05 17:08
Locking as this conversation isn't trending in a productive direction.
