### ISSUE TITLE
You have hit a bug in build_runner

### ISSUE THREAD

**Issue by crdornelles** [dart-lang/build#2532] opened 2019-11-05 02:31 UTC
I'm trying to generate the *g.dart files with pakages: build_runner: ^1.7.1 and json_serializable: ^3.2.3

λ flutter --version
Flutter 1.10.7 • channel beta • https://github.com/flutter/flutter.git
Framework • revision e70236e36c (5 weeks ago) • 2019-10-02 09:32:30 -0700
Engine • revision 9e6314d348
Tools • Dart 2.6.0 (build 2.6.0-dev.4.0 1103600280)
---
λ flutter packages pub run build_runner build --delete-conflicting-outputs
[INFO] Generating build script...
[INFO] Generating build script completed, took 267ms

[WARNING] Deleted previous snapshot due to missing asset graph.
[INFO] Creating build script snapshot......
[INFO] Creating build script snapshot... completed, took 19.2s

[INFO] Initializing inputs
[INFO] Building new asset graph...
[INFO] Building new asset graph completed, took 1.5s

[INFO] Checking for unexpected pre-existing outputs....
[INFO] Checking for unexpected pre-existing outputs. completed, took 2ms

[INFO] Running build...

You have hit a bug in build_runner
Please file an issue with reproduction steps at https://github.com/dart-lang/build/issues

NoSuchMethodError: The getter 'futureDynamicType' was called on null.
Receiver: null
Tried calling: futureDynamicType
dart:core                                                         Object.noSuchMethod
package:analyzer/src/dart/element/element.dart 7625:40            LibraryElementImpl.createLoadLibraryFunctionForLibrarypackage:analyzer/src/dart/element/element.dart 7475:9             LibraryElementImpl.createLoadLibraryFunction
package:analyzer/src/summary/resynthesize.dart 363:24             SummaryResynthesizer.getLibraryElement.<fn>
dart:collection                                                   _LinkedHashMapMixin.putIfAbsent
package:analyzer/src/summary/resynthesize.dart 351:36             SummaryResynthesizer.getLibraryElement
package:analyzer/src/summary/resynthesize.dart 414:20             SummaryResynthesizer._buildTypeProvider
package:analyzer/src/summary/resynthesize.dart 202:5              new SummaryResynthesizer
package:analyzer/src/summary/package_bundle_reader.dart 162:9     new StoreBasedSummaryResynthesizer
package:analyzer/src/dart/analysis/library_context.dart 100:27    new LibraryContext
package:analyzer/src/dart/analysis/driver.dart 1439:29            AnalysisDriver._createLibraryContext
package:analyzer/src/dart/analysis/driver.dart 1380:28            AnalysisDriver._computeUnitElement.<fn>
package:analyzer/src/dart/analysis/performance_logger.dart 34:15  PerformanceLog.run
package:analyzer/src/dart/analysis/driver.dart 1378:20            AnalysisDriver._computeUnitElement
package:analyzer/src/dart/analysis/driver.dart 997:34             AnalysisDriver.performWork
package:analyzer/src/dart/analysis/driver.dart 1931:24            AnalysisDriverScheduler._run
package:analyzer/src/dart/analysis/driver.dart 1865:5             AnalysisDriverScheduler.start
package:build_resolvers/src/analysis_driver.dart 54:13            analysisDriver
package:build_resolvers/src/resolver.dart 138:18                  new AnalyzerResolvers
package:build_runner_core/src/generate/options.dart 192:19        BuildOptions.create
package:build_runner/src/generate/build.dart 85:36                build
package:build_runner/src/entrypoint/build.dart 28:24              BuildCommand.run
package:args/command_runner.dart 197:27                           CommandRunner.runCommand
package:args/command_runner.dart 112:25                           CommandRunner.run.<fn>
dart:async                                                        new Future.sync
package:args/command_runner.dart 112:14                           CommandRunner.run
package:build_runner/src/entrypoint/run.dart 24:31                run
.dart_tool\build\entrypoint\build.dart 26:22                      main

pub finished with exit code 1

**Comment by jakemac53** [comment] 2019-11-06 15:58
Duplicate of https://github.com/dart-lang/build/issues/2502 - tldr; you need to upgrade your dependencies using `pub upgrade` or `flutter pub upgrade`.

**Closed by jakemac53** 2019-11-06 15:58 UTC
