### ISSUE TITLE
NoSuchMethodError: The getter 'lastKnownDigest' was called on null.

### ISSUE THREAD

**Issue by gaurav440** [dart-lang/build#1914] opened 2018-12-05 01:32 UTC
*Dart SDK Version [ 2.1.0] 
*build_runner 1.1.2

I am new to dart web development . I have created starter app and build and served it successfully . But the moment I add the dependency firebase I got my build failed Below is the error

`Creating build script, took 6540ms
[INFO] Initializing inputs
[INFO] Reading cached asset graph...
[WARNING] Throwing away cached asset graph because the build phases have changed. This most commonly would happen as a result of adding a new dependency or updating your dependencies.
[INFO] Cleaning up outputs from previous builds....
[INFO] Cleaning up outputs from previous builds. completed, took 130ms

[INFO] Reading cached asset graph completed, took 1.1s

[INFO] Checking for updates since last build...

You have hit a bug in build_runner
Please file an issue with reproduction steps at https://github.com/dart-lang/build/issues

NoSuchMethodError: The getter 'lastKnownDigest' was called on null.
Receiver: null
Tried calling: lastKnownDigest
dart:core                                                            Object.noSuchMethod
package:build_runner_core/src/generate/build_definition.dart 377:42  _Loader._computeBuilderOptionsUpdates.updateBuilderOptionsNode
package:build_runner_core/src/generate/build_definition.dart 387:33  _Loader._computeBuilderOptionsUpdates
package:build_runner_core/src/generate/build_definition.dart 290:20  _Loader._updateAssetGraph
package:build_runner_core/src/generate/build_definition.dart 89:17   _Loader.prepareWorkspace.<fn>
package:build_runner_core/src/logging/logging.dart 25:30             logTimedAsync
package:build_runner_core/src/generate/build_definition.dart 86:27   _Loader.prepareWorkspace
package:build_runner_core/src/generate/build_definition.dart 64:50   BuildDefinition.prepareWorkspace
package:build_runner_core/src/generate/build_impl.dart 105:49        BuildImpl.create
package:build_runner_core/src/generate/build_runner.dart 31:37       BuildRunner.create
package:build_runner/src/generate/build.dart 105:35                  build
package:build_runner/src/entrypoint/build.dart 28:24                 BuildCommand.run
package:args/command_runner.dart 196:27                              CommandRunner.runCommand
package:args/command_runner.dart 111:29                              CommandRunner.run.<fn>
dart:async                                                           new Future.sync
package:args/command_runner.dart 111:11                              CommandRunner.run
package:build_runner/src/entrypoint/run.dart 23:31                   run
.dart_tool/build/entrypoint/build.dart 133:22                        main`

Below is the pubsec.yaml file

`name: web_mytown
description: A web app that uses AngularDart Components
# version: 1.0.0
# homepage: https://www.example.com
# author: gaurav <email@example.com>

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  angular: ^5.1.0
  angular_components: ^0.10.1
  firebase: ^5.0.2
  #rxdart: ^0.19.0

dev_dependencies:
  angular_test: ^2.1.0
  build_runner: ^1.1.2
  build_test: ^0.10.3
  build_web_compilers: ^0.4.4
  test: ^1.5.1
`
Later I realised that the issue is not specific to firebase ,any dependency I add the build failed  such as rxDart

**Comment by gaurav440** [comment] 2018-12-05 01:37
I  Even tried to downgrade build runner to version 1.0.0 then also it was not working

**Comment by jakemac53** [comment] 2018-12-05 14:31
Duplicate of https://github.com/dart-lang/build/issues/1914

**Closed by jakemac53** 2018-12-05 14:31 UTC
