### ISSUE TITLE
Time cost too long! How can i exclude package: meta/**.dart?

### ISSUE THREAD

**Issue by AbeiOS** [dart-lang/build#3246] opened 2022-02-16 13:21 UTC
* Dart SDK version: 2.15.1 (stable) (Tue Dec 14 13:32:21 2021 +0100) on "macos_x64"
* build_runner:2.1.7
* MacOSX

thank you provide this lib，and how to exclude package:any?

**Comment by jakemac53** [comment] 2022-02-16 15:22
What do you mean by exclude? What is the use case?

**Comment by AbeiOS** [comment] 2022-02-17 05:49
when i run `flutter pub run build_runner build`, scanner will work on system package like  those
<img width="418" alt="截屏2022-02-17 下午1 48 20" src="https://user-images.githubusercontent.com/12441461/154413637-2dd89e03-3e88-4e30-b4be-1c2b8e551f50.png">

**Comment by jakemac53** [comment] 2022-02-17 15:19
Excluding the code of some of your dependencies is likely to cause problems (files won't analyze properly). It likely is not the cause of slowness in any case.

Generally slow builds are caused by a builder running on all sources, and analyzing them. Individual packages can configure what files a builder runs on in that package, using the `generate_for` configuration, see the docs here https://github.com/dart-lang/build/blob/master/docs/faq.md#how-do-i-avoid-running-builders-on-unnecessary-inputs.

**Comment by AbeiOS** [comment] 2022-02-18 08:01
> packages

thank you for you reply!

**Comment by jakemac53** [comment] 2022-02-23 16:40
I am going to close this issue for now, I don't think there is any action for us to take, but feel free to comment if you have some outstanding questions.

**Closed by jakemac53** 2022-02-23 16:40 UTC
Labels: type: question

**Comment by AbeiOS** [comment] 2022-03-12 05:55
> I am going to close this issue for now, I don't think there is any action for us to take, but feel free to comment if you have some outstanding questions.

3q

**Comment by AbeiOS** [comment] 2022-03-12 07:24
> Excluding the code of some of your dependencies is likely to cause problems (files won't analyze properly). It likely is not the cause of slowness in any case.
> 
> Generally slow builds are caused by a builder running on all sources, and analyzing them. Individual packages can configure what files a builder runs on in that package, using the `generate_for` configuration, see the docs here https://github.com/dart-lang/build/blob/master/docs/faq.md#how-do-i-avoid-running-builders-on-unnecessary-inputs.

First of all, thank you for your reply. but build_for just support local project files. and how can I build for some package: meta or package: flutter?
