### ISSUE TITLE
A comparison expression can't be an operand of another comparison expression.

### ISSUE THREAD

**Issue by yashanghan22** [dart-lang/build#3723] opened 2024-06-29 04:52 UTC
can be nullable marking showing error as comparison expression.

my list of objects are nullable list so that it is throwing error while generating error after g dart file generation and after generated file i have to fix this by removing question mark manually and then it wil be fixed.

so issue is that every time i have to manually fix this so is this error from package side or my side my class is shown below which is getting error.

-------info----------

- Dart SDK Version -`3.4.3`
- Fllutter version- `3.22.2`
- Build_runner- `2.4.11`
- plarform- `windows-10`
- target_platform- `windows desktop application`

### package issue in terminal:
![image](https://github.com/dart-lang/build/assets/53462202/8ef5571b-619f-4e7d-9726-af0179b98a98)

```
[SEVERE] objectbox_generator:generator on lib/$lib$:

Could not format because the source could not be parsed:

line 1521, column 45 of .: A comparison expression can't be an operand of another comparison expression.
     ╷
1521 │ final partyListParam = obx.ToMany<PartyModel>?();
     │                                             ^
     ╵
line 1521, column 46 of .: Expected an identifier.
     ╷
1521 │ final partyListParam = obx.ToMany<PartyModel>?();
     │                                              ^
     ╵
line 1521, column 49 of .: Expected to find ':'.
     ╷
1521 │ final partyListParam = obx.ToMany<PartyModel>?();
     │                                                 ^
     ╵
line 1521, column 49 of .: Expected an identifier.
     ╷
1521 │ final partyListParam = obx.ToMany<PartyModel>?();
     │                                                 ^
     ╵
line 1522, column 49 of .: A comparison expression can't be an operand of another comparison expression.
     ╷
1522 │ final challanListParam = obx.ToMany<ChallanModel>?();
     │                                                 ^
     ╵
line 1522, column 50 of .: Expected an identifier.
     ╷
1522 │ final challanListParam = obx.ToMany<ChallanModel>?();
     │                                                  ^
     ╵
line 1522, column 53 of .: Expected to find ':'.
     ╷
1522 │ final challanListParam = obx.ToMany<ChallanModel>?();
     │                                                     ^
     ╵
line 1522, column 53 of .: Expected an identifier.
     ╷
1522 │ final challanListParam = obx.ToMany<ChallanModel>?();
     │                                                     ^
     ╵
line 1523, column 49 of .: A comparison expression can't be an operand of another comparison expression.
     ╷
1523 │ final qualityListParam = obx.ToMany<QaulityModel>?();
     │                                                 ^
     ╵
line 1523, column 50 of .: Expected an identifier.
     ╷
1523 │ final qualityListParam = obx.ToMany<QaulityModel>?();
     │                                                  ^
     ╵
(22 more errors...)
[INFO] Running build completed, took 519ms
[INFO] Caching finalized dependency graph completed, took 180ms
[SEVERE] Failed after 708ms
```

### Issue containing code part:
```
@Entity()
class BillingsState extends Equatable {
  BillingsState({
    this.id = 0,
    required this.firmDetail,
    this.challanNo = 1,
    this.salesNo = 1,
    this.salesReturnNo = 1,
    this.salesPurchaseNo = 1,
    this.creditNoteNo = 1,
    this.debitNoteNo = 1,
    //  this.partyList=ToMany(),
    ToMany<PartyModel>? partyList,
    ToMany<ChallanModel>? challanList,
    ToMany<QaulityModel>? qualityList,
    ToMany<SalesModel>? salesList,
    ToMany<SalesReturnModel>? salesRetrunList,
    ToMany<SalesPurchaseReturnModel>? salesPurchaseList,
    ToMany<CreditDebitNoteModel>? creditNoteList,
    ToMany<CreditDebitNoteModel>? debitNoteList,
  })  : partyList = partyList ?? ToMany<PartyModel>(),
        challanList = challanList ?? ToMany<ChallanModel>(),
        qualityList = qualityList ?? ToMany<QaulityModel>(),
        salesList = salesList ?? ToMany<SalesModel>(),
        salesRetrunList = salesRetrunList ?? ToMany<SalesReturnModel>(),
        salesPurchaseList =
            salesPurchaseList ?? ToMany<SalesPurchaseReturnModel>(),
        creditNoteList = creditNoteList ?? ToMany<CreditDebitNoteModel>(),
        debitNoteList = debitNoteList ?? ToMany<CreditDebitNoteModel>();
  @Id()
  int id;
  ToOne<FirmModel> firmDetail;
  int challanNo;
  int salesNo;
  int salesReturnNo;
  int salesPurchaseNo;
  int creditNoteNo;
  int debitNoteNo;
  late ToMany<PartyModel> partyList;
  late ToMany<ChallanModel> challanList;
  late ToMany<QaulityModel> qualityList;
  late ToMany<SalesModel> salesList;
  late ToMany<SalesReturnModel> salesRetrunList;
  late ToMany<SalesPurchaseReturnModel> salesPurchaseList;
  late ToMany<CreditDebitNoteModel> creditNoteList;
  late ToMany<CreditDebitNoteModel> debitNoteList;
}
```

**Comment by eernstg** [comment] 2024-07-01 08:33
The source code in your screendump has many syntax errors, for example: `final partyListParam = obx.ToMany<PartyModel>?();`.

> issue is that every time i have to manually fix this so is this error from package side or my side my class is shown below which is getting error.

I'm not quite sure what you are saying here. I assume the screendump shows code that you have written, and hence I'd expect you to fix the syntax errors before you'd start worrying about errors being caused by anything other than your code.

On the other hand, the reference to "manually fix this" could imply that the code is generated, and in that case it would be the code generator which is buggy.

In any case, the initializing expression `obx.ToMany<PartyModel>?()` is a syntax error. The error message about relational expressions are caused by the fact that no grammar rule allows for a `?` in that position, so the `<` and the `>` are forced to be considered as relational operators rather than angle brackets around type arguments. So you're evaluating `a IS-LESS-THAN b IS-GREATER-THAN c` where `a` is `obx.ToMany`, `b` is `PartyModel`, and `c` is a syntax error. You can't do that because `a < b > c` puts two relational operators at the same level, so you'd have to make a choice and make it `(a < b) > c` or `a < (b > c)`, which is exactly what the error message 'A comparison expression can't be an operand of another comparison expression' tells us.

Perhaps your intention is that the `PartyModel` is a type argument, and it should be nullable? That would be `obx.ToMany<PartyModel?>()`.

Or perhaps your intention is that `obx.ToMany` is a method tear-off which is then subject to generic function instantiation (`obx.ToMany<PartyModel>`), and that function is then conditionally invoked? It might seem natural to allow `f?()` to be an invocation of `f` which will shortcut and yield null if `f` is null, but we don't have that syntax (we do have `myArray?[someIndex]`, and we did discuss supporting `f?()`). Anyway, we don't have that syntax because it can easily be done using `call`, which would be `(obx.ToMany<PartyModel>)?.call()`.  But that would give rise to a warning, because `obx.ToMany<PartyModel>` can't be null.

Hope this helps! It is all working as intended, so I'll close the issue.

**Closed by eernstg** 2024-07-01 08:33 UTC
