### ISSUE TITLE
Should we automatically detect syntax errors in `.dart` files?

### ISSUE THREAD

**Issue by natebosch** [dart-lang/build#2624] opened 2020-02-11 22:05 UTC
A builder which has a `.dart` file as a primary input will almost certainly be unable to do anything useful if there are syntax errors (errors that would make `dartfmt` fail, don't need type resolution). Even if it could do something, later parts of the build will almost certainly fail. As builder authors look to harden their behavior around errors to avoid stack traces or confusing errors we should consider handling this case of errors for them since it is universal.

**Comment by natebosch** [comment] 2020-02-11 22:06
cc @jakemac53 @leonsenft @matanlurey @MichaelRFairhurst

**Comment by jakemac53** [comment] 2020-02-11 22:25
I don't think we should be overly opinionated about this. Some sort of opt in behavior would be fine though. But I think we do effectively have a way of getting errors out of a resolver already?

**Comment by natebosch** [comment] 2020-02-11 22:28
> Some sort of opt in behavior would be fine though.

Who should opt in, the builder author or the end user? If we choose the end user it leaves us open to a poor UX and bugs filed against builders where the user should have opted in. If we choose the builder author it feels like complexity in `build_config` for something which we'd expect every builder to want.

> But I think we do effectively have a way of getting errors out of a resolver already?

We don't. We have been trying it for a while but have not been able to nail down the UX because we expect there will almost always be _some_ analysis errors before all the files are generated. We can work on narrowing down that API to something that can surface syntax errors, but it brings us back to the question of if every builder author _should_ first check for syntax errors, why aren't we doing it for them?

**Comment by leonsenft** [comment] 2020-02-11 22:39
Thanks for starting this thread Nate.

I'm not super concerned what the default behavior is so long as we have the capability to bail out of code generation on syntactically invalid inputs.

If we want to make it optional, perhaps we simply add a method you can call on a build step?

```dart
// Fails the build if the inputs contain syntax errors.
buildStep.reportSyntaxErrors();
```

That said, I think doing this automatically would be most helpful, as all code generators would immediately benefit without the need to educate all of their respective developers.

**Comment by jakemac53** [comment] 2020-02-11 22:45
> Who should opt in, the builder author or the end user?

The builder authors should opt in. Or we make it an automatic part of the resolver api or something.

I don't want to add an artificial restriction that builders can only ever operate on valid dart files. That seems overly aggressive to me. This seems like something that should be handled by an external library and not the build system itself.

It also ties the build system to forever having a dependency on some Dart parser - when we want to go in the opposite direction if anything and move the `Resolver` to a separate package entirely.

**Comment by leonsenft** [comment] 2020-02-11 23:15
Is opt out an option? I imagine writing a code generator that is expected to operate on invalid Dart code to be a rare case. I'm fairly confident all of the code generators we run today would benefit from opting in.

**Comment by MichaelRFairhurst** [comment] 2020-02-11 23:32
I agree with opt-out.

Especially from the perspective of the analyzer team, we don't really make any guarantees about how erroneous code will be resolved except that

- invalid programs are reported as invalid
- parse errors are reported as such

So in general, relying on the element model or resolved ast of a unit that contains errors is walking a dangerous ground. Ideally all APIs would change to use extension methods or other techniques in order to have the design not depend at all upon how an incomplete program analyzes.

That said, that's the world we're in. But I think its a healthy line to draw in the sand that builders won't be run for syntactically invalid code, because that is even further into dangerous ground in already weedy territory.

And I'm ok with people opting out of that, too -- if all you're doing is taking source text and transforming it, and for some reason you care about syntactically invalid programs working, you can use the opt out mechanism.

**Comment by jakemac53** [comment] 2020-02-12 15:15
I would be fine with this being an automatic part of the Resolver (with opt out or not). I pretty strongly disagree that it should be a part of the core build system.

That still allows us to remove our dependency on analyzer (or any dart parser) from the core build system while also still satisfying the goals here?

Any code generator that wants to resolve a Dart file would still stop running as soon as they grab a resolver. For source_gen generators this will never even enter the authors code since it grabs a resolver for them much earlier.

**Comment by leonsenft** [comment] 2020-02-12 17:41
Forgive my lack of knowledge, but is the resolver what's responsible to producing the analysis results for a Dart library? That seems like the logical place to put this.

**Comment by jakemac53** [comment] 2020-02-12 17:55
Correct - if you want to resolve a dart file you do `var resolver = await buildStep.resolver`. I propose we simply make that throw with a nice error if there are parse failures specifically.

We also want to move that api completely to the `build_resolvers` package so it would be `Resolver.fromBuildStep(buildStep)` or similar - which allows us to isolate the analyzer to just that package. That is the only reason I am giving pushback - if we don't run the builders at all it means we have to depend on the analyzer from the core build system which doesn't seem right.

**Comment by natebosch** [comment] 2020-02-12 22:35
One concern I have with making it the Resolver APIs that throw, is that it could cause a stack trace which points to the builder and look to users like a bug. Handling it entirely in the build system gives us the best chance at a consistent and helpful output.

**Comment by leonsenft** [comment] 2020-02-14 21:01
@davidmorgan might want to have a say in this.

**Comment by jakemac53** [comment] 2020-02-14 21:09
> One concern I have with making it the Resolver APIs that throw, is that it could cause a stack trace which points to the builder and look to users like a bug. Handling it entirely in the build system gives us the best chance at a consistent and helpful output.

We don't by default log stack traces - it should be simple enough to log a consistent/nice error imo. I don't think the knowledge about the builder that was trying to run is entirely superfluous either. That is the builder in which the error was detected :man_shrugging:.  Maybe the solution for some users is to disable that builder on that file for instance.

**Comment by natebosch** [comment] 2020-02-14 21:24
We might also want to tie this with a feature like https://github.com/dart-lang/build/issues/981 - I'd be more comfortable if we have a notion for a failure caused by the input and not the builder implementation.

We synced offline about my concerns. I feel comfortable with someone implementing an approach where the resolver throws if you grab a library with parse errors.

**Comment by davidmorgan** [comment] 2020-02-17 12:38
More checking sounds good; no strong opinions otherwise. Thanks.

**Comment by leonsenft** [comment] 2020-02-18 22:59
@natebosch So consensus is that the builder throws (and Angular's builder would have to catch that)?

Would package:build log the Dart parse and scanner errors responsible for the thrown exception, or would they ideally by included as data on the thrown exception for the calling builder implementation to handle?

**Comment by jakemac53** [comment] 2020-02-18 23:04
Angular should not catch it (nor should any other builder) unless they want to actually recover somehow and hide it.

The exception itself should have all the relevant information and present it in a reasonable fashion (via its `toString()`). The stack trace will be hidden unless --verbose is passed.

**Comment by leonsenft** [comment] 2020-02-18 23:13
Okay great, that means all builders would benefit from it without having to opt in. Should I take a shot at implementing this then? Is your suggested approached tied to #981?

**Comment by jakemac53** [comment] 2020-02-19 19:04
If you can take a shot at it that would be great. I don't think we have to gate this on https://github.com/dart-lang/build/issues/981 although we could do that as a part of this and we might then treat the error a bit more specially when logging.

**Comment by jakemac53** [comment] 2020-08-07 14:48
Are we still doing anything here or should this issue be closed?

**Comment by leonsenft** [comment] 2020-08-07 16:36
I landed the changes for the google3 resolver - I think at the time when I assigned this I didn't realize the changes would be google3-specific. If you want, you can port them to https://github.com/dart-lang/build/blob/master/build_resolvers/lib/src/resolver.dart, if not this can be closed.

**Comment by jakemac53** [comment] 2020-08-07 16:41
Would angular externally rely on this behavior in our external resolver?

**Comment by leonsenft** [comment] 2020-08-07 16:46
Yes, Angular and any other code generator would benefit from this change.

**Comment by jakemac53** [comment] 2020-08-25 23:02
It looks like internally it was done unconditionally, but only for syntax errors so that it wouldn't trip on expected errors like missing generated parts/symbols.

**Comment by leonsenft** [comment] 2020-08-25 23:42
We've had an uptick in unhandled exceptions caused by the syntax errors being reported through unexpected code paths that go through our builder, so I think we'll be addressing https://github.com/dart-lang/build/issues/981 in the near future. This would give custom builders the ability to "forward" these errors to the enclosing build runner to handle/report them properly as build failures.

As part of this effort it might make sense to just port the syntax error reporting we added to the internal resolver to package:build_resolvers since there's nothing proprietary about it - it just was added to a different implementation.

**Closed** 2020-09-09 18:38 UTC
Labels: package: build_runner_core, type: enhancement
