### ISSUE TITLE
JS interop does not appear to work in tests with build_web_compilers 2.0.0

### ISSUE THREAD

**Issue by corwinsheahan-wf** [dart-lang/build#2266] opened 2019-05-10 19:34 UTC
Hi there!

We recently began upgrading some of our packages to use `build_web_compilers` 2.0.0. Unfortunately, we noticed that tests seemed to have issues calling functions from `react.js`. I was able to create a reduced test case that appears to show that js interop is not working properly in tests with `build_web_compilers` 2.0.0, which you can find [here](https://github.com/corwinsheahan-wf/js_interop_failing). 

In that package, if you switch the deps to use `build_web_compilers` 1.x, the test will pass, but on `build_web_compilers` 2.0.0, the test will fail because it doesn't properly call the js method. I've also verified via using the `--pause-after-load` flag that the `some.js` file can be loaded successfully in the browser via the path specified in the test html. 

This is on Dart 2.3.0. Thanks for the help!

**Comment by jakemac53** [comment] 2019-05-10 19:58
Duplicate of https://github.com/dart-lang/sdk/issues/36912, note that it is cross-module JS-interop that doesn't work (that is, invoking a function marked as `@JS` in another library. You can work around the issue by making the actual `@JS` annotated function be private and making a regular function in the library that delegates to it. Essentially, this:

```dart
@JS()
external _foo();

foo() => _foo();
```

**Comment by jakemac53** [comment] 2019-05-10 20:12
Even though this is a Duplicate I will leave it open for now I think so it is easier to find and we don't get a ton more duplicates :).

**Comment by jakemac53** [comment] 2019-06-05 17:46
Note that the core issue is resolved here, so the next release should have a fix (stable or dev).

**Comment by corwinsheahan-wf** [comment] 2019-06-05 18:09
Thanks @jakemac53!

**Comment by natebosch** [comment] 2019-07-18 21:27
Closing since this should be resolved with the latest SDKs

**Closed by natebosch** 2019-07-18 21:27 UTC
