### ISSUE TITLE
build_runner failing to compile with 0.39.15 analyzer version

### ISSUE THREAD

**Issue by nicemanis** [dart-lang/build#2764] opened 2020-07-28 10:29 UTC
build_runner is throwing the following error:
```
Failed to precompile build_runner:graph_inspector:
../../.pub-cache/hosted/pub.dartlang.org/build_resolvers-1.3.7/lib/src/resolver.dart:343:10: Error: Method not found: 'SummaryBuilder'.
  return SummaryBuilder(sdkSources, sdk.context)
         ^^^^^^^^^^^^^^
../../.pub-cache/hosted/pub.dartlang.org/build_resolvers-1.3.7/lib/src/resolver.dart:332:7: Error: The setter 'useSummary' isn't defined for the class 'FolderBasedDartSdk'.
 - 'FolderBasedDartSdk' is from 'package:analyzer/src/dart/sdk/sdk.dart' ('../../.pub-cache/hosted/pub.dartlang.org/analyzer-0.39.15/lib/src/dart/sdk/sdk.dart').
Try correcting the name to the name of an existing setter, or defining a setter or field named 'useSummary'.
    ..useSummary = false
      ^^^^^^^^^^
Failed to precompile build_runner:build_runner:
../../.pub-cache/hosted/pub.dartlang.org/build_resolvers-1.3.7/lib/src/resolver.dart:343:10: Error: Method not found: 'SummaryBuilder'.
  return SummaryBuilder(sdkSources, sdk.context)
         ^^^^^^^^^^^^^^
../../.pub-cache/hosted/pub.dartlang.org/build_resolvers-1.3.7/lib/src/resolver.dart:332:7: Error: The setter 'useSummary' isn't defined for the class 'FolderBasedDartSdk'.
 - 'FolderBasedDartSdk' is from 'package:analyzer/src/dart/sdk/sdk.dart' ('../../.pub-cache/hosted/pub.dartlang.org/analyzer-0.39.15/lib/src/dart/sdk/sdk.dart').
Try correcting the name to the name of an existing setter, or defining a setter or field named 'useSummary'.
    ..useSummary = false
      ^^^^^^^^^^
pub finished with exit code 1
```
The same issue was reported in #2712 and it was supposedly fixed in 0.39.10 version, but there are reports of the compilation failure with later versions

**Comment by jakemac53** [comment] 2020-07-28 14:11
Are you able to update to `build_resolvers` version `1.3.10`? That is the easiest immediate fix.

cc @scheglov it looks like this api was removed again but still not in a breaking release.

**Comment by scheglov** [comment] 2020-07-28 15:31
Is this a new issue, or the same one caused by the same version of `analyzer`?

**Comment by jakemac53** [comment] 2020-07-28 16:45
The same issue but a different analyzer version (the title here says 0.39.15, but there was another report referencing [version 0.39.13](https://github.com/dart-lang/build/issues/2712#issuecomment-658597434)

**Comment by scheglov** [comment] 2020-07-28 17:30
OK, I see, the version of analyzer is different.

Yes, I think that the right solution is to update to the version of `build_resolvers` that started using the actual API from `analyzer`.  The previously used `SummaryBuilder` was not API.

**Comment by jakemac53** [comment] 2020-07-28 17:33
If a lot of people start running into this then we can revisit, closing for now.

**Comment by jakemac53** [comment] 2020-07-28 17:34
If you do run into this, and can't easily resolve it (by upgrading build_resolvers to at least `1.3.10`), please respond here or open a new issue.

**Closed by jakemac53** 2020-07-28 17:33 UTC

**Comment by nicemanis** [comment] 2020-07-29 09:55
Thank you for the response. The problem has disappeared after upgrading to `build_resolvers: 1.3.10`

**Comment by Sauraus** [comment] 2020-08-05 22:04
`build_resolvers 1.3.10` doesn't do it for us https://github.com/dart-lang/build/issues/2763#issuecomment-669544305

**Comment by oussaki** [comment] 2020-08-14 07:52
two thing i've done to solve this:
dependency_overrides:
  analyzer: '0.39.17'    
  build_resolvers: '1.3.10'
