### ISSUE TITLE
Uncaught Instance of 'minified:b0' when using proxy

### ISSUE THREAD

**Issue by odogy** [dart-lang/build#2337] opened 2019-06-29 22:12 UTC
Running proxy middleware in this Express app to serve JS files from the Dart web dev server is giving an "client.js:367 Uncaught Instance of 'minified:b0'" error. 

This may be the same issue or related to #2333 . However, build_web_compilers 2.1.2 does not seem to fix this, though it does fix #2333 for me (so I could just be screwing something up with configuration here). This worked before in a much older version of build_web_compilers (0.4.4+3) with build_runner 1.1.2 - I don't have any info for in-between versions.
 
* Dart SDK 2.4.0
* build_runner: 1.6.1, build_web_compilers: 2.1.2
* Windows 10
* Chrome

[minified_b0_issue.zip](https://github.com/dart-lang/build/files/3342341/minified_b0_issue.zip)
1. Download and unzip attached folder
2. run 'pub get' in client subfolder
3. run 'webdev serve' in client subfolder
4. run 'npm install' in server subfolder
5. run 'npm run start' in server subfolder
6. open http://localhost:3000/ in Chrome and check the console

If I'm just pursuing a silly strategy with the proxy middleware, and there's a better option, please let me know. Just figuring this stuff out.

**Comment by natebosch** [comment] 2019-07-02 16:53
> This worked before in a much older version of build_web_compilers (0.4.4+3) with build_runner 1.1.2

This is coming from `dart2js` and it is very unlikely to be impacted by the version of `build_runner` or `build_web_compilers` you are using since we've changed very little about how we invoke `dart2js`. The details for `ddc` have changed a lot and so differences in dev mode are more likely to be caused by changing version of `build_web_compilers`.

You might try disabling minification and debugging with the dart2js version to get a more specific error.
https://github.com/dart-lang/build/blob/master/docs/faq.md#how-can-i-debug-my-release-mode-web-app-dart2js

**Comment by odogy** [comment] 2019-07-02 17:33
I'm a little confused. I didn't know I was using dart2js here, since I'm just running webdev serve with default configuration. Is dart2js always used? As far as the error itself goes, the stack trace is identical to the one I see in #2333 which was resolved to be a pathing issue. I was sort of thinking this might be a similar issue due to the HTML being located on a different server. I will try using dart2js later today. Thanks!

**Comment by evanweible-wf** [comment] 2019-07-02 17:35
I can't remember the exact error, but I saw a similar `client.js` exception when using a proxy and refreshing at a URL that was not in the root directory. In order to fix that, I had to include a `<base href="/">` in the HTML that was being served.

**Comment by natebosch** [comment] 2019-07-02 17:46
>  I didn't know I was using dart2js here, since I'm just running webdev serve with default configuration

I would also expect DDC in that configuration, but I would not expect to see anything like `minified:b0` in that case. That looks like something coming from dart2js compiled code...

It looks like it may be related to dart2js code compiled by us for hot reload stuff maybe?
https://github.com/dart-lang/build/pull/2334 was intended to fix it but you would have been using a version with that fix at `2.1.2`

@jakemac53 @grouma do you have any more context here?

**Comment by grouma** [comment] 2019-07-02 18:04
`client.js` corresponds to this code here: 
https://github.com/dart-lang/webdev/blob/master/webdev/web/client.dart

This is precompiled with Dart2JS and shipped with `Webdev`. 
See: https://github.com/dart-lang/webdev/blob/master/webdev/lib/src/serve/injected/client.js 

The client is injected by `Webdev` and handles the handshake between server and browser. It also sets up various listeners to support the debugging and development workflows e.g. `alt + d`.

It would be helpful to get the unminified error. I created a PR which has the unoptimized client. Simply activate `Webdev` from this branch:
https://github.com/dart-lang/webdev/pull/472

**Comment by truthmast** [comment] 2019-07-21 22:44
The branch created for https://github.com/dart-lang/webdev/pull/472 has been deleted. Is there still a branch somewhere with the unminified version of webdev? I'm trying to provide an unminified version of the following error:
```
Uncaught Instance of 'minified:p'
    at Object.b (http://localhost:8888/web/webdev/src/serve/injected/client.js:367:3)
    at nq.$0 (http://localhost:8888/web/webdev/src/serve/injected/client.js:5445:20)
    at Object.uK (http://localhost:8888/web/webdev/src/serve/injected/client.js:1268:5)
    at kK.uP (http://localhost:8888/web/webdev/src/serve/injected/client.js:1270:7)
    at lL.$1 (http://localhost:8888/web/webdev/src/serve/injected/client.js:4865:3)
    at vk (http://localhost:8888/web/webdev/src/serve/injected/client.js:441:17)
    at MutationObserver.<anonymous> (http://localhost:8888/web/webdev/src/serve/injected/client.js:449:51)
```

**Comment by grouma** [comment] 2019-07-22 18:17
The branch was deleted as we no longer minify the client:
https://github.com/dart-lang/webdev/pull/497

Note that I will be publishing a new version of `webdev` later today which will include that change.

**Comment by grouma** [comment] 2019-07-22 19:46
I just published a new version of `webdev` (`2.3.0`) which does not minify the injected client.

**Comment by truthmast** [comment] 2019-07-22 21:11
Thanks!~
Here is the unminified error (`web/` is my base-href):
```
client.js:1016 Uncaught Instance of 'Event'
    at Object.wrapException (http://localhost:8888/web/dwds/src/injected/client.js:1016:17)
    at _rootHandleUncaughtError_closure.call$0 (http://localhost:8888/web/dwds/src/injected/client.js:12697:17)
    at Object._microtaskLoop (http://localhost:8888/web/dwds/src/injected/client.js:3253:21)
    at StaticClosure._startMicrotaskLoop (http://localhost:8888/web/dwds/src/injected/client.js:3259:11)
    at _AsyncRun__initializeScheduleImmediate_internalCallback.call$1 (http://localhost:8888/web/dwds/src/injected/client.js:11368:9)
    at invokeClosure (http://localhost:8888/web/dwds/src/injected/client.js:1206:26)
    at MutationObserver.<anonymous> (http://localhost:8888/web/dwds/src/injected/client.js:1225:18)
```

**Comment by grouma** [comment] 2019-07-22 21:52
Looks like there are two issues:

1) We can't resolve the `/main.digests` request here:
https://github.com/dart-lang/webdev/blob/880bdb361c2bbf8133fcfa224c78eb8427a2ca19/dwds/web/client.dart#L204

2) We can't create the `SSE` connection (`/$sseHandler?sseClientId=<some-id>`) here:
https://github.com/dart-lang/webdev/blob/880bdb361c2bbf8133fcfa224c78eb8427a2ca19/dwds/web/client.dart#L49

I was able to change the filter provided to the npm proxy server in the repo example and everything worked as expected without any changes to webdev.

We should probably add some better error handling in the injected client but I don't know if we should make any further logic changes.

@truthmast What is your set up like?

**Comment by truthmast** [comment] 2019-07-25 18:01
Getting back to this today! Sorry for the delay.

I'm running webdev with some other services (App Engine dev_server.py instances) using docker-compose. `/web/` is the base-href on my page and here is how webdev fits in:

- Request to an App Engine dev server container at `http://localhost:8888/web/*`
- Dev server proxies the request to `http://webdev-serve(/web/*)`
- Responds with content from `webdev serve` running in that container

I'm seeing a request for `http://localhost:8888/web/main.digests` which is `200 OK`, content looks good.

The SSE handler request is going to: `http://localhost:8888/$sseHandler?sseClientId=<client-id>`, and that is definitely failing. It doesn't have the base-href of `/web/`, but I also tried to route the request to `http://localhost:8888/web/$sseHandler?sseClientId=<client-id>` and that also returns a 404.

Thanks!

**Comment by grouma** [comment] 2019-07-25 18:27
I would look into why the request is failing. Maybe you haven't configured $sseHandler requests to properly be forwarded?

It's hard to say what exactly the problem is but it sounds like your proxy server may not support SSE requests:
https://en.wikipedia.org/wiki/Server-sent_events

By the way, the request shouldn't be under `/web/$sseHandler`.

**Comment by truthmast** [comment] 2019-07-25 18:46
My question is, how should the $sseHandler request be proxied? Everything else loaded by `webdev` is requested at `/web/*` except for `/$sseHandler`. My proxy doesn't handle requests outside of `/web/` because that's where the rest of my App Engine app lives. I can add a special handler for requests to `/$sseHandler`, but this suggests that I can't expect all requests to be contained within my base-href.

**Comment by grouma** [comment] 2019-07-25 19:00
Yes this should be special cased. We only have one SSE handler running for a given `webdev` instance and it services all applications launched by the tool.

**Comment by grouma** [comment] 2019-07-25 19:48
I created this PR that supports the base href in the SSE connect request:
https://github.com/dart-lang/webdev/pull/519

Let me know if this works for you.

**Comment by truthmast** [comment] 2019-07-26 18:27
How can I target this branch with `pub global activate`?

**Comment by jakemac53** [comment] 2019-07-26 19:11
https://dart.dev/tools/pub/cmd/pub-global#activating-a-package-with-git

**Comment by truthmast** [comment] 2019-07-26 20:34
Pulling down the `base-ref` branch and activating it with this command:
`pub global activate -s path webdev/webdev`
Output:
`Activated webdev 2.3.0 at path "/Users/matt/webdev/webdev".`

Running `webdev serve` gives me the following error output:
```
Unable to spawn isolate: file:///Users/matt/webdev/webdev/lib/src/command/configuration.dart:6:8: Error: Error when reading 'file:///Users/matt/webdev/webdev/webdev/dwds/lib/dwds.dart': No such file or directory
import 'package:dwds/dwds.dart';
       ^
file:///Users/matt/webdev/webdev/lib/src/daemon/app_domain.dart:10:8: Error: Error when reading 'file:///Users/matt/webdev/webdev/webdev/dwds/lib/dwds.dart': No such file or directory
import 'package:dwds/dwds.dart';
       ^
file:///Users/matt/webdev/webdev/lib/src/serve/webdev_server.dart:9:8: Error: Error when reading 'file:///Users/matt/webdev/webdev/webdev/dwds/lib/dwds.dart': No such file or directory
import 'package:dwds/dwds.dart';
       ^
file:///Users/matt/webdev/webdev/lib/src/command/configuration.dart:27:1: Error: Type 'ReloadConfiguration' not found.
ReloadConfiguration _parseReloadConfiguration(ArgResults argResults) {
^^^^^^^^^^^^^^^^^^^
file:///Users/matt/webdev/webdev/lib/src/command/configuration.dart:83:9: Error: Type 'ReloadConfiguration' not found.
  final ReloadConfiguration _reload;
        ^^^^^^^^^^^^^^^^^^^
file:///Users/matt/webdev/webdev/lib/src/command/configuration.dart:98:5: Error: Type 'ReloadConfiguration' not found.
    ReloadConfiguration reload,
    ^^^^^^^^^^^^^^^^^^^
file:///Users/matt/webdev/webdev/lib/src/command/configuration.dart:134:3: Error: Type 'ReloadConfiguration' not found.
  ReloadConfiguration get reload => _reload ?? ReloadConfiguration.none;
  ^^^^^^^^^^^^^^^^^^^
file:///Users/matt/webdev/webdev/lib/src/daemon/app_domain.dart:25:3: Error: Type 'DebugConnection' not found.
  DebugConnection _debugConnection;
  ^^^^^^^^^^^^^^^
file:///Users/matt/webdev/webdev/lib/src/serve/webdev_server.dart:36:9: Error: Type 'Dwds' not found.
  final Dwds dwds;
        ^^^^
file:///Users/matt/webdev/webdev/lib/src/command/configuration.dart:61:14: Error: Getter not found: 'ReloadConfiguration'.
      return ReloadConfiguration.none;
             ^^^^^^^^^^^^^^^^^^^
```

The local `dwds` package doesn't properly resolve.

**Comment by truthmast** [comment] 2019-07-26 21:01
Got it with `pub global activate -s path ~/webdev/webdev`

Had to specify full path

**Comment by grouma** [comment] 2019-07-30 09:45
Did that branch resolve your issues?

**Comment by truthmast** [comment] 2019-08-02 16:32
I had one issue with the branch missing a trailing `/` on the path. The path constructed was  `web$sseHandler...` but I was able to easily fix that locally.

While this branch makes my routing rules simpler in the proxy, I can see that it's not the actual problem here. I can resolve this pathing in the version published to pub with some extra routing rules on my end. The real problem is my proxy doesn't handle the infinite-timeout-always-open connection that SSE uses.

I wasn't seeing this connection in the older version of build_runner that I was previously using. My proxy is custom and very simple; previously (`^1.1.2`), just relaying GET requests was enough to make it work.

Is it possible to disable this connection? I imagine that it's what enables the auto-restart/reload functionality, but if I could optionally disable that and manually reload the page that would work for me right now.

**Comment by grouma** [comment] 2019-08-05 16:04
Closing in favor of https://github.com/dart-lang/webdev/issues/540

**Closed by grouma** 2019-08-05 16:04 UTC
Labels: type: bug
