### ISSUE TITLE
Allow "private" builders (in tool/**)

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/build#919] opened 2018-01-29 18:20 UTC
In `code_builder`, I want to create and provide a builder (today, using `built_value`)... but I only want to use it for myself (i.e. as a dev_dependency, and then I check in the resulting `.g.dart` files as part of my package). This is to get off the legacy workflow of a manual `build.dart` file.

It works (sort of), though it does require the following configuration:

```yaml
targets:
  $default:
    builders:
      "|_built_value":

builders:
  _built_value:
    target: ":code_builder"
    import: "../../../tool/src/builder.dart"
    builder_factories:
      - "builtValueBuilder"
    build_extensions:
      ".dart": ".g.dart"
    build_to: "source"
```

I noticed that `import` is not validated (even though docs say otherwise).

It should probably check that:

* It is a `package:` reference OR
* It is a reference to a file that exists in the current package (i.e. `tool/src/builder.dart`)

I don't know if there is a good way to denote the builder as "private" (maybe anything but a `package:` scheme does this implicitly?), but we need to be able to make sure others don't try to use this builder themselves.

**Comment by jakemac53** [comment] 2018-06-12 22:03
Closing this as working as intended for now.

We now treat any builder with a non `package:` import as private to the package.

We could add a flag which allows you to use a package: import and make it private but I don't think there is an actual use case for that, and there is the workaround of just doing a relative `lib/*` import.

**Closed by jakemac53** 2018-06-12 22:03 UTC
Labels: package: build_config, type: enhancement
