### ISSUE TITLE
Error using 0.8.9 with Flutter

### ISSUE THREAD

**Issue by mjohnsullivan** [dart-lang/build#1483] opened 2018-05-23 19:43 UTC
When trying to build on Flutter Beta 3 ('flutter pub pub run build_runner build'), 0.8.9 gives the following error:

NoSuchMethodError: No static getter 'terminal' declared in class 'StdioType'.
Receiver: StdioType
Tried calling: terminal
dart:core                                                       NoSuchMethodError._throwNew
package:build_runner/src/environment/io_environment.dart 67:35  _canPrompt
package:build_runner/src/environment/io_environment.dart 35:47  new IOEnvironment
package:build_runner/src/generate/build_impl.dart 77:11         build
package:build_runner/src/generate/build.dart 71:5               build
package:build_runner/src/entrypoint/build.dart 28:24            BuildCommand.run
package:args/command_runner.dart 194:27                         CommandRunner.runCommand
package:args/command_runner.dart 109:29                         CommandRunner.run.<fn>
dart:async                                                      new Future.sync
package:args/command_runner.dart 109:11                         CommandRunner.run
package:build_runner/src/entrypoint/run.dart 22:31              run
.dart_tool/build/entrypoint/build.dart 11:22                    main

pub finished with exit code 1

0.7.9 is working great.

**Comment by jakemac53** [comment] 2018-05-23 19:47
Duplicate of flutter/flutter#17656, you should be able to fix this now by updating your flutter version to the latest

**Closed by jakemac53** 2018-05-23 19:47 UTC
