### ISSUE TITLE
`build` needs a `--clean` flag

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/build#1170] opened 2018-03-15 15:11 UTC
Related to https://github.com/dart-lang/build/issues/1104

I'm doing a lot of `rm -rf .dart_tool/build; pbr build` to reproduce an issue, etc

**Comment by matanlurey** [comment] 2018-03-15 16:12
Duplicate of https://github.com/dart-lang/build/issues/1104.

**Comment by kevmoo** [comment] 2018-03-15 19:40
Not quite.

A stand-alone clean command. Great.

This is asking for a `--clean` flag to be added to the build command.

**Comment by matanlurey** [comment] 2018-03-15 19:44
I'm not sure of the value here. It's 1 command versus 2?

We don't want this to be a common flag/command, for example in #1104 I outline that we should prompt the user to file a bug everytime they have to use this, because it means we are probably doing something wrong.

**Comment by kevmoo** [comment] 2018-03-15 19:47
It's nice when debugging builders, etc – to run everything every time...

I guess one could just do `pbr clean; pbr build` 🤷‍♂️

**Comment by matanlurey** [comment] 2018-03-15 19:48
Right, but the point is you shouldn't need it - builders should rerun from scratch if changed.

**Comment by kevmoo** [comment] 2018-03-15 20:18
> Right, but the point is you shouldn't need it - builders should rerun from scratch if changed.

Right, but often you want to rerun several times from scratch as you're trying to step through and debug...

**Comment by natebosch** [comment] 2018-03-15 21:24
Today we typically touch a line of code in our builder which invalidates the entire build. I personally haven't had a need to rerun with a builder in exactly the same code state...

**Comment by dineshbhosale** [comment] 2018-03-22 12:20
When a user is trying to configure `build_runner` , he tries to make changes to build configuration files to see how things work; For example adding new arguments to `dart2js` , excluding certain files, etc etc.

In such situations, deleting `.dart-tool` folder and re-running entire build step is really useful IMO.

In my use case I wanted to change release configuration file to see how it would affect my chrome extension.

So I was forced to run two different commands whenever I want to run a build:

```
rm -rf .dart_tool/
pub run build_runner build --config release --output release
```

If we can add `--clean` flag or provide an option in `build.release.yaml` to delete `.dart_tool` folder than it will be really useful IMO.

**Comment by dineshbhosale** [comment] 2018-03-22 12:29
Using pub a user can run `pub build`. 
This command will start to build everything from scratch with new configuration.

This is not so useful while developing an angular app but when you are releasing a chrome extension then you would want to do that, this can be achieved by adding a `--clean` flag or by providing an option in `build.release.yaml` to delete `.dart_tool` folder.

Since `pub build` is deprecated we want `build_runner` to be flexible enough to do what `pub build` did in the past for building stuff like chrome extensions.

**Comment by natebosch** [comment] 2018-03-22 17:13
@dineshbhosale - If things are working correctly you should not need to delete this directory. If you update your configuration it will automatically clean whatever is necessary. The proposed `--clean` command is only for when things are going wrong, or here as a substitute for `--rerun-failing-actions`. 
https://github.com/dart-lang/build/issues/910#issuecomment-362735737

What issues are you seeing when you don't delete it?

**Comment by dineshbhosale** [comment] 2018-03-23 07:29
So far it works fine, I had no issues.

`pub build` worked fine for release builds of chrome extensions.

I want to implement similar functionality with `build_runner` just to be extra sure that everything is up to date in release build.

**Comment by matanlurey** [comment] 2018-03-24 18:27
Closing. There is no reason to be "extra sure". If we need things cleaned up, its a bug.

**Closed by matanlurey** 2018-03-24 18:27 UTC
Labels: package: build_runner, resolution: duplicate, type: enhancement

**Comment by MikeMitterer** [comment] 2018-06-04 18:28
I have another use case:
My builder reads a version info from git and generates some files.
Builder isn't aware of git changes so it doesn't rebuild the files.
--clean option would solve this problem.

My workaround is:
```
rm -rf .dart_tool/build/generated && pub run build_runner build
```
git_version: https://github.com/MikeMitterer/dart-git_version
usage-sample: https://github.com/MikeMitterer/mini_web_sample

pre condition: 
e.g.: git tag v1.0

**Comment by matanlurey** [comment] 2018-06-04 18:32
> My builder reads a version info from git and generates some files.
> Builder isn't aware of git changes so it doesn't rebuild the files.

That sounds like the whitelisting feature of the build system:
https://github.com/dart-lang/build/blob/a3a3b7d4403bf5ff5d6c92c630547dd9833c46da/build_runner_core/lib/src/generate/options.dart#L18-L28

I'd open up another bug asking how to customize this whitelist, not for `--clean`.

**Comment by natebosch** [comment] 2018-06-04 19:35
> My builder reads a version info from git and generates some files.

I guess you are using `dart:io` direction? This is not supported. If you need to be able to read files from `.git/` you should add them to a target. Perhaps:

```yaml
targets:
  $default:
    sources:
      exclude: [".git/**"]
   _git:
    sources:
      include: [".git/**"]
```

After that you should be able to construct an asset ID like `new AssetId(<your package name>, '.git/path/to/file')` and read these files through the build step.

**Comment by MikeMitterer** [comment] 2018-06-04 21:33
How would a whitelisting help if files don't change? OK - there are some changes but they are deep inside of .git

```bash
mini_web_sample $ git tag -l --sort=v:refname
v1.0
> mini_web_sample $ git describe --tags --match v1.0
v1.0-4-gb61c783
```
Thats what the package does, then it cuts off everything after the last dash.
Result v1.0-4

Every commit increases the last value v1.0-4 -> v1.0-5
The build system doesn't know anything about those commits.

Why is a --clean option so bad? It's easy to understand and easy to use.
It would also be quite useful for CI system.

`pub run build_runner build --clean` - looks clean and everyone know what it does

**Comment by matanlurey** [comment] 2018-06-04 21:36
@MikeMitterer As mentioned, using `dart:io` in the builder is not supported.

Take a look at @natebosch's comment for an example of what to do.

**Comment by jakemac53** [comment] 2018-06-04 21:44
Another option would be to run the git command and output it to a file in your package, then read that file in the builder.

Then, you just re-run the git command and run a build and only that one builder will rerun.

**Comment by jakemac53** [comment] 2018-06-04 21:45
You could even wrap up the build command in a little shell script that does that automatically for you before each build?

**Comment by natebosch** [comment] 2018-06-04 22:19
> Why is a --clean option so bad?

It's a pattern we want to discourage so we don't want to build in explicit support and give the impression that we think it's something users should ever have to do.

> It's easy to understand and easy to use.

It's also rarely something the users wants to happen. In this case it's definitely not what you want to happen - you wouldn't want to rerun DDC or any other builders that aren't impacted by the version change coming from git. You'd really like to rerun _only_ that builder and any other builders that depend on it, not the entire build graph. I filed https://github.com/dart-lang/build/issues/1512 to track the feature that would solve this problem.

> It would also be quite useful for CI system.

`pub run build_runner clean && pub run build_runner build` is pretty easy for a CI system, and we can always fall back on general "don't share build artifacts" practices which are already common practice for hermetic CI.
