### ISSUE TITLE
Stack traces are not working properly for errors in auto generated files when dart2js is used

### ISSUE THREAD

**Issue by drbcode** [dart-lang/build#1896] opened 2018-11-04 23:38 UTC
pubspec.yaml:
```yaml
name: stacktrace_test
version: 0.0.1
description:
homepage:
documentation:
author:
environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  angular: any

dev_dependencies:
  build_runner: any
  build_web_compilers: any
```

build.csp.yaml:
```yaml
targets:
  $default:
    builders:
      build_web_compilers|entrypoint:
        options:
          compiler: dart2js
          dart2js_args:
            - --csp
```

index.html:
```html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>test</title>
    <script defer src="index.dart.js"></script>
</head>
<body>
</body>
</html>
```

index.dart:
```dart
//import 'dart:async';
import 'package:angular/angular.dart';
// ignore: uri_has_not_been_generated
import "package:stacktrace_test/app/app.template.dart" as app;
// ignore: uri_has_not_been_generated
import 'index.template.dart' as self;

@GenerateInjector([])
final InjectorFactory injector = self.injector$Injector;

void main() {
  runApp(
    app.AppCompNgFactory,
    createInjector: injector,
  );
}
```

lib/app/app.dart:
```dart
import 'package:angular/angular.dart';
import 'dart:async';
@Component(
  selector: 'root',
  template: '',
)
class AppComp implements OnInit {
  @override
  Future<void> ngOnInit() async {
    throw new Error();
  }
}
```

building project using dart2js:
` pub run build_runner build --config=csp --output build`

after that open `build/web/index.html`, after that console shows:
```text
EXCEPTION: Instance of 'Error'
STACKTRACE: 
Instance of 'Error'
    at Object.wrapException (http://localhost:63342/stacktrace_test/build/web/index.dart.js:1356:17)
    at http://localhost:63342/stacktrace_test/build/web/index.dart.js:9919:25
    at _wrapJsFunctionForAsync_closure.$protected (http://localhost:63342/stacktrace_test/build/web/index.dart.js:3329:15)
    at _wrapJsFunctionForAsync_closure.dart._wrapJsFunctionForAsync_closure.call$2 (http://localhost:63342/stacktrace_test/build/web/index.dart.js:3752:14)
    at Object._asyncStartSync (http://localhost:63342/stacktrace_test/build/web/index.dart.js:3290:20)
    at AppComp.ngOnInit$0 (http://localhost:63342/stacktrace_test/build/web/index.dart.js:9924:18)
    at _ViewAppCompHost0.detectChangesInternal$0 (http://localhost:63342/stacktrace_test/build/web/index.dart.js:9992:29)
    at _ViewAppCompHost0.detectChanges$0 (http://localhost:63342/stacktrace_test/build/web/index.dart.js:9150:16)
    at ApplicationRef._runTick$0 (http://localhost:63342/stacktrace_test/build/web/index.dart.js:8993:32)
    at ApplicationRef.dart.ChangeDetectionHost.tick$0 (http://localhost:63342/stacktrace_test/build/web/index.dart.js:8973:16)
```

Running using `DDC`:
` webdev serve web`

After that open `http://localhost:8080/` and console output will look similar to this:
```
EXCEPTION: Instance of 'Error'
STACKTRACE: 
dart:sdk_internal                                           throw
package:stacktrace_test/app/app.dart 10:5                   ngOnInit
dart:sdk_internal                                           async
package:stacktrace_test/app/app.dart 9:27                   ngOnInit
package:stacktrace_test/app/app.template.dart 64:19         detectChangesInternal
package:angular/src/core/linker/app_view.dart 398:7         detectChanges
package:angular/src/core/linker/view_ref.dart 106:12        detectChanges
package:angular/src/core/change_detection/host.dart 168:18  [_runTick]
package:angular/src/core/change_detection/host.dart 144:15  tick
package:angular/src/core/application_ref.dart 108:5         [_loadedRootComponent]
package:angular/src/core/application_ref.dart 96:27         src__runtime__optimizations.unsafeCast.run.dart.fn
package:angular/src/core/change_detection/host.dart 250:18  runInZone.dart.fn
package:angular/src/core/zone/ng_zone.dart 178:16           parent.run.dart.fn
dart:sdk_internal                                           run
package:angular/src/core/zone/ng_zone.dart 175:18           [_run]
dart:sdk_internal                                           run
package:angular/src/core/zone/ng_zone.dart 327:22           run
package:angular/src/core/application_ref.dart 140:51        runInZone
package:angular/src/core/change_detection/host.dart 248:5   run
package:angular/src/core/application_ref.dart 69:23         bootstrap
package:angular/src/bootstrap/run.dart 188:16               runApp
index.dart 12:3                                             main
index.dart.bootstrap.js 271:13                              <fn>

package:stacktrace_test/app/app.dart 9:27                   ngOnInit
package:stacktrace_test/app/app.template.dart 64:19         detectChangesInternal
package:angular/src/core/linker/app_view.dart 398:7         detectChanges
package:angular/src/core/linker/view_ref.dart 106:12        detectChanges
package:angular/src/core/change_detection/host.dart 168:18  [_runTick]
package:angular/src/core/change_detection/host.dart 144:15  tick
package:angular/src/core/application_ref.dart 108:5         [_loadedRootComponent]
package:angular/src/core/application_ref.dart 96:27         src__runtime__optimizations.unsafeCast.run.dart.fn
package:angular/src/core/change_detection/host.dart 250:18  runInZone.dart.fn
package:angular/src/core/zone/ng_zone.dart 178:16           parent.run.dart.fn
dart:sdk_internal                                           run
package:angular/src/core/zone/ng_zone.dart 175:18           [_run]
dart:sdk_internal                                           run
package:angular/src/core/zone/ng_zone.dart 327:22           run
package:angular/src/core/application_ref.dart 140:51        runInZone
package:angular/src/core/change_detection/host.dart 248:5   run
package:angular/src/core/application_ref.dart 69:23         bootstrap
package:angular/src/bootstrap/run.dart 188:16               runApp
index.dart 12:3                                             main
index.dart.bootstrap.js 271:13                              <fn>
```

package versions:
```
build:
    version: "0.12.8"
  build_config:
    version: "0.3.1+4"
  build_modules:
    version: "1.0.2"
  build_resolvers:
    version: "0.2.2+6"
  build_runner:
    version: "0.10.3"
  build_runner_core:
    version: "1.0.0"
  build_web_compilers:
    version: "0.4.4+2"
  built_collection:
    version: "4.0.0"
```

As you can see in above example, stack-trace do not point to the line numbers in dart file where an error is thrown when dart2js is used for building project, but when `DDC` is used it shows the line numbers where an error is thrown, as a result of this issue a developer might be forced to switch from dart2js to DDC for debugging stack-traces that do not show the correct line numbers.

**Comment by jakemac53** [comment] 2018-11-05 17:55
This does work in serve mode of build_runner with dart2js, or when running a local server in either the package directory or the built output directory.

I think what doesn't work is loading it via a `file:` uri in chrome, which isn't a supported use case, although I am not totally sure why it doesn't work.

Going to close this as working as intended for now, feel free to re-open if you this I diagnosed this wrong.

**Comment by drbcode** [comment] 2018-11-05 23:40
I followed your suggestions and followed steps given below to test whether `webdev serve` with `dart2js` will show stack-traces as expected, it turns out that it does not:

In above example I made certain changes, such as,
I used this `build.yaml` :
```yaml
targets:
  $default:
    builders:
      build_web_compilers|entrypoint:
        options:
          compiler: dart2js
          dart2js_args:
            - --csp
```

After that ran `webdev serve web`.

After opening `http://localhost:8080/` it shows stack-traces that do not point to line numbers in dart files:
```text
core_patch.dart:566 EXCEPTION: Instance of 'Error'
STACKTRACE: 
Instance of 'Error'
    at Object.wrapException (http://localhost:8080/index.dart.js:6167:17)
    at http://localhost:8080/index.dart.js:14680:25
    at _wrapJsFunctionForAsync_closure.$protected (http://localhost:8080/index.dart.js:8090:15)
    at _wrapJsFunctionForAsync_closure.dart._wrapJsFunctionForAsync_closure.call$2 (http://localhost:8080/index.dart.js:8513:14)
    at Object._asyncStartSync (http://localhost:8080/index.dart.js:8051:20)
    at AppComp.ngOnInit$0 (http://localhost:8080/index.dart.js:14685:18)
    at _ViewAppCompHost0.detectChangesInternal$0 (http://localhost:8080/index.dart.js:14753:29)
    at _ViewAppCompHost0.detectChanges$0 (http://localhost:8080/index.dart.js:13911:16)
    at ApplicationRef._runTick$0 (http://localhost:8080/index.dart.js:13754:32)
    at ApplicationRef.dart.ChangeDetectionHost.tick$0 (http://localhost:8080/index.dart.js:13734:16)
```

From my experience of writing chrome extensions for too long, I can confirm that all stack traces work fine for both `DDC` and `dart2js` for files loaded via `file` URLs or loading them via static file server, except when the error is in a `*.template.dart` and the project is built via `dart2js`.

In above example stack-traces are not working because error is in `app.template.dart` file loaded by `index.dart`.

**Comment by drbcode** [comment] 2018-11-05 23:51
It's a severe issue because at the moment it is not possible to debug angular dart apps using dart2js because errors in `*.template.dart` files do not point to line number where error has occurred. 
All angular dart components are loaded via `*.template.dart` import paths.

**Comment by drbcode** [comment] 2018-11-06 02:05
I have seen other people complain about bad source maps in gitter chat, maybe it has something to do with above issue:

https://gitter.im/dart-lang/build?at=5b9e9a9efcba1254fac57dcf

https://gitter.im/dart-lang/build?at=5b9e9fbee5c2cc56ad9b97f5

**Comment by jakemac53** [comment] 2018-11-06 16:26
I wonder if this is because of the `--csp` mode? The build server does not treat generated files any differently than source files.

**Comment by jakemac53** [comment] 2018-11-06 16:57
Hmm I can't reproduce this generally in `--csp` mode either

**Comment by jakemac53** [comment] 2018-11-06 17:11
Ok - I was able to reproduce this with the angular app. The issue appears to be that angular is swallowing the errors and doing something special with them which breaks the source map translation.

This is a familiar issue now... I think there is a bug on the angular repo about it.

In chrome debugger if you set it to pause on caught exceptions it will break at the correct place.

**Comment by jakemac53** [comment] 2018-11-06 17:11
cc @matanlurey do you remember the status here?

**Comment by matanlurey** [comment] 2018-11-06 18:00
I don't see any open issues on `dart-lang/angular`. I'm not sure what the issue is/could be.

**Comment by jakemac53** [comment] 2018-11-06 18:16
@matanlurey So basically there is this BrowserExceptionHandler https://github.com/dart-lang/angular/blob/b7836989698a148309573a5c74c2e7c3f07c20d6/angular/lib/src/platform/browser/exceptions.dart#L14, which calls `console.error` with some custom string formatting from ExceptionHandler.

This ends up bypassing whatever normal stack trace mapping happens somehow, but I don't know enough about how it is supposed to work to know why that might be or if its solvable.

cc @sigmundch

**Comment by matanlurey** [comment] 2018-11-06 19:06
Right! I think it's unlikely we can change that immediately.

Anyone could provide their own exception handler that does the behavior they want if desired.

**Comment by jakemac53** [comment] 2018-11-06 19:07
Closing this as working as intended again then

**Closed by jakemac53** 2018-11-06 19:07 UTC

**Comment by jakemac53** [comment] 2018-11-06 21:18
I messed around a bit with this to see if I could get something sensible, and I did come up with the following exception handler, which produces a stack trace chrome can understand. This somewhat maps to what dart2js does under the covers normally:

```
class ThrowingExceptionHandler implements ExceptionHandler {
  @override
  void call(exception, [stackTrace, String reason]) {
    var jsError = JsObject(context['Error']);
    jsError['message'] = '$exception';
    jsError['stack'] = stackTrace.toString();
    (context['console'] as JsObject).callMethod('error', [jsError]);
  }
}
```

You can provide it using a normal provider... `Provider(ExceptionHandler, useClass: ThrowingExceptionHandler)` and it might work for you.

@matanlurey should angular consider something like this for the default behavior?

**Comment by jakemac53** [comment] 2018-11-06 21:35
Ok, so I narrowed this down to the real issue. Apparently chrome only applies formatting to errors that it recognizes, using either a prefix match or some sort of regex. Given the following code the first two don't work, and the following three do:

```dart
    var jsError = JsObject(context['Error']);
    jsError['message'] =
        'Error: Exception: $exception\nReason: $reason\nStack Trace: $stackTrace';
    // Logs the error object (useless)
    window.console.error(jsError);
    // Logs a javasacript stack trace (todays behavior essentially)
    window.console.error(
        'Exception: $exception\nReason: $reason\nStack Trace: $stackTrace');
    /// All of the following work
    window.console.error(jsError.toString());
    window.console.error(
        'Error: Exception: $exception\nReason: $reason\nStack Trace: $stackTrace');
    window.console.error(
        'TypeError: Exception: $exception\nReason: $reason\nStack Trace: $stackTrace');
```

**Comment by drbcode** [comment] 2018-11-07 00:32
Thanks for the help!

```dart
import 'package:angular/angular.dart';
// ignore: uri_has_not_been_generated
import "package:stacktrace_test/app/app.template.dart" as app;
// ignore: uri_has_not_been_generated
import 'index.template.dart' as self;
import 'dart:html' as html;

class ThrowingExceptionHandler implements ExceptionHandler {
  @override
  void call(exception, [stackTrace, String reason]) {
    html.window.console.error(
        'Error: Exception: $exception\nReason: $reason\nStack Trace: $stackTrace');
  }
}

@GenerateInjector([
  Provider(ExceptionHandler, useClass: ThrowingExceptionHandler),
])
final InjectorFactory injector = self.injector$Injector;

void main() {
  runApp(
    app.AppCompNgFactory,
    createInjector: injector,
  );
}
```

I'm using above `index.dart` and it shows line numbers for both ddc and dart2js outputs, so it resolves the issue for me.

But I noticed that custom formater works well for dart2js errors, however it doesn't work for errors shown by DDC, for example see the screenshots given below:

Dart2js stacktrace, notice how `app.dart:10` is clickable, makes it easy to inspect files:
![stacktrace](https://user-images.githubusercontent.com/41248528/48102554-997af280-e251-11e8-88ef-378ac116da57.png)

DDC stacktrace, (with and without above custom exception handler looks like the screenshot given below)
notice how `app.dart:10` is not clickable, no easy to inspect files as compared to dart2js output:
![stacktrace_ddc](https://user-images.githubusercontent.com/41248528/48102633-07bfb500-e252-11e8-946f-d9cddcc1b8db.png)

**Comment by jakemac53** [comment] 2018-11-13 20:06
Ya, its complicated :(. For DDC we are manually mapping the stack traces to dart instead of letting the browser do it. I don't know the details on why. When we do that, we are using `package:` uris which the browser doesn't understand, so it can't link them to files.

We need to come up with a unified approach here.
