### ISSUE TITLE
`dart run build_runner watch -d` not generating .g.dart files with the latest package:graphs

### ISSUE THREAD

**Issue by rrousselGit** [dart-lang/build#3503] opened 2023-05-12 08:51 UTC
Hello!

I've hit an issue in a few of my packages where running `dart run build_runner watch -d` does not generate any output.    
The generators are using source_gen, so I thought that could be the source. But I've tried downgrading it to versions I knew were working, to no avail.

TL;DR, temporary files inside the .dart_tool folders are correctly created (for ex. `.dart_tool/build/generated/my_file.my_part.g.part`). But the associated .g.dart is never created.   

I'm not sure exactly what could be causing this, so I've made a reproduction repository:

```
git clone https://github.com/rrousselGit/build_runner_bug
cd build_runner_bug/packages/custom_lint_core
dart pub get
dart pub run build_runner watch -d
```

Expected output:  
This should generate a `build_runner_bug/packages/custom_lint_core/lib/node_lint_visitor.g.dart`.

Actual:
No .g.dart is generated, even though a `build_runner_bug/packages/custom_lint_core/.dart_tool/build/generated/custom_lint_core/lib/src/node_lint_visitor.lint_visitor_generator.g.part` file is generated.

```
Dart SDK version: 3.1.0-69.0.dev (dev) (Tue May 2 23:30:22 2023 -0700) on "macos_arm64"
```

lock file:

<details>
# Generated by pub
# See https://dart.dev/tools/pub/glossary#lockfile
packages:
  _fe_analyzer_shared:
    dependency: transitive
    description:
      name: _fe_analyzer_shared
      sha256: "405666cd3cf0ee0a48d21ec67e65406aad2c726d9fa58840d3375e7bdcd32a07"
      url: "https://pub.dev"
    source: hosted
    version: "60.0.0"
  analyzer:
    dependency: "direct main"
    description:
      name: analyzer
      sha256: "1952250bd005bacb895a01bf1b4dc00e3ba1c526cf47dca54dfe24979c65f5b3"
      url: "https://pub.dev"
    source: hosted
    version: "5.12.0"
  args:
    dependency: transitive
    description:
      name: args
      sha256: c372bb384f273f0c2a8aaaa226dad84dc27c8519a691b888725dec59518ad53a
      url: "https://pub.dev"
    source: hosted
    version: "2.4.1"
  async:
    dependency: transitive
    description:
      name: async
      sha256: "947bfcf187f74dbc5e146c9eb9c0f10c9f8b30743e341481c1e2ed3ecc18c20c"
      url: "https://pub.dev"
    source: hosted
    version: "2.11.0"
  boolean_selector:
    dependency: transitive
    description:
      name: boolean_selector
      sha256: "6cfb5af12253eaf2b368f07bacc5a80d1301a071c73360d746b7f2e32d762c66"
      url: "https://pub.dev"
    source: hosted
    version: "2.1.1"
  build:
    dependency: transitive
    description:
      name: build
      sha256: "43865b79fbb78532e4bff7c33087aa43b1d488c4fdef014eaef568af6d8016dc"
      url: "https://pub.dev"
    source: hosted
    version: "2.4.0"
  build_config:
    dependency: transitive
    description:
      name: build_config
      sha256: bf80fcfb46a29945b423bd9aad884590fb1dc69b330a4d4700cac476af1708d1
      url: "https://pub.dev"
    source: hosted
    version: "1.1.1"
  build_daemon:
    dependency: transitive
    description:
      name: build_daemon
      sha256: "5f02d73eb2ba16483e693f80bee4f088563a820e47d1027d4cdfe62b5bb43e65"
      url: "https://pub.dev"
    source: hosted
    version: "4.0.0"
  build_resolvers:
    dependency: transitive
    description:
      name: build_resolvers
      sha256: db49b8609ef8c81cca2b310618c3017c00f03a92af44c04d310b907b2d692d95
      url: "https://pub.dev"
    source: hosted
    version: "2.2.0"
  build_runner:
    dependency: "direct dev"
    description:
      name: build_runner
      sha256: "87e06c939450b9b94e3e1bb2d46e0e9780adbff5500d3969f2ba2de6bbb860cb"
      url: "https://pub.dev"
    source: hosted
    version: "2.4.2"
  build_runner_core:
    dependency: transitive
    description:
      name: build_runner_core
      sha256: "30859c90e9ddaccc484f56303931f477b1f1ba2bab74aa32ed5d6ce15870f8cf"
      url: "https://pub.dev"
    source: hosted
    version: "7.2.8"
  built_collection:
    dependency: transitive
    description:
      name: built_collection
      sha256: "376e3dd27b51ea877c28d525560790aee2e6fbb5f20e2f85d5081027d94e2100"
      url: "https://pub.dev"
    source: hosted
    version: "5.1.1"
  built_value:
    dependency: transitive
    description:
      name: built_value
      sha256: "2f17434bd5d52a26762043d6b43bb53b3acd029b4d9071a329f46d67ef297e6d"
      url: "https://pub.dev"
    source: hosted
    version: "8.5.0"
  checked_yaml:
    dependency: transitive
    description:
      name: checked_yaml
      sha256: feb6bed21949061731a7a75fc5d2aa727cf160b91af9a3e464c5e3a32e28b5ff
      url: "https://pub.dev"
    source: hosted
    version: "2.0.3"
  code_builder:
    dependency: transitive
    description:
      name: code_builder
      sha256: "0d43dd1288fd145de1ecc9a3948ad4a6d5a82f0a14c4fdd0892260787d975cbe"
      url: "https://pub.dev"
    source: hosted
    version: "4.4.0"
  collection:
    dependency: transitive
    description:
      name: collection
      sha256: "4a07be6cb69c84d677a6c3096fcf960cc3285a8330b4603e0d463d15d9bd934c"
      url: "https://pub.dev"
    source: hosted
    version: "1.17.1"
  convert:
    dependency: transitive
    description:
      name: convert
      sha256: "0f08b14755d163f6e2134cb58222dd25ea2a2ee8a195e53983d57c075324d592"
      url: "https://pub.dev"
    source: hosted
    version: "3.1.1"
  coverage:
    dependency: transitive
    description:
      name: coverage
      sha256: "2fb815080e44a09b85e0f2ca8a820b15053982b2e714b59267719e8a9ff17097"
      url: "https://pub.dev"
    source: hosted
    version: "1.6.3"
  crypto:
    dependency: transitive
    description:
      name: crypto
      sha256: ff625774173754681d66daaf4a448684fb04b78f902da9cb3d308c19cc5e8bab
      url: "https://pub.dev"
    source: hosted
    version: "3.0.3"
  dart_style:
    dependency: transitive
    description:
      name: dart_style
      sha256: f4f1f73ab3fd2afcbcca165ee601fe980d966af6a21b5970c6c9376955c528ad
      url: "https://pub.dev"
    source: hosted
    version: "2.3.1"
  file:
    dependency: transitive
    description:
      name: file
      sha256: "1b92bec4fc2a72f59a8e15af5f52cd441e4a7860b49499d69dfa817af20e925d"
      url: "https://pub.dev"
    source: hosted
    version: "6.1.4"
  fixnum:
    dependency: transitive
    description:
      name: fixnum
      sha256: "25517a4deb0c03aa0f32fd12db525856438902d9c16536311e76cdc57b31d7d1"
      url: "https://pub.dev"
    source: hosted
    version: "1.1.0"
  frontend_server_client:
    dependency: transitive
    description:
      name: frontend_server_client
      sha256: "408e3ca148b31c20282ad6f37ebfa6f4bdc8fede5b74bc2f08d9d92b55db3612"
      url: "https://pub.dev"
    source: hosted
    version: "3.2.0"
  glob:
    dependency: transitive
    description:
      name: glob
      sha256: "4515b5b6ddb505ebdd242a5f2cc5d22d3d6a80013789debfbda7777f47ea308c"
      url: "https://pub.dev"
    source: hosted
    version: "2.1.1"
  graphs:
    dependency: transitive
    description:
      name: graphs
      sha256: "772db3d53d23361d4ffcf5a9bb091cf3ee9b22f2be52cd107cd7a2683a89ba0e"
      url: "https://pub.dev"
    source: hosted
    version: "2.3.0"
  http_multi_server:
    dependency: transitive
    description:
      name: http_multi_server
      sha256: "97486f20f9c2f7be8f514851703d0119c3596d14ea63227af6f7a481ef2b2f8b"
      url: "https://pub.dev"
    source: hosted
    version: "3.2.1"
  http_parser:
    dependency: transitive
    description:
      name: http_parser
      sha256: "2aa08ce0341cc9b354a498388e30986515406668dbcc4f7c950c3e715496693b"
      url: "https://pub.dev"
    source: hosted
    version: "4.0.2"
  io:
    dependency: transitive
    description:
      name: io
      sha256: "2ec25704aba361659e10e3e5f5d672068d332fc8ac516421d483a11e5cbd061e"
      url: "https://pub.dev"
    source: hosted
    version: "1.0.4"
  js:
    dependency: transitive
    description:
      name: js
      sha256: f2c445dce49627136094980615a031419f7f3eb393237e4ecd97ac15dea343f3
      url: "https://pub.dev"
    source: hosted
    version: "0.6.7"
  json_annotation:
    dependency: transitive
    description:
      name: json_annotation
      sha256: b10a7b2ff83d83c777edba3c6a0f97045ddadd56c944e1a23a3fdf43a1bf4467
      url: "https://pub.dev"
    source: hosted
    version: "4.8.1"
  lint_visitor_generator:
    dependency: "direct dev"
    description:
      path: "../lint_visitor_generator"
      relative: true
    source: path
    version: "0.0.0"
  logging:
    dependency: transitive
    description:
      name: logging
      sha256: "04094f2eb032cbb06c6f6e8d3607edcfcb0455e2bb6cbc010cb01171dcb64e6d"
      url: "https://pub.dev"
    source: hosted
    version: "1.1.1"
  matcher:
    dependency: transitive
    description:
      name: matcher
      sha256: "6501fbd55da300384b768785b83e5ce66991266cec21af89ab9ae7f5ce1c4cbb"
      url: "https://pub.dev"
    source: hosted
    version: "0.12.15"
  meta:
    dependency: "direct main"
    description:
      name: meta
      sha256: "3c74dbf8763d36539f114c799d8a2d87343b5067e9d796ca22b5eb8437090ee3"
      url: "https://pub.dev"
    source: hosted
    version: "1.9.1"
  mime:
    dependency: transitive
    description:
      name: mime
      sha256: e4ff8e8564c03f255408decd16e7899da1733852a9110a58fe6d1b817684a63e
      url: "https://pub.dev"
    source: hosted
    version: "1.0.4"
  node_preamble:
    dependency: transitive
    description:
      name: node_preamble
      sha256: "6e7eac89047ab8a8d26cf16127b5ed26de65209847630400f9aefd7cd5c730db"
      url: "https://pub.dev"
    source: hosted
    version: "2.0.2"
  package_config:
    dependency: transitive
    description:
      name: package_config
      sha256: "1c5b77ccc91e4823a5af61ee74e6b972db1ef98c2ff5a18d3161c982a55448bd"
      url: "https://pub.dev"
    source: hosted
    version: "2.1.0"
  path:
    dependency: transitive
    description:
      name: path
      sha256: "8829d8a55c13fc0e37127c29fedf290c102f4e40ae94ada574091fe0ff96c917"
      url: "https://pub.dev"
    source: hosted
    version: "1.8.3"
  pool:
    dependency: transitive
    description:
      name: pool
      sha256: "20fe868b6314b322ea036ba325e6fc0711a22948856475e2c2b6306e8ab39c2a"
      url: "https://pub.dev"
    source: hosted
    version: "1.5.1"
  protobuf:
    dependency: transitive
    description:
      name: protobuf
      sha256: "01dd9bd0fa02548bf2ceee13545d4a0ec6046459d847b6b061d8a27237108a08"
      url: "https://pub.dev"
    source: hosted
    version: "2.1.0"
  pub_semver:
    dependency: transitive
    description:
      name: pub_semver
      sha256: "40d3ab1bbd474c4c2328c91e3a7df8c6dd629b79ece4c4bd04bee496a224fb0c"
      url: "https://pub.dev"
    source: hosted
    version: "2.1.4"
  pubspec_parse:
    dependency: transitive
    description:
      name: pubspec_parse
      sha256: c63b2876e58e194e4b0828fcb080ad0e06d051cb607a6be51a9e084f47cb9367
      url: "https://pub.dev"
    source: hosted
    version: "1.2.3"
  shelf:
    dependency: transitive
    description:
      name: shelf
      sha256: ad29c505aee705f41a4d8963641f91ac4cee3c8fad5947e033390a7bd8180fa4
      url: "https://pub.dev"
    source: hosted
    version: "1.4.1"
  shelf_packages_handler:
    dependency: transitive
    description:
      name: shelf_packages_handler
      sha256: "89f967eca29607c933ba9571d838be31d67f53f6e4ee15147d5dc2934fee1b1e"
      url: "https://pub.dev"
    source: hosted
    version: "3.0.2"
  shelf_static:
    dependency: transitive
    description:
      name: shelf_static
      sha256: a41d3f53c4adf0f57480578c1d61d90342cd617de7fc8077b1304643c2d85c1e
      url: "https://pub.dev"
    source: hosted
    version: "1.1.2"
  shelf_web_socket:
    dependency: transitive
    description:
      name: shelf_web_socket
      sha256: "9ca081be41c60190ebcb4766b2486a7d50261db7bd0f5d9615f2d653637a84c1"
      url: "https://pub.dev"
    source: hosted
    version: "1.0.4"
  source_gen:
    dependency: transitive
    description:
      name: source_gen
      sha256: "373f96cf5a8744bc9816c1ff41cf5391bbdbe3d7a96fe98c622b6738a8a7bd33"
      url: "https://pub.dev"
    source: hosted
    version: "1.3.2"
  source_map_stack_trace:
    dependency: transitive
    description:
      name: source_map_stack_trace
      sha256: "84cf769ad83aa6bb61e0aa5a18e53aea683395f196a6f39c4c881fb90ed4f7ae"
      url: "https://pub.dev"
    source: hosted
    version: "2.1.1"
  source_maps:
    dependency: transitive
    description:
      name: source_maps
      sha256: "708b3f6b97248e5781f493b765c3337db11c5d2c81c3094f10904bfa8004c703"
      url: "https://pub.dev"
    source: hosted
    version: "0.10.12"
  source_span:
    dependency: transitive
    description:
      name: source_span
      sha256: "53e943d4206a5e30df338fd4c6e7a077e02254531b138a15aec3bd143c1a8b3c"
      url: "https://pub.dev"
    source: hosted
    version: "1.10.0"
  stack_trace:
    dependency: transitive
    description:
      name: stack_trace
      sha256: c3c7d8edb15bee7f0f74debd4b9c5f3c2ea86766fe4178eb2a18eb30a0bdaed5
      url: "https://pub.dev"
    source: hosted
    version: "1.11.0"
  stream_channel:
    dependency: transitive
    description:
      name: stream_channel
      sha256: "83615bee9045c1d322bbbd1ba209b7a749c2cbcdcb3fdd1df8eb488b3279c1c8"
      url: "https://pub.dev"
    source: hosted
    version: "2.1.1"
  stream_transform:
    dependency: transitive
    description:
      name: stream_transform
      sha256: "14a00e794c7c11aa145a170587321aedce29769c08d7f58b1d141da75e3b1c6f"
      url: "https://pub.dev"
    source: hosted
    version: "2.1.0"
  string_scanner:
    dependency: transitive
    description:
      name: string_scanner
      sha256: "556692adab6cfa87322a115640c11f13cb77b3f076ddcc5d6ae3c20242bedcde"
      url: "https://pub.dev"
    source: hosted
    version: "1.2.0"
  term_glyph:
    dependency: transitive
    description:
      name: term_glyph
      sha256: a29248a84fbb7c79282b40b8c72a1209db169a2e0542bce341da992fe1bc7e84
      url: "https://pub.dev"
    source: hosted
    version: "1.2.1"
  test:
    dependency: "direct dev"
    description:
      name: test
      sha256: "4f92f103ef63b1bbac6f4bd1930624fca81b2574464482512c4f0896319be575"
      url: "https://pub.dev"
    source: hosted
    version: "1.24.2"
  test_api:
    dependency: transitive
    description:
      name: test_api
      sha256: daadc9baabec998b062c9091525aa95786508b1c48e9c30f1f891b8bf6ff2e64
      url: "https://pub.dev"
    source: hosted
    version: "0.5.2"
  test_core:
    dependency: transitive
    description:
      name: test_core
      sha256: "3642b184882f79e76ca57a9230fb971e494c3c1fd09c21ae3083ce891bcc0aa1"
      url: "https://pub.dev"
    source: hosted
    version: "0.5.2"
  timing:
    dependency: transitive
    description:
      name: timing
      sha256: "70a3b636575d4163c477e6de42f247a23b315ae20e86442bebe32d3cabf61c32"
      url: "https://pub.dev"
    source: hosted
    version: "1.0.1"
  typed_data:
    dependency: transitive
    description:
      name: typed_data
      sha256: facc8d6582f16042dd49f2463ff1bd6e2c9ef9f3d5da3d9b087e244a7b564b3c
      url: "https://pub.dev"
    source: hosted
    version: "1.3.2"
  vm_service:
    dependency: transitive
    description:
      name: vm_service
      sha256: "1311639ad908dfdcb64734ac1fbd60416234c06e4351846783a79c56848a5185"
      url: "https://pub.dev"
    source: hosted
    version: "11.7.0"
  watcher:
    dependency: transitive
    description:
      name: watcher
      sha256: "6a7f46926b01ce81bfc339da6a7f20afbe7733eff9846f6d6a5466aa4c6667c0"
      url: "https://pub.dev"
    source: hosted
    version: "1.0.2"
  web_socket_channel:
    dependency: transitive
    description:
      name: web_socket_channel
      sha256: d88238e5eac9a42bb43ca4e721edba3c08c6354d4a53063afaa568516217621b
      url: "https://pub.dev"
    source: hosted
    version: "2.4.0"
  webkit_inspection_protocol:
    dependency: transitive
    description:
      name: webkit_inspection_protocol
      sha256: "67d3a8b6c79e1987d19d848b0892e582dbb0c66c57cc1fef58a177dd2aa2823d"
      url: "https://pub.dev"
    source: hosted
    version: "1.2.0"
  yaml:
    dependency: transitive
    description:
      name: yaml
      sha256: "75769501ea3489fca56601ff33454fe45507ea3bfb014161abc3b43ae25989d5"
      url: "https://pub.dev"
    source: hosted
    version: "3.1.2"
sdks:
  dart: ">=3.0.0-134.0.dev <4.0.0"
</details>

**Comment by rrousselGit** [comment] 2023-05-12 08:52
This reproducible example is taken from an existing repository. The code generator worked for sure before the upgrade. There are multiple published versions of the package on pub with the correctly generated files

**Comment by rrousselGit** [comment] 2023-05-12 09:06
This appears to be caused by `graphs`, where downgrading the package fixes the issue.

**Comment by astubenbord** [comment] 2023-05-12 09:56
I can reprooduce this and there seems to be a workaround. I am using freezed with hive.
Since upgrading to flutter 3.10.0 and dart 3.0.0, Hive type adapters are not correctly generated anymore. 
With flutter 3.7.10, everything worked as expected.

**To Reproduce**
I created three classes with the different ways to use Hive with and without freezed. 

```dart
part 'non_freezed_class.g.dart';

@HiveType(typeId: 2)
class NonFreezedClass {
  @HiveField(1)
  final String value;

  NonFreezedClass(this.value);
}
```
Here, the type adapter is correctly generated in the `non_freezed_class.g.dart` file.

Then, a freezed class with a single constructor:
```dart
part 'my_model.g.dart';
part 'my_model.freezed.dart';

@freezed
@HiveType(typeId: 1)
class MyModel with _$MyModel {
  const factory MyModel({
    @HiveField(0) required String value,
  }) = _MyModel;
}
```
Here, the type adapter is generated, but the `@HiveField` annotation on the field `value` is ignored, resulting in the following implementation of the type adapter's `read` method. You can see that the required parameter is not passed into the `MyModel()` constructor. The freezed part (i.e. copyWith etc.) is correctly generated as expected.
```dart
  @override
  MyModel read(BinaryReader reader) {
    final numOfFields = reader.readByte();
    final fields = <int, dynamic>{
      for (int i = 0; i < numOfFields; i++) reader.readByte(): reader.read(),
    };
    return MyModel();
  }
```

Lastly, a sealed class: 

```dart
part 'my_sealed_class.g.dart';
part 'my_sealed_class.freezed.dart';

@freezed
class MySealedClass with _$MySealedClass {
  @HiveType(typeId: 3)
  const factory MySealedClass.first({@HiveField(0) required String firstValue}) = _First;

  @HiveType(typeId: 4)
  const factory MySealedClass.second(@HiveField(0) String secondValue) = _Second;

  @HiveType(typeId: 5)
  const factory MySealedClass.third() = _Third;
}
```
Here, the part 'my_sealed_class.g.dart' is not even generated. 

**Expected behavior**
The type adapters should be correctly generated.


**Findings** 
When trying to run `dart run build_runner build` on a clean working set  (i.e. no files generated yet), the behavior as described above can be observed. Running it multiple times in succession does not make any difference. However, I have found that when running `dart run build_runner watch` the behavior is different. 
I could get it to work with the following steps:
1. Start with a clean working set, i.e. clean asset graph and no generated files. 
2. Let `dart run build_runner watch` finish generating (until it prints success)
3.  Change a hive related value in the class (e.g. change the field id or the typeId of the class). Other changes do not work, like changing a field's name
4. Save the file and wait for build runner to correctly generate the type adapter _related to only this file_!

Also, as you said, forcing a dependency overwrite of graph also fixes this issue.

**Comment by kaankoken** [comment] 2023-05-12 13:15
> I can reprooduce this and there seems to be a workaround. I am using freezed with hive. Since upgrading to flutter 3.10.0 and dart 3.0.0, Hive type adapters are not correctly generated anymore. With flutter 3.7.10, everything worked as expected.
> 
> **To Reproduce** I created three classes with the different ways to use Hive with and without freezed.
> 
> ```dart
> part 'non_freezed_class.g.dart';
> 
> @HiveType(typeId: 2)
> class NonFreezedClass {
>   @HiveField(1)
>   final String value;
> 
>   NonFreezedClass(this.value);
> }
> ```
> 
> Here, the type adapter is correctly generated in the `non_freezed_class.g.dart` file.
> 
> Then, a freezed class with a single constructor:
> 
> ```dart
> part 'my_model.g.dart';
> part 'my_model.freezed.dart';
> 
> @freezed
> @HiveType(typeId: 1)
> class MyModel with _$MyModel {
>   const factory MyModel({
>     @HiveField(0) required String value,
>   }) = _MyModel;
> }
> ```
> 
> Here, the type adapter is generated, but the `@HiveField` annotation on the field `value` is ignored, resulting in the following implementation of the type adapter's `read` method. You can see that the required parameter is not passed into the `MyModel()` constructor. The freezed part (i.e. copyWith etc.) is correctly generated as expected.
> 
> ```dart
>   @override
>   MyModel read(BinaryReader reader) {
>     final numOfFields = reader.readByte();
>     final fields = <int, dynamic>{
>       for (int i = 0; i < numOfFields; i++) reader.readByte(): reader.read(),
>     };
>     return MyModel();
>   }
> ```
> 
> Lastly, a sealed class:
> 
> ```dart
> part 'my_sealed_class.g.dart';
> part 'my_sealed_class.freezed.dart';
> 
> @freezed
> class MySealedClass with _$MySealedClass {
>   @HiveType(typeId: 3)
>   const factory MySealedClass.first({@HiveField(0) required String firstValue}) = _First;
> 
>   @HiveType(typeId: 4)
>   const factory MySealedClass.second(@HiveField(0) String secondValue) = _Second;
> 
>   @HiveType(typeId: 5)
>   const factory MySealedClass.third() = _Third;
> }
> ```
> 
> Here, the part 'my_sealed_class.g.dart' is not even generated.
> 
> **Expected behavior** The type adapters should be correctly generated.
> 
> **Findings** When trying to run `dart run build_runner build` on a clean working set (i.e. no files generated yet), the behavior as described above can be observed. Running it multiple times in succession does not make any difference. However, I have found that when running `dart run build_runner watch` the behavior is different. I could get it to work with the following steps:
> 
> 1. Start with a clean working set, i.e. clean asset graph and no generated files.
> 2. Let `dart run build_runner watch` finish generating (until it prints success)
> 3. Change a hive related value in the class (e.g. change the field id or the typeId of the class). Other changes do not work, like changing a field's name
> 4. Save the file and wait for build runner to correctly generate the type adapter _related to only this file_!
> 
> Also, as you said, forcing a dependency overwrite of graph also fixes this issue.

I am using flutter: `3.7.6` & all packages that we use do not have caret (everything is in a fixed version). we are still faced with the same issue. I think it is not related to the Flutter version & @rrousselGit mentioned, it totally depends on the `graph`

**Comment by jakemac53** [comment] 2023-05-12 15:46
I am looking into this

**Comment by jakemac53** [comment] 2023-05-12 15:50
@rrousselGit it looks like explicitly specifying `runs_before` does solve the problem, in the builder definition in 
`lint_visitor_generator/build.yaml`:

```dart
    runs_before:
    - source_gen|combining_builder
```

I can't remember if `applies_builders` is supposed to imply this though.

**Comment by jakemac53** [comment] 2023-05-12 16:04
Ok, so the actual problem here is a misconfigured `build_extensions` in the `lint_visitor_generator/build.yaml`, it is currently:

``` yaml
    build_extensions: { ".dart": [".lint_visitor_generator.g.dart"] }
```

but it should be:

``` yaml
    build_extensions: { ".dart": [".lint_visitor_generator.g.part"] }
```

The difference being `.g.part` instead of `.g.dart`. This is important, because the `source_gen|combining_builder` has this configuration `required_inputs: [".g.part"]` which ensures things that generate these ".g.part" files run before it.

Obviously it is an easy mistake to make though.

**Comment by jakemac53** [comment] 2023-05-12 16:05
Note that running `dart run build_runner doctor` would notify you of this mismatch, but we don't do the check as a part of normal builds.

I can't remember exactly why we don't, cc @natebosch? What if we only did it when generating the build script?

**Comment by jakemac53** [comment] 2023-05-12 16:11
cc @kevmoo another option here is we could update the docs for source_gen to suggest putting in an explicit `runs_before`, which while not technically necessary might still help keep things on the rails when there are mistakes like this.

**Comment by natebosch** [comment] 2023-05-12 17:37
> I can't remember exactly why we don't

I think this is at least in part because there are valid reasons for the build extensions in `build.yaml` to not match perfectly with the `Builder` instances. See https://github.com/dart-lang/build/issues/590#issuecomment-480047797

**Comment by rrousselGit** [comment] 2023-05-12 18:37
That's funky. Let me check if that issue is consistent with the other projects where I've seen this happen

**Comment by rrousselGit** [comment] 2023-05-12 18:40
Indeed, looks like I made the same mistake in the other generator facing this issue.

I guess that can be closed then, my bad.

Although that's quite a common mistake I would say.
I know I've made the same typo (part vs dart) before. The words being so close to each other that, even knowing it should be "part", my mind still is tempted to write "dart" due to familiarity

**Comment by jakemac53** [comment] 2023-05-12 18:55
I definitely agree its a very easy mistake, and since we give no warning by default, its really not your fault.

You (and other codegen authors) may want to consider running `dart run build_runner doctor` on CI though? It should help with issues like this.

**Comment by jakemac53** [comment] 2023-05-12 18:57
I almost wonder if we should actually consider flattening build stages just to provide more consistent behavior here? It might actually speed up builds too.

Basically the result would be that a builder can never see files from builders that it doesn't explicitly depend on (either via required_inputs or by being the target of a runs_before config). That way at least we would have consistent behavior that isn't dependent on this unspecified ordering.

**Comment by rrousselGit** [comment] 2023-05-12 19:21
I'll definitely run the doctor command in the CI from now on.
But I'll be honest, I didn't know it existed.

**Comment by jakemac53** [comment] 2023-05-12 19:31
> But I'll be honest, I didn't know it existed.

Well, apparently it is a hidden command? So I can't blame you, lol. We might want to re-evaluate that.

**Comment by jakemac53** [comment] 2023-05-12 21:53
I am going to close this issue, even though it sucks to get broken like this, it isn't something we can easily do anything about. I did make the `doctor` command public which hopefully should help.

**Closed by jakemac53** 2023-05-12 21:53 UTC
