### ISSUE TITLE
Can't run build_runner because BuildForInputLogger

### ISSUE THREAD

**Issue by water-user** [dart-lang/build#3519] opened 2023-05-24 14:42 UTC
I'm using objectbox package, i'm trying to run build_runner and i'm getting error:
```
../../../../AppData/Local/Pub/Cache/hosted/pub.dev/build_runner_core-7.2.7/lib/src/logging/build_for_input_logger.dart:13:7: Error: The non-abstract class 'BuildForInputLogger' is missing implementations for these members:
 - Logger.onLevelChanged
Try to either
 - provide an implementation,
 - inherit an implementation from a superclass or mixin,
 - mark the class as abstract, or
 - provide a 'noSuchMethod' implementation.

class BuildForInputLogger implements Logger {
      ^^^^^^^^^^^^^^^^^^^
../../../../AppData/Local/Pub/Cache/hosted/pub.dev/logging-1.2.0/lib/src/logger.dart:162:22: Context: 'Logger.onLevelChanged' is defined here.
  Stream<Level?> get onLevelChanged {
                     ^^^^^^^^^^^^^^
pub finished with exit code 1
PS C:\Users\Daniel\AndroidStudioProjects\water-io-flutter\projects\water-io-hydration-flutter>
```
In order to route, prioritize, and act on this as soon as possible please include:

* Dart SDK Version: **Dart SDK version: 2.19.2 (stable) (Tue Feb 7 18:37:17 2023 +0000) on "windows_x64"**
* What package(s) from this repo you are using: **build_runner 2.3.3**
* I'm running `flutter pub run build_runner build` to generate .g.dart for objectbox package. 
* Windows
* Chrome

In other computers of my team it's working without any problem, only in my computer it's getting this error. how can i fix it? Thanks!

**Comment by jakemac53** [comment] 2023-05-24 14:44
Please run a `dart pub upgrade`, that should give you a newer version of build_runner_core with the fix

**Comment by fehmidevoteam** [comment] 2023-05-24 14:51
I have the same error 
pub-cache/hosted/pub.dev/build_runner_core-7.2.7/lib/src/logging/build_for_input_logger.dart:13:7: Error: The non-abstract class 'BuildForInputLogger' is missing implementations for these members:
 - Logger.onLevelChanged

**Comment by fehmidevoteam** [comment] 2023-05-24 15:12
@jakemac53 actually we couldn't migrate to 3.10.1. I don't think that is related to flutter version. Because it was fine before. and we are also using a specific versions of so i didn't think it is a compatibility versions problem:
freezed_annotation: 2.1.0
freezed: 2.1.0+1
build_runner: 2.2.1

**Comment by jakemac53** [comment] 2023-05-24 15:22
> actually we couldn't migrate to 3.10.1

of what sdk/package?

> we are also using a specific versions of so i didn't think it is a compatibility versions problem

The issue is that a version of a transitive dependency broke build_runner_core (with a change that isn't generally considered breaking, adding a member to a class that wasn't intended to be implemented).

What is actually breaking you is pinning build_runner to a specific version here - you need to get the latest build_runner_core which isn't allowed by your pinned version of build_runner.

Generally, if you want to pin packages you should just use your `pubspec.lock` file to do that, so that all transitive deps are pinned. Pinning only specific packages causes more problems than it solves generally.

**Comment by adar2378** [comment] 2023-05-24 15:55
Is there any update? Could we fix this without upgrading to Flutter 3.10.0 immediately?

**Comment by jakemac53** [comment] 2023-05-24 16:05
Re-opened this for now to help reduce duplicate issues and also because clearly some people still are having issues.

**Comment by bahag-chandrana** [comment] 2023-05-24 16:23
@jakemac53  after adding `build_runner_core` to the dependency, running `flutter pub upgrade` following is the error I see

```
Resolving dependencies...
The current Dart SDK version is 2.19.6.

Because build_runner >=2.1.0 <2.1.7 depends on build >=2.1.0 <2.2.0 and build_runner >=2.1.10 <2.4.0 depends on build >=2.1.0 <2.4.0, build_runner >=2.1.0 <2.1.7-∞ or >=2.1.10 <2.4.0-∞ requires build >=2.1.0 <2.4.0.
And because build_runner >=2.1.7 <2.1.10 depends on build >=2.1.0 <2.3.0 and build_runner >=1.12.0 <2.1.0 depends on build >=2.0.0 <2.1.0, build_runner >=1.12.0 <2.4.0 requires build >=2.0.0 <2.1.0 or >=2.1.0 <2.4.0.
And because build_runner >=0.9.1+1 <1.12.2 depends on dart_style ^1.0.0 and build_runner_core >=7.2.8 depends on build ^2.4.0, if build_runner >=0.9.1+1 <2.4.0 and build_runner_core >=7.2.8 then dart_style ^1.0.0.
And because json_serializable >=4.1.0 <6.7.0 depends on source_gen ^1.0.0 which depends on dart_style ^2.0.0, one of build_runner >=0.9.1+1 <2.4.0 or build_runner_core >=7.2.8 or json_serializable >=4.1.0 <6.7.0 must be false.
And because json_serializable >=6.7.0 requires SDK version ^3.0.0 and build_runner <0.9.1+1 requires SDK version >=1.9.1 <2.0.0-∞, one of build_runner_core >=7.2.8 or json_serializable >=4.1.0 or build_runner <2.4.0 must be false.
And because build_runner >=2.4.0 requires SDK version >=3.0.0-134.0.dev <4.0.0 and assets_master_data_api depends on json_serializable ^6.1.4, build_runner_core >=7.2.8 is incompatible with build_runner.
So, because assets_master_data_api depends on both build_runner any and build_runner_core ^7.2.9, version solving failed.
```

And my pubspec.yaml config

```yaml

environment:
  sdk: '>=2.14.0 <3.0.0'

dependencies:
  dio: '>=4.0.1 <5.0.0'
  freezed_annotation: '^2.0.3'
  json_annotation: '^4.4.0'

dev_dependencies:
  freezed: '^2.0.3'
  json_serializable: '^6.1.4'
  build_runner: any
  build_runner_core: ^7.2.9
  test: ^1.16.0
```

**Comment by jakemac53** [comment] 2023-05-24 16:35
Ah I see, thanks @bahag-chandrana . It looks like we need to backport a hotfix for a version of build_runner_core that is compatible with a version of build_runner that supports Dart 2.19.

That way users on flutter 3.7 can get a version that works

**Comment by bahag-chandrana** [comment] 2023-05-24 16:40
Thank you so much @jakemac53. That would be great.

**Comment by jakemac53** [comment] 2023-05-24 16:48
Ok, it actually looks like build_runner 2.3.3 _is_ compatible with build_runner_core 7.2.9, so its something a bit more subtle than I originally thought and we may need a fix from one of these builder packages. I will keep investigating here though and file any requisite issues. If they are in dart-lang repos I can also do the fixes.

Stay tuned!

**Comment by jakemac53** [comment] 2023-05-24 17:16
@bahag-chandrana @fehmidevoteam If one of you could try out my backport PR that would be great, I think adding this should do it:

```yaml
dependency_overrides:
  build_runner_core:
    git:
      url: https://github.com/dart-lang/build.git
      ref: build_runner_core-backport
      path: build_runner_core/
```

That working for you doesn't actually guarantee the version solve will work in the real world, but its still worth validating.

**Comment by jakemac53** [comment] 2023-05-24 17:20
Ok @bahag-chandrana (ignore previous comment I deleted) can you try a `flutter pub upgrade` now? (without any overrides). Hopefully you get `build_runner_core` version 7.2.7+1

**Comment by diegohzea** [comment] 2023-05-24 17:23
> Ok @bahag-chandrana (ignore previous comment I deleted) can you try a `flutter pub upgrade` now? (without any overrides). Hopefully you get `build_runner_core` version 7.2.7+1

It works for me now, thanks!

**Comment by jakemac53** [comment] 2023-05-24 17:41
Whoops - re-opened just to help prevent dupes for a while, marking as needs-input so it closes itself in a while also once things calm down.

**Comment by bahag-chandrana** [comment] 2023-05-24 20:22
> Ok @bahag-chandrana (ignore previous comment I deleted) can you try a `flutter pub upgrade` now? (without any overrides). Hopefully you get `build_runner_core` version 7.2.7+1

I can also confirm, it works now. Thank you once again @jakemac53 for a quick fix 👍🏽 ❤️ .

**Comment by fehmidevoteam** [comment] 2023-05-25 07:25
it is so strange, the issue was fixed without any change 😵‍💫

**Comment by twisstosin** [comment] 2023-06-12 10:42
I'm still experiencing this issue, with flutter version `3.10.4`
I've also run `flutter pub upgrade` , cleared pub cache, deleted pubspec.lock, reinstalled packages.

this override workaround is the only thing I've tried that works right now - 
https://github.com/dart-lang/build/issues/3529#issuecomment-1576559719

**Comment by jakemac53** [comment] 2023-06-12 14:57
@twisstosin can you add `build_runner_core: ^7.2.9` to your dev dependencies and then paste the error you get on `flutter pub upgrade` here (assuming you get one?). You need that version to get the fix, but likely some other package has a constraint that is preventing you from getting it.

**Closed** 2023-07-20 08:06 UTC
Labels: needs-info

**Comment by deep-mangukiya** [comment] 2023-07-26 09:54
![Uploading Screenshot 2023-07-26 at 3.22.00 PM.png…]()

% flutter pub run build_runner build --delete-conflicting-outputs
Deprecated. Use `dart run` instead.
Building package executable... 
Failed to build build_runner:build_runner:
../../.pub-cache/hosted/pub.dev/build_runner_core-7.2.8/lib/src/logging/build_for_input_logger.dart:13:7: Error: The non-abstract class 'BuildForInputLogger' is missing implementations for these members:
 - Logger.onLevelChanged
Try to either
 - provide an implementation,
 - inherit an implementation from a superclass or mixin,
 - mark the class as abstract, or
 - provide a 'noSuchMethod' implementation.

class BuildForInputLogger implements Logger {
      ^^^^^^^^^^^^^^^^^^^
../../.pub-cache/hosted/pub.dev/logging-1.2.0/lib/src/logger.dart:162:22: Context: 'Logger.onLevelChanged' is defined here.
  Stream<Level?> get onLevelChanged {
                     ^^^^^^^^^^^^^^
                     
                     
i try every thing but no change to anything.
same error.

cab you help me.

**Comment by jakemac53** [comment] 2023-07-26 14:47
@deep-mangukiya you need at least build_runner version 7.2.9 to work with logging 1.2.0, add `build_runner_core: ^7.2.9` to your dev_dependencies and run `flutter pub upgrade`

**Comment by deep-mangukiya** [comment] 2023-07-27 04:02
@jakemac53
 I have Two system - mac m1 and - windows.
same code both system, windows system work properly. but i have use same code in mac m1 and use same commend line than show error.

i have use this commend line : flutter pub run build_runner build 

can have outside set up for this commend ??.

**Comment by deep-mangukiya** [comment] 2023-07-27 04:03
@jakemac53
 I have Two system - mac m1 and - windows.
same code both system, windows system work properly. but i have use same code in mac m1 and use same commend line than show error.

i have use this commend line : flutter pub run build_runner build 

can have outside set up for this commend ??.

**Comment by jakemac53** [comment] 2023-07-27 14:40
> i don't use build_runner_core package.

You do use it, just not directly. You shouldn't _need_ the dependency constraint, but adding it would at a minimum surface the real problem (why you can't get the latest version). You absolutely must get at least version 7.2.9 of that package, I can guarantee to you that this is the problem.

**Comment by Frabbi727** [comment] 2023-09-18 06:09
1. **flutter upgrade**
2. **dart pub upgrade** 
3. **dart pub outdated** 
4. **dart pub upgrade --major-versions** 
then run the :
**flutter packages pub run build_runner build --delete-conflicting-outputs**
If your are using the **dio** old version, then read the documents and update dio class as per documentations,

**Comment by CodeK254** [comment] 2023-11-02 13:56
Works 100%

**Comment by mtbfm** [comment] 2024-07-08 13:38
Works 100%

**Comment by jatesun** [comment] 2025-02-23 06:00
> 1. **flutter upgrade**
> 2. **dart pub upgrade**
> 3. **dart pub outdated**
> 4. **dart pub upgrade --major-versions**
>    then run the :
>    **flutter packages pub run build_runner build --delete-conflicting-outputs**
>    If your are using the **dio** old version, then read the documents and update dio class as per documentations,

these works well 2025,thanks
