### ISSUE TITLE
Null Safety

### ISSUE THREAD

**Issue by felixwortmann** [dart-lang/build#3026] opened 2021-03-05 23:00 UTC
Please migrate this package to Null-Safety.
https://dart.dev/null-safety/migration-guide

**Comment by MarlonJD** [comment] 2021-03-06 03:51
We cannot using build runner on flutter 2.0.0 or 2.0.1, we need update

**Comment by simolus3** [comment] 2021-03-06 10:35
Duplicate of #2920. The `build`, `build_resolvers` and `build_test` packages have been migrated and will be released in the next weeks (afaik).

> We cannot using build runner on flutter 2.0.0 or 2.0.1, we need update

You can use the current `build_runner` with Flutter 2.

**Closed** 2021-03-09 18:10 UTC
