### ISSUE TITLE
Error: The class 'FileSystemEvent' can't be extended, implemented, or mixed in outside of its library because it's a sealed class.

### ISSUE THREAD

**Issue by cuneyt0** [dart-lang/build#3563] opened 2023-08-21 07:22 UTC
Hi, when I upgrade to Flutter 3.13 I get the error Error: The class 'FileSystemEvent' can't be extended, implemented, or mixed in outside of its library because it's a sealed class.

**Comment by josemiguelvarela** [comment] 2023-08-21 08:26
I solved this issue upgrading build_runner to latest version `build_runner: ^2.4.6`.

You can also try overriding `watcher` if upgrading `build_runner` doesn't work
```
dependency_overrides:
  watcher: ^1.1.0
```

Probably the problem is with some other dependency that is using an old version of watcher, but I'm not sure.

**Comment by cuneyt0** [comment] 2023-08-21 08:31
I will try. Thank you.

**Comment by jakemac53** [comment] 2023-08-21 14:35
Yeah this is an issue related to outdated dependencies, I am going to close this but feel free to chime in if you need more help updating watcher.

**Closed by jakemac53** 2023-08-21 14:35 UTC
