### ISSUE TITLE
Get clean on Dart2

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/build#1482] opened 2018-05-23 17:41 UTC
- [x] Land latest pub in SDK - https://dart-review.googlesource.com/c/sdk/+/56292
- [x] Get a new pkg:watcher out - 0.9.7+8
- [x] Publish SDK w/ https://dart-review.googlesource.com/c/sdk/+/56292
    - should be in -dev.58
- [x] Fix YamlMap convert error w/ build_config - https://github.com/dart-lang/build/issues/1293
- [x] build_web_compilers issue: https://github.com/dart-lang/build/issues/1487
- [x] build_runner - https://github.com/dart-lang/build/issues/1488
- [x] build_web_compilers - https://github.com/dart-lang/build/issues/1513

**Comment by natebosch** [comment] 2018-05-23 17:48
Dupe of #1293

**Comment by kevmoo** [comment] 2018-05-23 17:55
Humor the PM – I'll track this...

**Comment by kevmoo** [comment] 2018-05-24 21:10
Sample build running now that #1293 is fixed - https://travis-ci.org/dart-lang/build/builds/383404287

**Comment by jakemac53** [comment] 2018-06-13 13:36
All the checkboxes above are checked off now - rerunning the build to see if we have issues still

**Comment by kevmoo** [comment] 2018-06-13 14:22
Woo hoo!

**Comment by jakemac53** [comment] 2018-06-13 14:27
Looks like some failing e2e tests still so we can leave this open, but at least all the unit tests are passing now so that is good :)

**Comment by kevmoo** [comment] 2018-06-13 15:00
Woo hoo!

**Comment by natebosch** [comment] 2018-06-20 20:45
Everything seems to pass for me now.

**Closed by natebosch** 2018-06-20 20:45 UTC
Labels: P1 high
