### ISSUE TITLE
Bump `frontend_server_client` to `^4.0.0`

### ISSUE THREAD

**Issue by rrousselGit** [dart-lang/build#3745] opened 2024-09-01 16:17 UTC
Cf https://github.com/dart-lang/build/issues/3733#issuecomment-2272082820

At the moment, `build_runner` specifies:

```yaml
dependencies:
  [...]
  frontend_server_client: ">=3.0.0 <5.0.0"
```

But it seems like only `^4.0.0` is supported, as per the above issue.  
This confuses `pub get` into thinking that `frontend_server_client: 3.0.0` and `build_runner` are compatible, when they aren't.

The minimum version probably should be bumped to match what is actually supported.

Note: It could be that the true culprit is another package. In the scenario where `frontend_server_client: 3.0.0` is supported by build_runner, maybe a separate package that build_runner depends on is the one that needs to bump its `frontend_server_client` dependency.

**Comment by jakemac53** [comment] 2024-09-03 16:39
The issue is related to frontend_server_client specifically and its support of certain SDKs (where older versions don't work on newer SDKs). Having a constraint in build_runner on more recent versions won't actually help anybody here. In general, package constraints should be used to signal the specific compatibilities of a package with another package, and this package is compatible with 3.x and 4.x versions of frontend_server.

- For a new pub solve, or any `pub upgrade` they will get the latest version that is solvable anyways.
  - If they couldn't solve for >4.x the suggested constraint will just end up with them getting an older build_runner which is strictly worse.
- For checked in `pubspec.lock` files, there is no benefit (they will be on an older build_runner that allows the full range of frontend_server anyways)

Because of this bumping constraints in an attempt to force users to pick up bug fixes in dependencies doesn't actually provide any benefit it just causes churn.

**Closed by jakemac53** 2024-09-03 16:39 UTC

**Comment by jakemac53** [comment] 2024-09-03 16:56
Yes, `frontend_server_client` should have tighter SDK constraints - and it used to. However, at some point it was expanded by mistake.

Once you have a single version published which does allow any SDK <4.0.0, you cannot meaningfully reduce the constraint any longer in future versions, because the result is people just get that _even older_ version of your package.

So, at least until the 4.x SDK, we are unfortunately stuck with just responding to issues and telling people to upgrade.

The issue is with frontend_server_client though, not this package. If you have a suggestion for a way to fix it in that package feel free to file an issue, but just adding an upper constraint now won't help.

**Comment by jakemac53** [comment] 2024-09-03 17:06
> As it is, `pub downgrade` is effectively broken.

I would suggest adding a `frontend_server_client` constraint of your own to resolve this (in dev_dependencies). It is a bit weird to have to do that for a transitive dependency, but it is also not all that unexpected to have to do so if you want `pub downgrade` to work - you are explicitly asking for older versions which might not have necessary bug fixes.

**Comment by rrousselGit** [comment] 2024-09-03 17:09
I wish we were able to retract packages for longer than 7 days or that we could update constraints after publishing.
I've had constraints mistakes before and solved them by retracting the package, then publishing a new version with fixed constraints. But frontend_server_client is 5 months old, so that's not going to work (unless Google uses some super privileges)


Anyway, when is it that we need to use `frontend_server_client <4.0.0` then? Are there specific SDK versions?
Because as I said, I'm running my CIs in a matrix of various Dart/Flutter and package versions.  
If I add a `frontend_server_client: ^4.0.0`, that will decrease the probability that my CI will meaningfully fail when testing against `pub downgrade`. As if I use a dependency that's also used by `frontend_server_client`, `pub downgrade` may not be able to downgrade that dependency far enough to spot the problem.

**Comment by rrousselGit** [comment] 2024-09-03 17:12
For example, I use `async: ^2.0.0` and `path: 1.0.0`. But having the CI run against`frontend_server_client: 4.0.0` would force those deps to respectively `^2.5.0` and `^1.8.0`

So if my package is incompatible with `async: >=2.0.0<2.5.0` and `path: >=1.0.0 <1.8.0`, I wouldn't know about it.

**Comment by jakemac53** [comment] 2024-09-03 17:23
> I wish we were able to retract packages for longer than 7 days or that we could update constraints after publishing.

Yes in particular being able to update the upper SDK constraint any point arbitrarily long after publishing a package would be super helpful. But, it could also be generalized such that you could add arbitrary additional constraints to old versions after the fact. There hasn't been a lot of enthusiasm on the pub side for allowing this though (and I think it is probably more complicated than it seems on the surface, as is everything).

> Anyway, when is it that we need to use `frontend_server_client <4.0.0` then? Are there specific SDK versions?

I really don't know, but that is kind of the point. The only thing a package should have to care about is which versions of its dependencies it is API compatible with. This package wasn't broken by frontend_server_client version 4.x, so we only needed to increase the upper constraint.

**Comment by jakemac53** [comment] 2024-09-03 17:25
> So if my package is incompatible with `async: >=2.0.0<2.5.0` and `path: >=1.0.0 <1.8.0`, I wouldn't know about it.

This is always the case with `pub downgrade`? It doesn't give any guarantees, and I think it would in fact be very rare for it to actually provide the exact lower constraint from all deps (especially transitively).

You would anyways need your own tooling to check if the versions you actually got match the minimums you specified in your pubspec if you want to guarantee compatibility with those (or just know when you should bump them since you can't guarantee it).
