### ISSUE TITLE
No backtrace to error

### ISSUE THREAD

**Issue by normcf** [dart-lang/build#1532] opened 2018-06-07 03:26 UTC
john@transition:$ dart --version
Dart VM version: 2.0.0-dev.58.0 (Unknown timestamp) on "linux_x64"
john@transition:$ lsb_release -d
Description:	Ubuntu 18.04 LTS

webdev  serve -v --log-requests web
No builders from me.
Testing with Chrome Version 67.0.3396.62 (Official Build) (64-bit)
Using Apache2 with reverse proxy.  php is handled by Apache and everything else is passed to webdev.

Trying to debug and I get this in the console:

`dart_sdk.js:4831 Uncaught _js_helper.TypeErrorImpl.new {message: "Type '(MouseEvent$) => void' is not a subtype of expected type '(Event$) => void'.", Symbol(_error): Error at Object.dart.throw (http://192.168.1.200/packages/$sdk/dev_compiler/amd/dart_sdk.js:4830…} dart.throw @ dart_sdk.js:4831 async._rethrow @ dart_sdk.js:29268 async._schedulePriorityAsyncCallback.dart.fn @ dart_sdk.js:29263 async._microtaskLoop @ dart_sdk.js:25905 async._startMicrotaskLoop @ dart_sdk.js:25911 internalCallback @ dart_sdk.js:25981 childList (async) dart.fn.callback @ dart_sdk.js:25991 _scheduleImmediate @ dart_sdk.js:25967 async._scheduleAsyncCallback @ dart_sdk.js:25925 async._rootScheduleMicrotask @ dart_sdk.js:29319 scheduleMicrotask @ dart_sdk.js:29509 [_asyncComplete] @ dart_sdk.js:25584 complete @ dart_sdk.js:25117 xhr.(anonymous function).listen.dart.fn.e @ dart_sdk.js:78069 dart._checkAndCall @ dart_sdk.js:4651 dart.dcall @ dart_sdk.js:4656 (anonymous function).html$._wrapZone.dart.fn.e @ dart_sdk.js:98872 load (async) [_addEventListener] @ dart_sdk.js:56878 [dartx.addEventListener] @ dart_sdk.js:56868 [_tryResume] @ dart_sdk.js:98853 _EventStreamSubscription.new @ dart_sdk.js:98873 listen @ dart_sdk.js:98674 request @ dart_sdk.js:78063 postFormData @ dart_sdk.js:78030 refreshTab @ not.dart:780 refresh @ not.dart:748 chosen @ supertabview.dart:70 tabClicked @ supertabview.dart:61 dart._checkAndCall @ dart_sdk.js:4651 dart.dcall @ dart_sdk.js:4656 (anonymous function).html$._wrapZone.dart.fn.e @ dart_sdk.js:98872`

The code line at not.dart line 780 is 

`HttpRequest.postFormData(url, postArgs).then(onLogDataLoaded, onError: simpleHttpError); `

but after old school debugging (print statements in the code) I know this is not the problem.  The problem was in function onLogDataLoaded.  In this function (a few functions deep)  
`void handleDoubleClick(MouseEvent e) {...} `
was called.  After finding this line, I could change it to
`void handleDoubleClick(Event e) {...} `
which fixed it.  Note this has been running for a couple of years and gives no error in dart2js.

I could regen by putting the bug back if you need me to do anything.

**Comment by jakemac53** [comment] 2018-06-12 21:07
duplicate of https://github.com/dart-lang/build/issues/1532 I think

**Closed by jakemac53** 2018-06-12 21:07 UTC

**Comment by normcf** [comment] 2018-06-12 23:09
did you mean to say it was a duplicate of itself?
